--[[
    init.lua
    Created: 11/22/2023 12:14:44
    Description: Autogenerated script file for the map guild_outside.
]]--
-- Commonly included lua functions and data
require 'eos.common'
require 'eos.CharacterActions'
require 'eos.ExplorerEssentials'
require 'eos.PartnerEssentials'

-- Package name
local guild_outside = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---guild_outside.Init(map)
--Engine callback function
function guild_outside.Init(map)
	SOUND:PlayBGM("008 - Wigglytuff's Guild.ogg", true)
        player = CH("PLAYER")
        partner = CH("TEAMMATE_1") --why does this have to be like this?
        Bidoof = CH("Bidoof")

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  
COMMON:RespawnAllies()
PartnerEssentials.InitializePartnerSpawn()
end

---guild_outside.Enter(map)
--Engine callback function
function guild_outside.Enter(map)

  GAME:FadeIn(20)

  if SV.Progression.Chapter == 3 then
	if SV.Progression.SectionFlag == 4 then
	guild_outside.CH2BidoofTutorialScene3()
	end

  end

end
---guild_outside.Exit(map)
--Engine callback function
function guild_outside.Exit(map)
GAME:FadeOut(false, 20)

end

---guild_outside.Update(map)
--Engine callback function
function guild_outside.Update(map)


end

---guild_outside.GameSave(map)
--Engine callback function
function guild_outside.GameSave(map)


end

---guild_outside.GameLoad(map)
--Engine callback function
function guild_outside.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Cutscene Functions
-------------------------------

function guild_outside.CH2BidoofTutorialScene3()
	player = CH("PLAYER")
        partner = CH("TEAMMATE_1") --why does this have to be like this?
        Bidoof = CH("Bidoof")
	AI:DisableCharacterAI(partner)	
	GAME:MoveCamera(0, 0, 1, true)
	local hTalkKind = SV.Personality.HeroTalkKind
        local pTalkKind = SV.Personality.PartnerTalkKind
	Bidoof.CollisionDisabled = true
	partner.CollisionDisabled = true
        player.CollisionDisabled = true
	local marker = MRKR("GuildEntranceMarker")

	GAME:FadeIn(20)
	--coroutine begin
	GROUND:TeleportTo(Bidoof, marker.Position.X, marker.Position.Y, Direction.Down)
	GROUND:TeleportTo(player, marker.Position.X, marker.Position.Y, Direction.Down)
	GROUND:TeleportTo(partner, marker.Position.X, marker.Position.Y, Direction.Down)

        local coro2 = TASK:BranchCoroutine(function() GROUND:MoveToPosition(Bidoof, marker.Position.X, marker.Position.Y + 140, false, 1) end)
        local coro3 = TASK:BranchCoroutine(function() GAME:WaitFrames(30) GROUND:MoveToPosition(player, marker.Position.X, marker.Position.Y + 140, false, 1) end)
        local coro4 = TASK:BranchCoroutine(function() GAME:WaitFrames(60) GROUND:MoveToPosition(partner, marker.Position.X, marker.Position.Y + 140, false, 1) end )
	local coro5 = TASK:BranchCoroutine(function() GAME:WaitFrames(110) GAME:FadeOut(false, 60) end)
	TASK:JoinCoroutines({coro2, coro3, coro4, coro5})	

	SV.Progression.SectionFlag = 5	
	SV.partner.Spawn = 'GuildOutsideEntranceMarker'
	GAME:EnterGroundMap("crossroads_assembly", "GuildOutsideEntranceMarker")

end


-------------------------------
-- Entities Callbacks
-------------------------------

function guild_outside.GuildEntrance_Touch(obj, activator)

--GAME:EnterGroundMap("guild_top_floor", "Entrance")
SV.partner.Spawn = 'Ladder'
GAME:EnterGroundMap("guild_basement", "Ladder")

end

function guild_outside.CrossRoadsEntrance_Touch(obj, activator)
SV.partner.Spawn = 'GuildOutsideEntranceMarker'
GAME:EnterGroundMap("crossroads_assembly", "GuildOutsideEntranceMarker")

end

return guild_outside

