--[[
    init.lua
    Created: 07/03/2022 16:01:27
    Description: Autogenerated script file for the map personality_test.
]] --
-- Commonly included lua functions and data
require 'eos.common'
require 'eos.ExplorerEssentials'

-- Package name
local personality_test = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---personality_test.Init
--Engine callback function
function personality_test.Init(map)
	--This will fill the localized strings table automatically based on the locale the game is
	-- currently in. You can use the MapStrings table after this line!
end

local natures = {
	["bold"] = 0,
	["brave"] = 0,
	["calm"] = 0,
	["docile"] = 0,
	["hardy"] = 0,
	["hasty"] = 0,
	["impish"] = 0,
	["jolly"] = 0,
	["lonely"] = 0,
	["naive"] = 0,
	["quiet"] = 0,
	["quirky"] = 0,
	["rash"] = 0,
	["relaxed"] = 0,
	["sassy"] = 0,
	["timid"] = 0
}

local starterList = {
	-- Gen 1
	RogueEssence.Dungeon.MonsterID("bulbasaur", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("squirtle", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("charmander", 0, "normal", Gender.Genderless),

	RogueEssence.Dungeon.MonsterID("cubone", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("eevee", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("growlithe", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("machop", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("meowth", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("pikachu", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("psyduck", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("vulpix", 0, "normal", Gender.Genderless),
	--Gen 2
	RogueEssence.Dungeon.MonsterID("chikorita", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("totodile", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("cyndaquil", 0, "normal", Gender.Genderless),

	RogueEssence.Dungeon.MonsterID("phanpy", 0, "normal", Gender.Genderless),
	--Gen 3
	RogueEssence.Dungeon.MonsterID("treecko", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("mudkip", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("torchic", 0, "normal", Gender.Genderless),

	RogueEssence.Dungeon.MonsterID("skitty", 0, "normal", Gender.Genderless),
	--Gen 4
	RogueEssence.Dungeon.MonsterID("turtwig", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("piplup", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("chimchar", 0, "normal", Gender.Genderless),

	RogueEssence.Dungeon.MonsterID("munchlax", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("riolu", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("shinx", 0, "normal", Gender.Genderless),
	--Gen 5
	RogueEssence.Dungeon.MonsterID("snivy", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("oshawott", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("tepig", 0, "normal", Gender.Genderless),

	RogueEssence.Dungeon.MonsterID("axew", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("zorua", 0, "normal", Gender.Genderless),
	--RogueEssence.Dungeon.MonsterID("zorua", 1, "normal", Gender.Genderless),
	--Gen 6	
	RogueEssence.Dungeon.MonsterID("rowlet", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("popplio", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("litten", 0, "normal", Gender.Genderless),
	--Gen 7	
	RogueEssence.Dungeon.MonsterID("chespin", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("froakie", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("fennekin", 0, "normal", Gender.Genderless),

	RogueEssence.Dungeon.MonsterID("vulpix", 1, "normal", Gender.Genderless),
	--Gen 8	
	RogueEssence.Dungeon.MonsterID("grookey", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("sobble", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("scorbunny", 0, "normal", Gender.Genderless),
	--Gen 9	
	RogueEssence.Dungeon.MonsterID("sprigatito", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("quaxly", 0, "normal", Gender.Genderless),
	RogueEssence.Dungeon.MonsterID("fuecoco", 0, "normal", Gender.Genderless)
}

local egg_move_list = {
	--vanilla egg moves
	["vulpix"] = "feint_attack",
	["meowth"] = "hypnosis",
	["eevee"] = "flail",
	["phanpy"] = "ancient_power",
	["skitty"] = "zen_headbutt",
	["shinx"] = "quick_attack",
	["munchlax"] = "zen_headbutt",
	["riolu"] = "bite",
	--origins egg moves
	["machop"] = "close_combat",
	["cubone"] = "ancient_power",
	["psyduck"] = "cross_chop",
	["axew"] = "aqua_tail",
	["zorua"] = "extrasensory"
}

local natureMap = {
	[1] = {
		[1] = { { nature = "brave", points = 2 }, { nature = "hardy", points = 4 } },
		[2] = { { nature = "quirky", points = 4 } },
		[3] = { { nature = "rash", points = 2 }, { nature = "bold", points = 4 } },
	},
	[2] = {
		[1] = { { nature = "sassy", points = 2 }, { nature = "impish", points = 4 } },
		[2] = { { nature = "hardy", points = 4 } },
		[3] = { { nature = "quirky", points = 4 } },
	},
	[3] = {
		[1] = { { nature = "hardy", points = 4 } },
		[2] = { { nature = "hasty", points = 2 }, { nature = "quirky", points = 4 } },
		[3] = { { nature = "quiet", points = 2 } },
		[4] = { { nature = "lonely", points = 4 } },
	},
	[4] = {
		[1] = { { nature = "brave", points = 2 }, { nature = "hardy", points = 4 } },
		[2] = { { nature = "docile", points = 2 } },
		[3] = { { nature = "sassy", points = 2 }, { nature = "bold", points = 4 } },
	},
	[5] = {
		[1] = { { nature = "docile", points = 4 } },
		[2] = { { nature = "lonely", points = 2 }, { nature = "timid", points = 4 } },
	},
	[6] = {
		[1] = { { nature = "docile", points = 4 } },
		[2] = { { nature = "rash", points = 2 }, { nature = "naive", points = 4 } },
		[3] = { { nature = "impish", points = 4 } },
	},
	[7] = {
		[1] = { { nature = "timid", points = 2 }, { nature = "docile", points = 4 } },
		[2] = { { nature = "relaxed", points = 2 }, { nature = "jolly", points = 4 } },
	},
	[8] = {
		[1] = { { nature = "timid", points = 2 }, { nature = "bold", points = 4 } },
		[2] = { { nature = "docile", points = 4 }, { nature = "rash", points = 4 } },
		[3] = { { nature = "impish", points = 4 } },
	},
	[9] = {
		[1] = { { nature = "brave", points = 4 }, { nature = "impish", points = 4 } },
		[2] = { { nature = "quiet", points = 2 } },
		[3] = { { nature = "docile", points = 2 }, { nature = "timid", points = 4 } },
	},
	[10] = {
		[1] = { { nature = "brave", points = 4 } },
		[2] = { { nature = "timid", points = 2 }, { nature = "lonely", points = 4 } },
		[3] = { { nature = "quiet", points = 2 }, { nature = "quirky", points = 2 } },
	},
	[11] = {
		[1] = { { nature = "quiet", points = 2 }, { nature = "jolly", points = 4 } },
		[2] = { { nature = "naive", points = 2 }, { nature = "lonely", points = 4 } },
		[3] = { { nature = "brave", points = 4 }, { nature = "impish", points = 4 } },
		[4] = { { nature = "timid", points = 2 } },
	},
	[12] = {
		[1] = { { nature = "timid", points = 4 } },
		[2] = { { nature = "brave", points = 4 }, { nature = "sassy", points = 4 } },
		[3] = { { nature = "naive", points = 4 } },
	},
	[13] = {
		[1] = { { nature = "lonely", points = 2 }, { nature = "jolly", points = 4 } },
		[2] = { { nature = "quiet", points = 2 } },
	},
	[14] = {
		[1] = { { nature = "calm", points = 2 } },
		[2] = { { nature = "jolly", points = 4 }, { nature = "naive", points = 4 } },
		[3] = { { nature = "lonely", points = 2 }, { nature = "sassy", points = 4 } },
	},
	[15] = {
		[1] = { { nature = "jolly", points = 4 }, { nature = "naive", points = 4 } },
		[2] = { { nature = "docile", points = 2 }, { nature = "impish", points = 2 } },
		[3] = { { nature = "brave", points = 4 } },
	},
	[16] = {
		[1] = { { nature = "bold", points = 4 }, { nature = "jolly", points = 4 } },
		[2] = { { nature = "docile", points = 2 }, { nature = "timid", points = 2 } },
	},
	[17] = {
		[1] = { { nature = "impish", points = 4 }, { nature = "rash", points = 4 } },
		[2] = { { nature = "calm", points = 2 } },
	},
	[18] = {
		[1] = { { nature = "hasty", points = 2 }, { nature = "sassy", points = 2 } },
		[2] = { { nature = "impish", points = 4 } },
		[3] = { { nature = "lonely", points = 4 } },
	},
	[19] = {
		[1] = { { nature = "naive", points = 2 }, { nature = "impish", points = 4 } },
		[2] = { { nature = "timid", points = 2 }, { nature = "quirky", points = 4 } },
	},
	[20] = {
		[1] = { { nature = "rash", points = 2 }, { nature = "brave", points = 4 }, { nature = "hasty", points = 4 }, { nature = "impish", points = 4 } },
		[2] = { { nature = "timid", points = 2 } },
	},
	[21] = {
		[1] = { { nature = "lonely", points = 2 }, { nature = "brave", points = 4 } },
		[2] = { { nature = "rash", points = 2 }, { nature = "impish", points = 4 }, { nature = "naive", points = 4 } },
	},
	[22] = {
		[1] = { { nature = "hasty", points = 4 } },
		[2] = { { nature = "lonely", points = 4 } },
		[3] = { { nature = "impish", points = 4 }, { nature = "jolly", points = 4 }, { nature = "naive", points = 4 } },
	},
	[23] = {
		[1] = { { nature = "naive", points = 4 } },
		[2] = { { nature = "quiet", points = 2 } },
	},
	[24] = {
		[1] = { { nature = "impish", points = 2 }, { nature = "naive", points = 4 } },
		[2] = { { nature = "calm", points = 4 } },
	},
	[25] = {
		[1] = { { nature = "timid", points = 4 } },
		[2] = { { nature = "docile", points = 4 } },
		[3] = { { nature = "lonely", points = 4 }, { nature = "sassy", points = 4 } },
		[4] = { { nature = "relaxed", points = 4 } },
	},
	[26] = {
		[1] = { { nature = "brave", points = 2 }, { nature = "quiet", points = 2 } },
		[2] = { { nature = "lonely", points = 2 }, { nature = "calm", points = 4 } },
		[3] = { { nature = "rash", points = 2 }, { nature = "timid", points = 2 } },
	},
	[27] = {
		[1] = { { nature = "calm", points = 2 } },
		[2] = { { nature = "quirky", points = 2 } },
		[3] = { { nature = "timid", points = 4 } },
	},
	[28] = {
		[1] = { { nature = "relaxed", points = 4 } },
		[2] = { { nature = "naive", points = 4 } },
		[3] = { { nature = "timid", points = 4 } },
	},
	[29] = {
		[1] = { { nature = "hasty", points = 4 }, { nature = "rash", points = 4 } },
		[2] = { { nature = "docile", points = 2 }, { nature = "quiet", points = 2 } },
	},
	[30] = {
		[1] = { { nature = "hasty", points = 4 } },
		[2] = { { nature = "calm", points = 2 } },
	},
	[31] = {
		[1] = { { nature = "hasty", points = 4 } },
		[2] = { { nature = "quiet", points = 2 } },
		[3] = { { nature = "bold", points = 4 } },
	},
	[32] = {
		[1] = { { nature = "hasty", points = 4 } },
		[2] = { { nature = "hardy", points = 4 } },
		[3] = { { nature = "rash", points = 4 } },
	},
	[33] = {
		[1] = { { nature = "sassy", points = 4 } },
		[2] = { { nature = "calm", points = 2 } },
	},
	[34] = {
		[1] = { { nature = "lonely", points = 2 }, { nature = "sassy", points = 4 } },
		[2] = { { nature = "quirky", points = 2 }, { nature = "calm", points = 4 } },
	},
	[35] = {
		[1] = { { nature = "jolly", points = 2 }, { nature = "naive", points = 2 }, { nature = "sassy", points = 4 } },
		[2] = { { nature = "hardy", points = 2 } },
	},
	[36] = {
		[1] = { { nature = "brave", points = 4 }, { nature = "sassy", points = 4 } },
		[2] = { { nature = "timid", points = 2 } },
	},
	[37] = {
		[1] = { { nature = "sassy", points = 2 }, { nature = "lonely", points = 4 } },
		[2] = { { nature = "calm", points = 4 } },
		[3] = { { nature = "quirky", points = 4 } },
	},
	[38] = {
		[1] = { { nature = "calm", points = 4 } },
		[2] = { { nature = "jolly", points = 4 }, { nature = "relaxed", points = 4 } },
		[3] = { { nature = "lonely", points = 4 } },
	},
	[39] = {
		[1] = { { nature = "hardy", points = 4 } },
		[2] = { { nature = "docile", points = 4 } },
		[3] = { { nature = "bold", points = 4 }, { nature = "calm", points = 4 } },
	},
	[40] = {
		[1] = { { nature = "relaxed", points = 2 }, { nature = "bold", points = 4 } },
		[2] = { { nature = "hasty", points = 2 }, { nature = "lonely", points = 4 } },
	},
	[41] = {
		[1] = { { nature = "rash", points = 2 }, { nature = "hasty", points = 4 } },
		[2] = { { nature = "hardy", points = 2 } },
		[3] = { { nature = "relaxed", points = 2 }, { nature = "bold", points = 4 }, { nature = "jolly", points = 4 } },
	},
	[42] = {
		[1] = { { nature = "hardy", points = 4 } },
		[2] = { { nature = "relaxed", points = 4 } },
		[3] = { { nature = "naive", points = 4 } },
	},
	[43] = {
		[1] = { { nature = "docile", points = 4 }, { nature = "lonely", points = 4 } },
		[2] = { { nature = "jolly", points = 4 }, { nature = "relaxed", points = 4 } },
		[3] = { { nature = "bold", points = 4 } },
	},
	[44] = {
		[1] = { { nature = "jolly", points = 2 }, { nature = "relaxed", points = 4 } },
		[2] = { { nature = "quiet", points = 2 } },
	},
	[45] = {
		[1] = { { nature = "hasty", points = 4 }, { nature = "lonely", points = 4 } },
		[2] = { { nature = "quiet", points = 2 } },
		[3] = { { nature = "timid", points = 2 } },
	},
	[46] = {
		[1] = { { nature = "naive", points = 4 } },
		[2] = { { nature = "lonely", points = 4 } },
		[3] = { { nature = "timid", points = 2 } },
	},
	[47] = {
		[1] = { { nature = "lonely", points = 4 }, { nature = "sassy", points = 4 } },
		[2] = { { nature = "relaxed", points = 2 } },
	},
	[48] = {
		[1] = { { nature = "docile", points = 4 } },
		[2] = { { nature = "naive", points = 4 } },
		[3] = { { nature = "rash", points = 4 } },
		[4] = { { nature = "lonely", points = 4 } },
	},
	[49] = {
		[1] = { { nature = "hasty", points = 2 }, { nature = "rash", points = 2 }, { nature = "quirky", points = 4 } },
		[2] = { { nature = "quiet", points = 2 } },
	},
	[50] = {
		[1] = { { nature = "hardy", points = 4 } },
		[2] = { { nature = "hasty", points = 2 }, { nature = "quirky", points = 4 } },
	},
	[51] = {
		[1] = { { nature = "quirky", points = 4 }, { nature = "rash", points = 4 } },
		[2] = { { nature = "calm", points = 2 } },
	},
	[52] = {
		[1] = { { nature = "hardy", points = 4 } },
		[2] = { { nature = "rash", points = 2 }, { nature = "quirky", points = 4 } },
		[3] = { { nature = "relaxed", points = 4 } },
	},
	[53] = {
		[1] = { { nature = "bold", points = 4 }, { nature = "quiet", points = 4 } },
		[2] = { { nature = "brave", points = 4 } },
		[3] = { { nature = "docile", points = 4 } },
	},
	[54] = {
		[1] = { { nature = "jolly", points = 2 }, { nature = "naive", points = 4 } },
		[2] = { { nature = "timid", points = 2 } },
		[3] = { { nature = "quiet", points = 4 } },
	},
	[55] = {
		[1] = { { nature = "quiet", points = 4 }, { nature = "sassy", points = 4 } },
		[2] = { { nature = "brave", points = 4 } },
	},
	[56] = {
		[1] = { { nature = "hasty", points = 4 } },
		[2] = { { nature = "quiet", points = 4 } },
		[3] = { { nature = "timid", points = 2 } },
	},
	[57] = {
		[1] = { { nature = "docile", points = 4 } },
		[2] = { { nature = "rash", points = 4 } },
		[3] = { { nature = "jolly", points = 4 } },
	},
	[58] = {
		[1] = { { nature = "timid", points = 2 } },
		[2] = { { nature = "sassy", points = 2 }, { nature = "naive", points = 4 } },
		[3] = { { nature = "rash", points = 4 } },
	},
	[59] = {
		[1] = { { nature = "rash", points = 4 } },
		[2] = { { nature = "quiet", points = 2 } },
	},
	[60] = {
		[1] = { { nature = "lonely", points = 4 }, { nature = "rash", points = 4 } },
		[2] = { { nature = "hardy", points = 2 } },
	},
	[61] = {
		[1] = { { nature = "bold", points = 4 }, { nature = "brave", points = 4 } },
		[2] = { { nature = "hasty", points = 2 } },
		[3] = { { nature = "timid", points = 2 } },
	},
	[62] = {
		[1] = { { nature = "bold", points = 4 } },
		[2] = { { nature = "jolly", points = 4 } },
		[3] = { { nature = "quirky", points = 4 } },
	},
	[63] = {
		[1] = { { nature = "relaxed", points = 2 }, { nature = "brave", points = 4 } },
		[2] = { { nature = "timid", points = 2 } },
		[3] = { { nature = "bold", points = 4 } },
	},
	[64] = {
		[1] = { { nature = "impish", points = 4 }, { nature = "naive", points = 4 } },
		[2] = { { nature = "hardy", points = 2 } },
		[3] = { { nature = "bold", points = 4 } },
	},
}

local function addNature(question, answer)
	local questionMap = natureMap[question]
	if not questionMap then
		return
	end
	local points = questionMap[answer]
	if not points then
		return
	end
	for _, res in ipairs(points) do
		natures[res.nature] = (natures[res.nature] or 0) + res.points
	end
end

local convertGender = {
	[0] = Gender.Genderless,
	[1] = Gender.Male,
	[2] = Gender.Female
}

local function pokemonSelection(trait, gender)

	--[[

	Natures:
	1 = bold
	2 = brave
	3 = calm
	4 = docile
	5 = hardy
	6 = hasty
	7 = impish
	8 = jolly
	9 = lonely
	10 = naive
	11 = quiet
	12 = quirky
	13 = rash
	14 = relaxed
	15 = sassy
	16 = timid

	]]--

	local pokemonList = {
		[1] = {
			[0] = "riolu",
			[1] = "turtwig",
			[2] = "squirtle"
		},
		[2] = {
			[0] = "phanpy",
			[1] = "pikachu",
			[2] = "charmander"
		},
		[3] = {
			[0] = "treecko",
			[1] = "chikorita",
			[2] = "cyndaquil"
		},
		[4] = {
			[0] = "vulpix",
			[1] = "charmander",
			[2] = "bulbasaur"
		},
		[5] = {
			[0] = "charmander",
			[1] = "torchic",
			[2] = "treecko"
		},
		[6] = {
			[0] = "eevee",
			[1] = "shinx",
			[2] = "pikachu"
		},
		[7] = {
			[0] = "skitty",
			[1] = "piplup",
			[2] = "chimchar"
		},
		[8] = {
			[0] = "mudkip",
			[1] = "totodile",
			[2] = "eevee"
		},
		[9] = {
			[0] = "chimchar",
			[1] = "bulbasaur",
			[2] = "mudkip"
		},
		[10] = {
			[0] = "shinx",
			[1] = "chimchar",
			[2] = "skitty"
		},
		[11] = {
			[0] = "cyndaquil",
			[1] = "treecko",
			[2] = "chikorita"
		},
		[12] = {
			[0] = "totodile",
			[1] = "squirtle",
			[2] = "piplup"
		},
		[13] = {
			[0] = "pikachu",
			[1] = "mudkip",
			[2] = "torchic"
		},
		[14] = {
			[0] = "bulbasaur",
			[1] = "phanpy",
			[2] = "vulpix"
		},
		[15] = {
			[0] = "piplup",
			[1] = "riolu",
			[2] = "totodile"
		},
		[16] = {
			[0] = "turtwig",
			[1] = "cyndaquil",
			[2] = "turtwig"
		}
	}

	return RogueEssence.Dungeon.MonsterID(pokemonList[trait][gender], 0, "normal", convertGender[gender])
end

local function roll(randMin, randMax)
	local cont = 0
	local rand = 0
	while cont < 10 do
		cont = math.random(1, 10)
		rand = math.random(randMin, randMax)
	end

	return rand
end

-- 0 = silver (warm, light, soft, space)
-- 1 = brown (warm, dark, soft, time)
-- 2 = red (warm, dark, vibrant, time)
-- 3 = pink (warm, light, vibrant, space)
-- 4 = orange (warm, dark, soft, space)
-- 5 = yellow (warm, light, vibrant, time)
-- 6 = lime (warm, light, soft, time)
-- 7 = green (cool, light, soft, time)
-- 8 = viridian (cool, dark, vibrant, space)
-- 9 = minty (cool, light, vibrant, time)
-- 10 = sky blue (cool, light, soft, space)
-- 11 = blue (cool, light, vibrant, space)
-- 12 = cobalt (cool, dark, vibrant, time)
-- 13 = purple (cool, dark, soft, time)
-- 14 = violet (cool, dark, soft, space)
-- 15 = fuchsia (warm, dark, vibrant, space)

local auraTable = {
	[1] = { -- warm
		[1] = { -- light
			[1] = { -- soft
				-- time & space
				6,
				0
			},
			[2] = { -- vibrant
				-- time & space
				5,
				3
			}
		},
		[2] = { -- dark
			[1] = { -- soft
				-- time & space
				1,
				4
			},
			[2] = { -- vibrant
				-- time & space
				2,
				15
			}
		}
	},
	[2] = { -- cool
		[1] = { -- light
			[1] = { -- soft
				-- time & space
				7,
				10
			},
			[2] = { -- vibrant
				-- time & space
				9,
				11
			}
		},
		[2] = { -- dark
			[1] = { -- soft
				-- time & space
				13,
				14
			},
			[2] = { -- vibrant
				-- time & space
				12,
				8
			}
		}
	}
}

---personality_test.Enter
--Engine callback function
function personality_test.Enter(map)
	--Setup
	UI:WaitShowBG("Black", 1, 1)
	GROUND:Hide("PLAYER")
	UI:ResetSpeaker()
	UI:SetCenter(true)
	GAME:FadeIn(20)
	UI:WaitShowVoiceOver(STRINGS:Format(STRINGS.MapStrings['Disclaimer']), -1)

	-- Hide Aura Objects (Colored bows are fine because they're hidden OOB)
	GROUND:Hide("AuraBG")
	GROUND:Hide("AuraPulse")
	GROUND:Hide("AuraResultBG")
	GROUND:Hide("BlankBow")

	--Intro
	GAME:WaitFrames(120)
	for i = 1, 7, 1 do
		UI:WaitShowVoiceOver(STRINGS:Format(STRINGS.MapStrings['Intro_' .. tostring(i)]), -1)
	end
	GAME:WaitFrames(20)
	SOUND:PlayBGM("003 - Welcome to the World of Pokémon!.ogg", true)
	UI:WaitHideBG(60)

	UI:SetCenter(false)

	--Have you played before?
	local hasPlayed = false
	local skipQuiz = false

	UI:ChoiceMenuYesNo(STRINGS:Format(STRINGS.MapStrings['Quiz_Played_Q1']), true)
	UI:WaitForChoice()
	hasPlayed = UI:ChoiceResult()

	--Do you just want to skip the quiz then?
	if hasPlayed then
		UI:ChoiceMenuYesNo(STRINGS:Format(STRINGS.MapStrings['Quiz_Played_Q2']), true)
		UI:WaitForChoice()
		skipQuiz = UI:ChoiceResult()
	end

	--Randomize and output questions
	if not skipQuiz then
		local currentQ = {}
		local qTable = {}

		for i = 1, 64, 1 do
			table.insert(qTable, i)
		end

		for i = 1, #qTable, 1 do
			local rand = math.random(1, #qTable)
			table.insert(currentQ, qTable[rand])
			table.remove(qTable, rand)
		end

		for i = 1, 16, 1 do
			local choices = {}

			local rand = math.random(1, #currentQ)

			if not (STRINGS:Format(STRINGS.MapStrings['Quiz_Q' .. tostring(currentQ[rand]) .. '_A1']) == 'x') then
				table.insert(choices, STRINGS:Format(STRINGS.MapStrings['Quiz_Q' .. tostring(currentQ[rand]) .. '_A1']))
			end
			if not (STRINGS:Format(STRINGS.MapStrings['Quiz_Q' .. tostring(currentQ[rand]) .. '_A2']) == 'x') then
				table.insert(choices, STRINGS:Format(STRINGS.MapStrings['Quiz_Q' .. tostring(currentQ[rand]) .. '_A2']))
			end
			if not (STRINGS:Format(STRINGS.MapStrings['Quiz_Q' .. tostring(currentQ[rand]) .. '_A3']) == 'x') then
				table.insert(choices, STRINGS:Format(STRINGS.MapStrings['Quiz_Q' .. tostring(currentQ[rand]) .. '_A3']))
			end
			if not (STRINGS:Format(STRINGS.MapStrings['Quiz_Q' .. tostring(currentQ[rand]) .. '_A4']) == 'x') then
				table.insert(choices, STRINGS:Format(STRINGS.MapStrings['Quiz_Q' .. tostring(currentQ[rand]) .. '_A4']))
			end

			GAME:WaitFrames(1)
			UI:BeginChoiceMenu(STRINGS:Format(STRINGS.MapStrings['Quiz_Q' .. tostring(currentQ[rand]) .. '_A0']), choices,
				1, 3)
			UI:WaitForChoice()
			local result = UI:ChoiceResult()
			addNature(currentQ[rand], result)
			table.remove(currentQ, rand)
		end
	end

	--Gender
	local choices = { STRINGS:Format(STRINGS.MapStrings['Quiz_Gender_A1']),
		STRINGS:Format(STRINGS.MapStrings['Quiz_Gender_A2']),
		STRINGS:Format(STRINGS.MapStrings['Quiz_Gender_A3']) }

	UI:BeginChoiceMenu(STRINGS:Format(STRINGS.MapStrings['Quiz_Gender_A0']), choices, 1, 3)
	UI:WaitForChoice()
	local gender = UI:ChoiceResult()
	if gender == 3 then gender = 0 end
	
	if hasPlayed and not skipQuiz then
		if gender == 1 then
			natures["hasty"] = natures["hasty"] + 4
			natures["sassy"] = natures["sassy"] + 4
			natures["relaxed"] = natures["relaxed"] + 4
		elseif gender == 2 then
			natures["jolly"] = natures["jolly"] + 4
			natures["relaxed"] = natures["relaxed"] + 4
		else
			natures["hasty"] = natures["hasty"] + 2
			natures["sassy"] = natures["sassy"] + 2
			natures["relaxed"] = natures["relaxed"] + 2
			natures["jolly"] = natures["jolly"] + 2
		end
	end

	-- TODO: Revamp Aura Selection
	-- 0 = silver (warm, light, soft, space)
	-- 1 = brown (warm, dark, soft, time)
	-- 2 = red (warm, dark, vibrant, time)
	-- 3 = pink (warm, light, vibrant, space)
	-- 4 = orange (warm, dark, soft, space)
	-- 5 = yellow (warm, light, vibrant, time)
	-- 6 = lime (warm, light, soft, time)
	-- 7 = green (cool, light, soft, time)
	-- 8 = viridian (cool, dark, vibrant, space)
	-- 9 = minty (cool, light, vibrant, time)
	-- 10 = sky blue (cool, light, soft, space)
	-- 11 = blue (cool, light, vibrant, space)
	-- 12 = cobalt (cool, dark, vibrant, time)
	-- 13 = purple (cool, dark, soft, time)
	-- 14 = violet (cool, dark, soft, space)
	-- 15 = fuchsia (warm, dark, vibrant, space)

	-- Aura

	-- SFX:
	-- Pulse = _UNK_EVT_129
	-- Result Jingle = _UNK_EVT_078(X) (Can't find correct one)

	-- Fade Out and switch to aura BG
	GAME:FadeOut(false, 60)
	GROUND:Unhide("AuraBG")
	GROUND:Unhide("AuraPulse")
	GROUND:Unhide("BlankBow")
	GAME:MoveCamera(160, 120, 1, false) -- move camera to map center

	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Quiz_Aura_1']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Quiz_Aura_2']))

	-- Loop Pulse SFX
	SOUND:LoopSE("Battle/_UNK_EVT_129")

	GAME:FadeIn(60)
	GAME:WaitFrames(30)

	local auraResult = {}
	for i = 1, 4, 1 do
		local choices = { STRINGS:Format(STRINGS.MapStrings['Quiz_Aura_Q' .. tostring(i) .. '_A1']),
			STRINGS:Format(STRINGS.MapStrings['Quiz_Aura_Q' .. tostring(i) .. '_A2']),
			STRINGS:Format(STRINGS.MapStrings['Quiz_Aura_Unsure']) }

		GAME:WaitFrames(1)
		UI:BeginChoiceMenu(STRINGS:Format(STRINGS.MapStrings['Quiz_Aura_Q' .. tostring(i) .. '_A0']), choices, 1, 3)
		UI:WaitForChoice()
		if UI:ChoiceResult() < 3 then
			table.insert(auraResult, UI:ChoiceResult())
		else
			table.insert(auraResult, (math.random(1, 100) % 2) + 1)
		end
	end

	local bowStrings = {
		"Silver",
		"Brown",
		"Red",
		"Pink",
		"Orange",
		"Yellow",
		"Lime",
		"Green",
		"Viridian",
		"Minty",
		"SkyBlue",
		"Blue",
		"Cobalt",
		"Purple",
		"Violet",
		"Fuchsia"
	}

	local auraColor = auraTable[auraResult[1]][auraResult[2]][auraResult[3]][auraResult[4]]

	-- Fade To White
	local coro1 = TASK:BranchCoroutine(function() GAME:FadeOut(true, 60) end)
	local coro2 = TASK:BranchCoroutine(function() SOUND:FadeOutSE("Battle/_UNK_EVT_129", 60) end)
	TASK:JoinCoroutines({ coro1, coro2 })

	GAME:WaitFrames(30)
	GAME:FadeOutFront(false, 60)

	-- hotswitch to black transition on lower layer so the text is shown
	GAME:FadeOut(false, 1)
	GAME:FadeInFront(1)

	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Quiz_Aura_5']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Quiz_Aura_6']))

	-- Switch BGs
	GROUND:Unhide("AuraResultBG")
	GROUND:Hide("AuraBG")
	GROUND:Hide("AuraPulse")

	-- Set Colored Bow
	local bow = OBJ('Bow_' .. bowStrings[auraColor + 1])
	GROUND:TeleportTo(bow, OBJ('BlankBow').Position.X, OBJ('BlankBow').Position.Y, Direction.Left)
	GROUND:Hide("BlankBow")

	-- Fade From White
	GAME:WaitFrames(20)
	GAME:FadeOutFront(true, 60)
	GAME:FadeOut(true, 1)
	GAME:FadeInFront(1)
	GAME:WaitFrames(60)

	local coro1 = TASK:BranchCoroutine(function() GAME:FadeIn(60) end)                                                                                    -- fade
	local coro2 = TASK:BranchCoroutine(function() SOUND:PlaySE("Battle/_UNK_EVT_078") end)                                                                -- sfx
	local coro3 = TASK:BranchCoroutine(function() UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings
		['Quiz_Aura_Result_' .. tostring(auraColor + 1)])) end)                                                                                           -- text
	local coro4 = TASK:BranchCoroutine(function()
		local emitter = RogueEssence.Content.FiniteReleaseEmitter(RogueEssence.Content.AnimData("AuraParticle", 3))
		emitter.Bursts = 5
		emitter.ParticlesPerBurst = 8
		emitter.BurstTime = 10

		emitter.StartDistance = 8
		emitter.Speed = 120
		GROUND:PlayVFX(emitter, GAME:GetCameraCenter().X, GAME:GetCameraCenter().Y)
	end)
	TASK:JoinCoroutines({ coro1, coro2, coro3, coro4 })

	-- Fade Out and return to normal quiz
	GAME:FadeOut(false, 60)
	GROUND:Hide("AuraResultBG")
	GROUND:Hide("Bow_" .. bowStrings[auraColor + 1])
	GAME:MoveCamera(0, 0, 1, false) -- move camera back to origin
	GAME:FadeIn(60)
	GAME:WaitFrames(30)

	--Color Selection (Aura Replacement)
	--choices = {STRINGS:Format(STRINGS.MapStrings['Quiz_Color_A1']),
	--STRINGS:Format(STRINGS.MapStrings['Quiz_Color_A2']),
	--STRINGS:Format(STRINGS.MapStrings['Quiz_Color_A3']),
	--STRINGS:Format(STRINGS.MapStrings['Quiz_Color_A4']),
	--STRINGS:Format(STRINGS.MapStrings['Quiz_Color_A5']),
	--STRINGS:Format(STRINGS.MapStrings['Quiz_Color_A6']),
	--STRINGS:Format(STRINGS.MapStrings['Quiz_Color_A7']),
	--STRINGS:Format(STRINGS.MapStrings['Quiz_Color_A8']),
	--STRINGS:Format(STRINGS.MapStrings['Quiz_Color_A9']),
	--STRINGS:Format(STRINGS.MapStrings['Quiz_Color_A10']),
	--STRINGS:Format(STRINGS.MapStrings['Quiz_Color_A11'])}

	--UI:BeginChoiceMenu(STRINGS:Format(STRINGS.MapStrings['Quiz_Color_A0']), choices, 1, 3)
	--UI:WaitForChoice()
	--result = UI:ChoiceResult()
	--favColor = result

	--Test Results
	local natureVars = { "bold", "brave", "calm", "docile", "hardy", "hasty", "impish", "jolly", "lonely", "naive",
		"quiet", "quirky", "rash", "relaxed", "sassy", "timid" }
	local mainTrait = 0
	local mainTraitVal = 0

	if not skipQuiz then
		for v, i in ipairs(natureVars) do
			print(i)
			if natures[i] > mainTraitVal then
				mainTraitVal = natures[i]
				mainTrait = v
			elseif natures[i] == mainTraitVal then
				local rand = math.random(1, 100)
				if rand >= 50 then
					mainTraitVal = natures[i]
					mainTrait = v
				end
			end
		end

		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Nature_Intro']))
		for i = 1, 8, 1 do
			if not (STRINGS:Format(STRINGS.MapStrings['Nature_' .. tostring(mainTrait) .. '_' .. tostring(i)]) == 'x') then
				UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Nature_' .. tostring(mainTrait) .. '_' .. tostring(i)]))
			end
		end

		GAME:RemovePlayerTeam(0)
		--GAME:RemovePlayerTeam(1)
		--GAME:RemovePlayerTeam(2)
		local pkm = pokemonSelection(mainTrait, gender)
		GAME:WaitFrames(1)
		_DATA.Save.ActiveTeam.Players:Add(_DATA.Save.ActiveTeam:CreatePlayer(_DATA.Save.Rand, pkm, 5, "", 0))

		--add egg move (thanks again palika)
		if GAME:GetCharacterSkill(GAME:GetPlayerPartyMember(0), 3) ~= "" then
			GAME:SetCharacterSkill(GAME:GetPlayerPartyMember(0), egg_move_list[pkm.Species], 3) --override move in slot 4 if 4 moves are known. They can always go see slowpoke to get it back
		else
			GAME:LearnSkill(GAME:GetPlayerPartyMember(0), egg_move_list[pkm.Species])
		end

		SV.General.Starter = pkm
		SV.PlayerInputs.AuraColor = auraColor
		SV.PlayerInputs.Personality = mainTrait

		_DATA.Save:UpdateTeamProfile(true)
		_DATA.Save.ActiveTeam.Players[0].IsFounder = true
		_DATA.Save.ActiveTeam.Players[0].IsPartner = true

		GAME:WaitFrames(20)
		ExplorerEssentials.SetPlayerFromData(pkm)

		for i = 1, 10, 1 do
			GROUND:Unhide("PLAYER")
			GAME:WaitFrames(5)
			GROUND:Hide("PLAYER")
			GAME:WaitFrames(5)
		end

		GROUND:Unhide("PLAYER")

		GAME:WaitFrames(30)
		UI:SetCenter(true)
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Quiz_Result'],
			_DATA:GetMonster(pkm.Species):GetColoredName()))
		UI:SetCenter(false)

		UI:ChoiceMenuYesNo(STRINGS:Format(STRINGS.MapStrings['Choice_Prompt'],
			_DATA:GetMonster(pkm.Species):GetColoredName()))
		UI:WaitForChoice()

		if not UI:ChoiceResult() then
			GROUND:Hide("PLAYER")

			local continue = false
			local txt = STRINGS:Format(STRINGS.MapStrings['Starter_Select'])
			pkm = -1

			while not continue do
				for i = 1, #starterList do
					starterList[i].Gender = convertGender[gender]
				end

				UI:ChooseMonsterMenu("", starterList)
				
				UI:WaitForChoice()
				local result = UI:ChoiceResult()
				pkm = result
				pkm.Gender = convertGender[gender]
				GAME:RemovePlayerTeam(0)
				GAME:WaitFrames(1)
				_DATA.Save.ActiveTeam.Players:Add(_DATA.Save.ActiveTeam:CreatePlayer(_DATA.Save.Rand, pkm, 5, "", 0))

				--add egg move (thanks again palika)
				if GAME:GetCharacterSkill(GAME:GetPlayerPartyMember(0), 3) ~= "" then
					GAME:SetCharacterSkill(GAME:GetPlayerPartyMember(0), egg_move_list[pkm.Species], 3) --override move in slot 4 if 4 moves are known. They can always go see slowpoke to get it back
				else
					GAME:LearnSkill(GAME:GetPlayerPartyMember(0), egg_move_list[pkm.Species])
				end

				ExplorerEssentials.SetPlayerFromData(pkm)
				UI:ChoiceMenuYesNo(STRINGS:Format(STRINGS.MapStrings['Choice_Prompt'],
					_DATA:GetMonster(pkm.Species):GetColoredName()))
				UI:WaitForChoice()
				continue = UI:ChoiceResult()
				if not continue then
					GROUND:Hide("PLAYER")
				end
			end

			--GAME:SetCharacterNickname(GAME:GetPlayerPartyMember(0), name)
			SV.General.Starter = pkm

			_DATA.Save:UpdateTeamProfile(true)
			_DATA.Save.ActiveTeam.Players[0].IsFounder = true
			_DATA.Save.ActiveTeam.Players[0].IsPartner = true
		end
	else
		SV.PlayerInputs.AuraColor = auraColor
		SV.PlayerInputs.Personality = mainTrait

		local continue = false
		local txt = STRINGS:Format(STRINGS.MapStrings['Starter_Select'])
		local pkm = -1

		local heroListNum = 0

		while not continue do
			for i = 1, #starterList do
				starterList[i].Gender = convertGender[gender]
			end
				
			UI:ChooseMonsterMenu("", starterList)
			UI:WaitForChoice()
			local result = UI:ChoiceResult()
			pkm = result
			pkm.Gender = convertGender[gender]

			for i = 1, #starterList do
				if starterList[i] == pkm then
					heroListNum = i
					break
				end
			end

			GAME:RemovePlayerTeam(0)
			GAME:WaitFrames(1)
			_DATA.Save.ActiveTeam.Players:Add(_DATA.Save.ActiveTeam:CreatePlayer(_DATA.Save.Rand, pkm, 5, "", 0))

			--add egg move (thanks again palika)
			if GAME:GetCharacterSkill(GAME:GetPlayerPartyMember(0), 3) ~= "" then
				GAME:SetCharacterSkill(GAME:GetPlayerPartyMember(0), egg_move_list[pkm.Species], 3) -- override move in slot 4 if 4 moves are known
			else
				GAME:LearnSkill(GAME:GetPlayerPartyMember(0), egg_move_list[pkm.Species])
			end

			ExplorerEssentials.SetPlayerFromData(pkm)
			UI:ChoiceMenuYesNo(STRINGS:Format(STRINGS.MapStrings['Choice_Prompt'],
				_DATA:GetMonster(pkm.Species):GetColoredName()))
			UI:WaitForChoice()
			continue = UI:ChoiceResult()
			if not continue then
				GROUND:Hide("PLAYER")
			end
		end

		_DATA.Save:UpdateTeamProfile(true)
		_DATA.Save.ActiveTeam.Players[0].IsFounder = true
		_DATA.Save.ActiveTeam.Players[0].IsPartner = true
	end

	--Partner Selection
	GROUND:Hide("PLAYER")
	_DATA.Save.ActiveTeam.Players:Add(_DATA.Save.ActiveTeam:CreatePlayer(_DATA.Save.Rand,
		RogueEssence.Dungeon.MonsterID("missingno", 0, "normal", Gender.Genderless), 5, "", 0))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Partner_Intro']))

	local continue = false
	local txt = STRINGS:Format(STRINGS.MapStrings['Partner_Select'])
	local pkm = -1

	local partnerListNum = 0

	while not continue do
		UI:ChooseMonsterMenu("", starterList)
		UI:WaitForChoice()
		local result = UI:ChoiceResult()
		print(result)
		pkm = result

		for i = 1, #starterList do
			if starterList[i] == pkm then
				partnerListNum = i
				break
			end
		end

		GAME:RemovePlayerTeam(1)
		GAME:WaitFrames(1)
		_DATA.Save.ActiveTeam.Players:Add(_DATA.Save.ActiveTeam:CreatePlayer(_DATA.Save.Rand, pkm, 5, "", 0))
		ExplorerEssentials.SetPlayerFromData(pkm)
		UI:ChoiceMenuYesNo(STRINGS:Format(STRINGS.MapStrings['Choice_Prompt'],
			_DATA:GetMonster(pkm.Species):GetColoredName()))
		UI:WaitForChoice()
		continue = UI:ChoiceResult()
		if _DATA.Save.ActiveTeam.Players[0].Element1 == _DATA.Save.ActiveTeam.Players[1].Element1 and continue then
			UI:ChoiceMenuYesNo(STRINGS:Format(STRINGS.MapStrings['Partner_Warning'],
				_DATA:GetMonster(pkm.Species):GetColoredName()))
			UI:WaitForChoice()
			continue = UI:ChoiceResult()
		end
		if not continue then
			GROUND:Hide("PLAYER")
		end
	end

	--Partner Gender
	choices = { STRINGS:Format(STRINGS.MapStrings['Quiz_Gender_A1']),
		STRINGS:Format(STRINGS.MapStrings['Quiz_Gender_A2']),
		STRINGS:Format(STRINGS.MapStrings['Quiz_Gender_A3']) }

	UI:BeginChoiceMenu(STRINGS:Format(STRINGS.MapStrings['Partner_Gender']), choices, 1, 3)
	UI:WaitForChoice()
	local result = UI:ChoiceResult()
	GAME:RemovePlayerTeam(1)

	GAME:WaitFrames(1)

	if result == 1 then pkm.Gender = Gender.Male end
	if result == 2 then pkm.Gender = Gender.Female end
	if result == 3 then pkm.Gender = Gender.Genderless end

	GAME:RemovePlayerTeam(1)
	GAME:WaitFrames(1)
	_DATA.Save.ActiveTeam.Players:Add(_DATA.Save.ActiveTeam:CreatePlayer(_DATA.Save.Rand, pkm, 5, "", 0))
	ExplorerEssentials.SetPlayerFromData(pkm)

	--add egg move (thanks again palika)
	if GAME:GetCharacterSkill(GAME:GetPlayerPartyMember(1), 3) ~= "" then
		GAME:SetCharacterSkill(GAME:GetPlayerPartyMember(1), egg_move_list[pkm.Species], 3) -- override move in slot 4 if 4 moves are known
	else
		GAME:LearnSkill(GAME:GetPlayerPartyMember(1), egg_move_list[pkm.Species])
	end

	_DATA.Save.ActiveTeam.Players[1].IsFounder = true
	_DATA.Save.ActiveTeam.Players[1].IsPartner = true

	--Partner Name
	local ch = false
	local name = ""
	while not ch do
		name = ""
		while name == "" do
			UI:NameMenu(STRINGS:Format(STRINGS.MapStrings['Name_Title']), "")
			UI:WaitForChoice()
			name = UI:ChoiceResult()
		end

		GAME:SetCharacterNickname(GAME:GetPlayerPartyMember(1), name)
		UI:ChoiceMenuYesNo(STRINGS:Format(STRINGS.MapStrings['Name_Confirm'], name), true)
		UI:WaitForChoice()
		ch = UI:ChoiceResult()
	end

	SV.General.Starter = GAME:GetPlayerPartyMember(0)
	SV.General.Partner = GAME:GetPlayerPartyMember(1)

	GROUND:Hide("PLAYER")

	--Partner Text
	-- 0 = Neutral
	-- 1 = "Cool"
	-- 2 = "Cute"
	if _DATA.Save.ActiveTeam.Players[1].Gender == Gender.Male then
		local randResult = roll(1, 100)

		if randResult <= 10 then -- 10%
			SV.Personality.PartnerTalkKind = 2
		elseif randResult > 10 and randResult <= 50 then -- 40%
			SV.Personality.PartnerTalkKind = 1
		elseif randResult > 50 then -- 50%
			SV.Personality.PartnerTalkKind = 0
		end
	elseif _DATA.Save.ActiveTeam.Players[1].Gender == Gender.Female then
		local randResult = roll(1, 100)

		if randResult <= 10 then -- 10%
			SV.Personality.PartnerTalkKind = 1
		elseif randResult > 10 and randResult <= 50 then -- 40%
			SV.Personality.PartnerTalkKind = 2
		elseif randResult > 50 then -- 50%
			SV.Personality.PartnerTalkKind = 0
		end
	else
		local randResult = roll(1, 100)

		if randResult <= 25 then -- 25%
			SV.Personality.PartnerTalkKind = 1
		elseif randResult > 25 and randResult <= 50 then -- 25%
			SV.Personality.PartnerTalkKind = 2
		elseif randResult > 50 then -- 50%
			SV.Personality.PartnerTalkKind = 0
		end
	end

	--Hero Text
	if _DATA.Save.ActiveTeam.Players[0].Gender == Gender.Female then
		SV.Personality.HeroTalkKind = 1
	else
		SV.Personality.HeroTalkKind = 0
	end

	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Conclusion_1']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Conclusion_2']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['Conclusion_3']))

	SOUND:FadeOutBGM(120)
	GAME:FadeOut(false, 120)

	GROUND:SetPlayer(GAME:GetPlayerPartyMember(0))

	GAME:SetCanSwitch(false)
	GAME:SetTeamName('????')
	_DATA.Save.ActiveTeam:SetRank('none')
	_DATA.Save.ActiveTeam.Fame = 0
	_DATA.Save:UpdateTeamProfile(true)

	GAME:EnterGroundMap("chapter_card", "Entrance")
end

---personality_test.Exit
--Engine callback function
function personality_test.Exit(map)

end

---personality_test.Update
--Engine callback function
function personality_test.Update(map)

end

---personality_test.GameSave
--Engine callback function
function personality_test.GameSave(map)

end

---personality_test.GameLoad
--Engine callback function
function personality_test.GameLoad(map)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return personality_test
