--[[
    init.lua
    Created: 10/31/2023 15:01:40
    Description: Autogenerated script file for the map dusk_beach.
]]--
-- Commonly included lua functions and data
require 'eos.common'
require 'eos.CharacterActions'
require 'eos.ExplorerEssentials'

-- Package name
local dusk_beach = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---dusk_beach.Init(map)
--Engine callback function
function dusk_beach.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  
  ExplorerEssentials.SpawnPartner()

  stopBubbles = false
end

---dusk_beach.Enter(map)
--Engine callback function
function dusk_beach.Enter(map)
  GAME:CutsceneMode(true)
  
  if SV.Progression.Chapter == 1 then

	--PrintInfo("SectionFlag: "..tostring(SV.Progression.SectionFlag))
	--PrintInfo("FailedDungeon: "..tostring(SV.beach_cave.FailedDungeon))
  
	if SV.Progression.SectionFlag == 1 then
		dusk_beach.CH1_ExplorerTeamInvite()
	elseif SV.beach_cave.FailedDungeon == true then
		dusk_beach.CH1_FailedBeachCave()
	else
		dusk_beach.CH1_PartnerFindsHero()
	end
  end
  
  if SV.Progression.Chapter == 16 then
	dusk_beach.CH16_BackInThePast()
  end
  
end

---dusk_beach.Exit(map)
--Engine callback function
function dusk_beach.Exit(map)


end

---dusk_beach.Update(map)
--Engine callback function
function dusk_beach.Update(map)


end

---dusk_beach.GameSave(map)
--Engine callback function
function dusk_beach.GameSave(map)


end

---dusk_beach.GameLoad(map)
--Engine callback function
function dusk_beach.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------



-------------------------------
-- Cutscene Functions
-------------------------------

function dusk_beach.CH1_PartnerFindsHero()
	
	local player = CH('PLAYER')
	local partner = CH('PARTNER')
	
	partner.CollisionDisabled = true
	
	local hTalkKind = SV.Personality.HeroTalkKind
	local pTalkKind = SV.Personality.PartnerTalkKind

	AI:DisableCharacterAI(partner)
	
	local marker = MRKR("Entrance")
	local cam = MRKR("C1S1_CamPos_1")
	
	GROUND:TeleportTo(partner, marker.Position.X - 120, marker.Position.Y, Direction.Left)
	GAME:MoveCamera(cam.Position.X, cam.Position.Y, 1, false)

	GROUND:Hide("PLAYER")

	if SV.Cutscene.ProgressFlag == 0 then -- initial beach shot

		GROUND:Hide("PARTNER")

		--fade in to initial shot
		local coro1 = TASK:BranchCoroutine(function() SOUND:FadeInSE("Ambient/AMB_Ocean", 60) end)
		local coro2 = TASK:BranchCoroutine(function() GAME:FadeIn(60) end)
		TASK:JoinCoroutines({coro1, coro2})
	
		GAME:WaitFrames(120)
	
		GAME:FadeOut(false, 60)

		SV.Cutscene.ProgressFlag = 1
		GAME:EnterGroundMap("krabby_scene_a", "Entrance")

	elseif SV.Cutscene.ProgressFlag == 1 then -- partner arrives

		GROUND:Hide("PARTNER")

		--partner walks up
		local bubbles = TASK:BranchCoroutine(function()
			dusk_beach.UTIL_PopulateBubbles()
			dusk_beach.UTIL_BubbleSpawnerLoop()
		end)
		local main = TASK:BranchCoroutine(function() -- contains everything else that happens while bubbles run in the bg

		GAME:FadeIn(60)
	
		GAME:WaitFrames(60)
	
		GROUND:Unhide("PARTNER")
		GROUND:MoveToPosition(partner, cam.Position.X, marker.Position.Y, false, 1)
	
		GAME:WaitFrames(10)

		GROUND:CharAnimateTurnTo(partner, Direction.Up, 4)

		GAME:WaitFrames(10)
	
		UI:SetSpeaker(partner)
		UI:SetSpeakerEmotion("Inspired")
	
		local coro1 = TASK:BranchCoroutine(function() UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_1_'..tostring(pTalkKind)])) end)
		local coro2 = TASK:BranchCoroutine(function() GROUND:MoveToPosition(partner, cam.Position.X, cam.Position.Y, false, 1) end)
		TASK:JoinCoroutines({coro1, coro2})
	
		GAME:WaitFrames(60)
	
		GAME:FadeOut(false, 60)

		SV.Cutscene.ProgressFlag = 2
		stopBubbles = true -- ALWAYS NEEDS TO BE CALLED BEFORE GROUND MAP CHANGE OR ELSE YOU'RE SOFTLOCKED
		GAME:EnterGroundMap("sunset_view", "Entrance", true)

		end)
		TASK:JoinCoroutines({main, bubbles})

	elseif SV.Cutscene.ProgressFlag == 2 then -- partner talks about bubbles

		local bubbles = TASK:BranchCoroutine(function()
			dusk_beach.UTIL_PopulateBubbles()
			dusk_beach.UTIL_BubbleSpawnerLoop()
		end)
		local main = TASK:BranchCoroutine(function() -- contains everything else that happens while bubbles run in the bg

		--back to partner
		GROUND:TeleportTo(partner, cam.Position.X, cam.Position.Y, Direction.Up)

		GAME:FadeIn(60)
		GAME:WaitFrames(60)
		
		UI:SetSpeaker(partner)
		UI:SetSpeakerEmotion("Normal")
		
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_2'], _DATA:GetMonster("krabby"):GetColoredName()))
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_3_'..tostring(pTalkKind)]))
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_4_'..tostring(pTalkKind)]))
		
		GAME:FadeOut(false, 60)

		SV.Cutscene.ProgressFlag = 3
		stopBubbles = true -- ALWAYS NEEDS TO BE CALLED BEFORE GROUND MAP CHANGE OR ELSE YOU'RE SOFTLOCKED
		GAME:EnterGroundMap("sunset_view", "Entrance", true)

		end)
		TASK:JoinCoroutines({main, bubbles})

	elseif SV.Cutscene.ProgressFlag == 3 then -- partner finds hero

		SV.Cutscene.ProgressFlag = 0 -- reset flag for future cutscenes

		--partner walks up
		local bubbles = TASK:BranchCoroutine(function()
			dusk_beach.UTIL_PopulateBubbles()
			dusk_beach.UTIL_BubbleSpawnerLoop()
		end)
		local main = TASK:BranchCoroutine(function() -- contains everything else that happens while bubbles run in the bg
		
		--partner exposition
		GROUND:TeleportTo(partner, cam.Position.X, cam.Position.Y, Direction.Up)

		GAME:FadeIn(60)
		GAME:WaitFrames(60)
		
		UI:SetSpeaker(partner)
		UI:SetSpeakerEmotion("Normal")

		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_5']))
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_6_'..tostring(pTalkKind)]))
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_7']))
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_8_'..tostring(pTalkKind)]))
		
		--bgm fade out
		local coro1 = TASK:BranchCoroutine(function() SOUND:FadeOutBGM(120) end)
		local coro2 = TASK:BranchCoroutine(function() GAME:WaitFrames(60) end)
		TASK:JoinCoroutines({coro1, coro2})
		
		GROUND:CharAnimateTurnTo(partner, Direction.Left, 8)
		
		GAME:WaitFrames(30)
		
		SOUND:PlayBattleSE("EVT_Emote_Exclaim")
		GROUND:CharSetEmote(partner, "notice", 1)
		
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_9']))
		
		--partner notices something
		local marker = MRKR("C1S1_PlayerSpawn")
		GROUND:TeleportTo(player, marker.Position.X, marker.Position.Y, Direction.Right)
		GROUND:Unhide("PLAYER")
		GROUND:CharSetAnim(player, "Laying", true)
		
		local coro1 = TASK:BranchCoroutine(function() GAME:MoveCamera(cam.Position.X - 60, cam.Position.Y, 60, false) end)
		local coro2 = TASK:BranchCoroutine(function() GROUND:MoveInDirection(partner, Direction.Left, 60, false, 1) end)
		TASK:JoinCoroutines({coro1, coro2})
		
		SOUND:PlayBattleSE("EVT_Emote_Startled")
		GROUND:CharSetEmote(partner, "shock", 1)
		CharacterActions.ScaredJump(partner, Direction.Left)
		
		UI:SetSpeakerEmotion("Surprised")
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_10']))
		
		local coro1 = TASK:BranchCoroutine(function() GAME:MoveCamera(player.Position.X + 40, cam.Position.Y, 60, false) end)
		local coro2 = TASK:BranchCoroutine(function() GROUND:MoveInDirection(partner, Direction.Left, 60, false, 2) end)
		TASK:JoinCoroutines({coro1, coro2})
		
		CharacterActions.HopTwice(partner, Direction.Left)
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_11']))
		
		--partner wakes up hero
		GROUND:CharSetDrawEffect(player, DrawEffect.Shaking)
		GAME:WaitFrames(10)
		GROUND:CharEndDrawEffect(player, DrawEffect.Shaking)
		
		ExplorerEssentials.SetSpeakerHero()
		UI:SetSpeakerEmotion("Pain")
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Hero_1']))
		
		local coro1 = TASK:BranchCoroutine(function() UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Hero_2'])) end)
		local coro2 = TASK:BranchCoroutine(function() GAME:WaitFrames(10)
													GROUND:CharSetDrawEffect(player, DrawEffect.Shaking)
													GAME:WaitFrames(20)
													GROUND:CharEndDrawEffect(player, DrawEffect.Shaking) end)
		TASK:JoinCoroutines({coro1, coro2})
		
		GROUND:CharWaitAnim(player, "Wake")
		GAME:WaitFrames(30)
		GROUND:CharAnimateTurnTo(player, Direction.Down, 4)
		
		SOUND:PlayBattleSE("EVT_Emote_Exclaim")
		GROUND:CharSetEmote(partner, "exclaim", 1)
		GAME:WaitFrames(30)
		
		UI:SetSpeaker(partner)
		UI:SetSpeakerEmotion("Normal")
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_12_'..tostring(pTalkKind)]))
		
		GAME:WaitFrames(10)
		
		local coro1 = TASK:BranchCoroutine(function() GROUND:CharAnimateTurnTo(player, Direction.Left, 4) end)
		local coro2 = TASK:BranchCoroutine(function() GROUND:AnimateInDirection(partner, "Walk", Direction.Left, Direction.Right, 20, 1, 1) end)
		TASK:JoinCoroutines({coro1, coro2})
		
		GAME:WaitFrames(15)
		GROUND:CharAnimateTurnTo(player, Direction.Right, 4)
		GAME:WaitFrames(30)
		GROUND:CharAnimateTurnTo(player, Direction.Down, 4)
		GAME:WaitFrames(45)
		
		ExplorerEssentials.SetSpeakerHero()
		UI:SetSpeakerEmotion("Normal")
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Hero_3']))
		
		GAME:WaitFrames(10)
		GROUND:CharTurnToCharAnimated(player, partner, 4, true)
		
		UI:SetSpeaker(partner)
		UI:SetSpeakerEmotion("Normal")
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_13_'..tostring(pTalkKind)]))
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_14_'..tostring(pTalkKind)]))
		
		GAME:WaitFrames(10)
		ExplorerEssentials.SetSpeakerHero()
		UI:SetSpeakerEmotion("Normal")
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Hero_4']))
		
		GAME:WaitFrames(10)
		UI:SetSpeaker(partner)
		UI:SetSpeakerEmotion("Happy")
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_15_'..tostring(pTalkKind)], partner:GetDisplayName()))
		UI:SetSpeakerEmotion("Normal")
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_16_'..tostring(pTalkKind)]))
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_17_'..tostring(pTalkKind)]))
		
		GAME:WaitFrames(15)
		CharacterActions.Explain(player)
		GAME:WaitFrames(30)
		
		SOUND:PlayBattleSE("EVT_Emote_Startled")
		CharacterActions.ScaredJump(partner, Direction.Left)
		
		GAME:WaitFrames(10)
		UI:SetSpeaker(partner)
		UI:SetSpeakerEmotion("Surprised")
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_18_'..tostring(pTalkKind)]))
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_19'], _DATA:GetMonster(player.CurrentForm.Species):GetColoredName()))
		
		GAME:WaitFrames(10)
		GROUND:CharAnimateTurnTo(player, Direction.Up, 4)
		GAME:WaitFrames(30)
		GROUND:CharAnimateTurnTo(player, Direction.Down, 4)
		GAME:WaitFrames(45)
		GROUND:CharAnimateTurnTo(player, Direction.Up, 4)
		GAME:WaitFrames(30)
		GROUND:CharAnimateTurnTo(player, Direction.Right, 4)
		GAME:WaitFrames(45)
		
		SOUND:PlayBattleSE("EVT_Emote_Shock")
		GROUND:CharSetEmote(player, "shock", 1)
		GAME:WaitFrames(30)
		
		ExplorerEssentials.SetSpeakerHero()
		UI:SetSpeakerEmotion("Surprised")
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Hero_5']))
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Hero_6'], _DATA:GetMonster(player.CurrentForm.Species):GetColoredName()))
		
		GAME:WaitFrames(15)
		UI:SetSpeakerEmotion("Worried")
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Hero_7']))
		
		GAME:WaitFrames(10)
		UI:SetSpeaker(partner)
		UI:SetSpeakerEmotion("Worried")
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_20']))
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_21']))
		
		SOUND:PlayBattleSE("EVT_Emote_Exclaim_Surprised")
		GROUND:CharSetEmote(player, "shock", 1)
		GAME:WaitFrames(30)
		CharacterActions.ShakeHead(player, Direction.Right)
		GAME:WaitFrames(30)
		
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_22']))
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_23_'..tostring(pTalkKind)]))
		
		ExplorerEssentials.SetSpeakerHero()
		UI:SetSpeakerEmotion("Normal")
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Hero_8']))
		
		GAME:WaitFrames(10)
		
		--name entry
		UI:ResetSpeaker()
		local ch = false
		local name = ""
		while not ch do
			name = ""
			while name == "" do
			UI:NameMenu(STRINGS:Format(STRINGS.MapStrings['Name_Prompt']), "")
			UI:WaitForChoice()
			name = UI:ChoiceResult()
			end
		
			GAME:SetCharacterNickname(GAME:GetPlayerPartyMember(0), name)
			GAME:SetCharacterNickname(SV.General.Starter, name) -- make sure nickname is saved
			UI:ChoiceMenuYesNo(STRINGS:Format(STRINGS.MapStrings['Name_Confirm'], player:GetDisplayName()), true)
			UI:WaitForChoice()
			ch = UI:ChoiceResult()
		end
		
		GAME:WaitFrames(10)
		UI:SetSpeaker(partner)
		UI:SetSpeakerEmotion("Worried")
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_24_'..tostring(pTalkKind)], player:GetDisplayName()))
		
		UI:SetSpeakerEmotion("Normal")
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_25']))
		
		GAME:WaitFrames(15)
		SOUND:PlayBattleSE("EVT_Emote_Sweating")
		GROUND:CharSetEmote(partner, "sweating", 1)
		
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_26']))
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_27']))
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_28_'..tostring(pTalkKind)]))
		
		--setup koffing, zubat, and relic fragment
		local koffing = CH('Koffing')
		local zubat = CH('Zubat')
		local relic = OBJ('RelicFragment')
		
		GROUND:TeleportTo(koffing, cam.Position.X, cam.Position.Y + 32, Direction.Left)
		GROUND:TeleportTo(zubat, cam.Position.X, cam.Position.Y, Direction.Left)
		
		local coro1 = TASK:BranchCoroutine(function() GAME:WaitFrames(5) --koffing
													GROUND:MoveInDirection(koffing, Direction.Left, 64, false, 2) end) 
		local coro2 = TASK:BranchCoroutine(function() GROUND:MoveInDirection(zubat, Direction.Left, 64, false, 2) --zubat
													GROUND:CharWaitAnim(zubat, "Attack")
													SOUND:PlayBattleSE("EVT_Tackle") end) 
		local coro3 = TASK:BranchCoroutine(function() GAME:WaitFrames(30) --player
													SOUND:PlayBattleSE("EVT_Emote_Exclaim")
													GROUND:CharSetEmote(player, "exclaim", 1) end)
		TASK:JoinCoroutines({coro1, coro2, coro3})
		
		local coro1 = TASK:BranchCoroutine(function() GROUND:AnimateInDirection(partner, "Hurt", Direction.Left, Direction.Left, 17, 1, 4) --partner
													GROUND:CharSetEmote(partner, "shock", 1)
													GROUND:CharSetAction(partner, RogueEssence.Ground.PoseGroundAction(partner.Position, partner.Direction, RogueEssence.Content.GraphicsManager.GetAnimIndex("Pain"))) end) 
		local coro2 = TASK:BranchCoroutine(function() GAME:WaitFrames(15) --player
													GROUND:AnimateInDirection(player, "Walk", Direction.Right, Direction.Left, 8, 1, 4) end) 
		local coro3 = TASK:BranchCoroutine(function() GROUND:TeleportTo(relic, partner.Position.X, partner.Position.Y, Direction.Down) --relic fragment
													GROUND:MoveObjectToPosition(relic, koffing.Position.X - 48, koffing.Position.Y - 8, 4) end)
		local coro4 = TASK:BranchCoroutine(function() UI:SetSpeakerEmotion("Shouting") --dialogue
													UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_29_'..tostring(pTalkKind)])) end)
		TASK:JoinCoroutines({coro1, coro2, coro3, coro4})
		
		GAME:WaitFrames(10)
		UI:SetSpeaker(koffing)
		UI:SetSpeakerEmotion("Normal")
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Koffing_1']))
		
		GAME:WaitFrames(10)
		GROUND:CharAnimateTurnTo(partner, Direction.Right, 1)
		SOUND:PlayBattleSE("EVT_Emote_Complain_2")
		GROUND:CharSetEmote(partner, "angry", -1)
		GROUND:CharSetAnim(partner, "None", false)
		
		UI:SetSpeaker(partner)
		UI:SetSpeakerEmotion("Angry")
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_30']))
		
		GAME:WaitFrames(10)
		UI:SetSpeaker(zubat)
		UI:SetSpeakerEmotion("Normal")
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Zubat_1']))
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Zubat_2']))
		
		GROUND:CharSetEmote(partner, "none", 1)
		CharacterActions.ScaredJump(partner, Direction.Right)
		
		UI:SetSpeaker(partner)
		UI:SetSpeakerEmotion("Surprised")
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_31']))
		
		GAME:WaitFrames(10)
		GROUND:CharAnimateTurnTo(zubat, Direction.DownLeft, 4)
		UI:SetSpeaker(zubat)
		UI:SetSpeakerEmotion("Normal")
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Zubat_3']))
		
		local coro1 = TASK:BranchCoroutine(function() GAME:WaitFrames(5) --player
													GROUND:CharAnimateTurnTo(player, Direction.DownRight, 4) end) 
		local coro2 = TASK:BranchCoroutine(function() GROUND:CharAnimateTurnTo(partner, Direction.DownRight, 4) --partner
													SOUND:PlayBattleSE("EVT_Emote_Exclaim")
													GROUND:CharSetEmote(partner, "exclaim", 1)
													GAME:WaitFrames(30) end) 
		TASK:JoinCoroutines({coro1, coro2})
		
		UI:SetSpeaker(partner)
		UI:SetSpeakerEmotion("Surprised")
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_32_'..tostring(pTalkKind)]))
		
		GAME:WaitFrames(10)
		UI:SetSpeaker(zubat)
		UI:SetSpeakerEmotion("Normal")
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Zubat_4']))
		
		local origX = zubat.Position.X
		local origY = zubat.Position.Y
		
		GAME:WaitFrames(15)
		GROUND:MoveToPosition(zubat, relic.Position.X, relic.Position.Y + 1, false, 1)
		GAME:WaitFrames(15)
		GROUND:Hide("RelicFragment")
		
		local coro1 = TASK:BranchCoroutine(function() GROUND:AnimateToPosition(zubat, "Walk", Direction.DownLeft, origX, origY, 1, 1, 0) --zubat
													GROUND:CharAnimateTurnTo(zubat, Direction.Left, 4)
													GROUND:CharAnimateTurnTo(player, Direction.Right, 4)
													GROUND:CharAnimateTurnTo(partner, Direction.Right, 4) end) 
		local coro2 = TASK:BranchCoroutine(function() SOUND:PlayBattleSE("EVT_Emote_Shock")
													GROUND:CharSetEmote(partner, "shock", 1)
													UI:SetSpeaker(partner)
													UI:SetSpeakerEmotion("Surprised")
													UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_33'])) end) 
		TASK:JoinCoroutines({coro1, coro2})
		
		GAME:WaitFrames(10)
		UI:SetSpeaker(koffing)
		UI:SetSpeakerEmotion("Normal")
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Koffing_2']))
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Koffing_3']))
		
		local coro1 = TASK:BranchCoroutine(function() GROUND:CharTurnToCharAnimated(zubat, koffing, 8, true) end) 
		local coro2 = TASK:BranchCoroutine(function() GROUND:CharTurnToCharAnimated(koffing, zubat, 8, true) end) 
		TASK:JoinCoroutines({coro1, coro2})
		
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Koffing_4']))
		
		local coro1 = TASK:BranchCoroutine(function() GROUND:CharAnimateTurnTo(zubat, Direction.Left, 4) end) 
		local coro2 = TASK:BranchCoroutine(function() GROUND:CharAnimateTurnTo(koffing, Direction.Left, 4) end) 
		TASK:JoinCoroutines({coro1, coro2})
		
		GAME:WaitFrames(10)
		UI:SetSpeaker(zubat)
		UI:SetSpeakerEmotion("Normal")
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Zubat_5']))
		
		local posx = 0
		local posy = 0	
		
		local coro1 = TASK:BranchCoroutine(function() posx = koffing.Position.X - 16 --koffing
													posy = koffing.Position.Y + 16
													GROUND:MoveToPosition(koffing, posx, posy, false, 1) 
													GROUND:MoveToPosition(koffing, koffing.Position.X - 240, koffing.Position.Y, false, 1)
													GROUND:Hide("Koffing") end) 
		local coro2 = TASK:BranchCoroutine(function() GAME:WaitFrames(30)
													posx = zubat.Position.X - 48 --zubat
													posy = zubat.Position.Y + 48
													GROUND:MoveToPosition(zubat, posx, posy, false, 1) 
													GROUND:MoveToPosition(zubat, zubat.Position.X - 240, zubat.Position.Y, false, 1)
													GROUND:Hide("Zubat")
													continue = true end)
		local coro3 = TASK:BranchCoroutine(function() GAME:WaitFrames(40) --player turn to people leaving
													GROUND:CharAnimateTurnTo(player, Direction.DownLeft, 60) end) 
		local coro4 = TASK:BranchCoroutine(function() GAME:WaitFrames(30) --partner turn to people leaving
													GROUND:CharAnimateTurnTo(partner, Direction.DownLeft, 60) end) 
		TASK:JoinCoroutines({coro1, coro2, coro3, coro4})
		
		GAME:WaitFrames(60)
		
		UI:SetSpeaker(partner)
		UI:SetSpeakerEmotion("Sad")
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_34']))
		
		GROUND:CharAnimateTurnTo(partner, Direction.Left, 4)
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_35']))
		
		GROUND:CharAnimateTurnTo(player, Direction.Right, 4)
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_36']))
		
		UI:SetSpeakerEmotion("Teary-Eyed")
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_37']))
		
		CharacterActions.ShakeHead(partner, Direction.Left)
		GAME:WaitFrames(30)
		
		UI:SetSpeakerEmotion("Determined")
		UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_38']))
		
		--begin dialogue choices
		local continue = false
		local choices = {STRINGS:Format(STRINGS.MapStrings['CH1_S1_Option_1']),
			STRINGS:Format(STRINGS.MapStrings['CH1_S1_Option_2']),
			STRINGS:Format(STRINGS.MapStrings['CH1_S1_Option_3'])}
		
		UI:BeginChoiceMenu(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_39_'..tostring(pTalkKind)]), choices, 1, 3)
		UI:WaitForChoice()
		local result = UI:ChoiceResult()
		
		while not continue do
			--A
			if result == 1 then --yes
				continue = true
				
				CharacterActions.HopTwice(partner, Direction.Left)
				
				UI:SetSpeakerEmotion("Inspired")
				UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_40A']))
				UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_41A_'..tostring(pTalkKind)]))
				
				--leave for dungeon
				local coro1 = TASK:BranchCoroutine(function() posx = partner.Position.X - 48 --partner
													posy = partner.Position.Y + 48
													GROUND:MoveToPosition(partner, posx, posy, false, 1) 
													GROUND:MoveToPosition(partner, partner.Position.X - 140, partner.Position.Y, false, 1)
													GROUND:Hide("PARTNER") end) 
				local coro2 = TASK:BranchCoroutine(function() GAME:WaitFrames(60)
													posx = player.Position.X - 48 --player
													posy = player.Position.Y + 48
													GROUND:MoveToPosition(player, posx, posy, false, 1) 
													GROUND:MoveToPosition(player, player.Position.X - 140, player.Position.Y, false, 1)
													GROUND:Hide("PLAYER") end)
				TASK:JoinCoroutines({coro1, coro2})
				
			--B
			elseif result == 2 then --no
			
				CharacterActions.ScaredJump(partner, Direction.Left)
				
				UI:SetSpeakerEmotion("Surprised")
				UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_40B_'..tostring(pTalkKind)]))
				UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_41B_'..tostring(pTalkKind)]))
				UI:SetSpeakerEmotion("Teary-Eyed")
				UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_42B']))
				
				CharacterActions.HopTwice(partner, Direction.Left)
				
				--back to choices
				UI:BeginChoiceMenu(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_43B_'..tostring(pTalkKind)]), choices, 1, 3)
				UI:WaitForChoice()
				result = UI:ChoiceResult()
				
			else --other
			
				--new choice menu
				choices = {STRINGS:Format(STRINGS.MapStrings['CH1_S1_Option_4']),
				STRINGS:Format(STRINGS.MapStrings['CH1_S1_Option_5'])}
				
				UI:SetSpeakerEmotion("Worried")
				UI:BeginChoiceMenu(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_44B_'..tostring(pTalkKind)]), choices, 1, 2)
				UI:WaitForChoice()
				result = UI:ChoiceResult() --1 should never be checked for as choice 1 is ALWAYS yes
				
				if result == 2 then
					
					SOUND:PlayBattleSE("EVT_Emote_Sweating")
					GROUND:CharSetEmote(partner, "sweating", 1)
					
					UI:SetSpeakerEmotion("Worried")
					UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_45B']))
					
					GROUND:CharSetDrawEffect(partner, DrawEffect.Shaking)
					
					UI:SetSpeakerEmotion("Teary-Eyed")
					UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_46B']))
					
					GROUND:CharEndDrawEffect(partner, DrawEffect.Shaking)
					
					CharacterActions.HopTwice(partner, Direction.Left)
					
					--new choice menu
					choices = {STRINGS:Format(STRINGS.MapStrings['CH1_S1_Option_4']),
					STRINGS:Format(STRINGS.MapStrings['CH1_S1_Option_6'])}
				
					UI:BeginChoiceMenu(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_47B_'..tostring(pTalkKind)]), choices, 1, 2)
					UI:WaitForChoice()
					result = UI:ChoiceResult() --1 should never be checked for as choice 1 is ALWAYS yes
				
					if result == 2 then
						
						UI:SetSpeakerEmotion("Worried")
						UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_48B']))
						
						--new choice menu
						choices = {STRINGS:Format(STRINGS.MapStrings['CH1_S1_Option_4']),
						STRINGS:Format(STRINGS.MapStrings['CH1_S1_Option_7'])}
				
						UI:BeginChoiceMenu(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_49B']), choices, 1, 2)
						UI:WaitForChoice()
						result = UI:ChoiceResult() --1 should never be checked for as choice 1 is ALWAYS yes
				
						if result == 2 then
							
							SOUND:PlayBattleSE("EVT_Emote_Complain_2")
							GROUND:CharSetEmote(partner, "angry", -1)
							CharacterActions.HopTwice(partner, Direction.Left)
							
							--new choice menu
							choices = {STRINGS:Format(STRINGS.MapStrings['CH1_S1_Option_4']),
							STRINGS:Format(STRINGS.MapStrings['CH1_S1_Option_8'])}
				
							UI:SetSpeakerEmotion("Angry")
							UI:BeginChoiceMenu(STRINGS:Format(STRINGS.MapStrings['CH1_S1_Partner_50B']), choices, 1, 2)
							UI:WaitForChoice()
							
							--getting result doesn't matter here as both options force you into yes
							GROUND:CharSetEmote(partner, "none", 1)
							result = 1
							
						end
						
					end
					
				end
			
			end
		end
		
		local coro1 = TASK:BranchCoroutine(function() GAME:FadeOut(false, 60) end) 
		local coro2 = TASK:BranchCoroutine(function() SOUND:FadeOutSE("Ambient/AMB_Ocean", 60) end)
		TASK:JoinCoroutines({coro1, coro2})
		
		--enter dungeon
		GAME:WaitFrames(60)
		GAME:CutsceneMode(false)
		stopBubbles = true -- ALWAYS NEEDS TO BE CALLED BEFORE GROUND MAP CHANGE OR ELSE YOU'RE SOFTLOCKED
		GAME:EnterDungeon('beach_cave', 0, 0, 0, RogueEssence.Data.GameProgress.DungeonStakes.Risk, true, false)

		end)
		TASK:JoinCoroutines({main, bubbles})

	end
	
end

function dusk_beach.CH1_ExplorerTeamInvite()
	local player = CH('PLAYER')
	local partner = CH('PARTNER')
	
  	AI:DisableCharacterAI(partner)
	partner.CollisionDisabled = true
	
	local hTalkKind = SV.Personality.HeroTalkKind
	local pTalkKind = SV.Personality.PartnerTalkKind
	
	local marker = MRKR("C1S2_CamPos_1")
	GROUND:TeleportTo(partner, marker.Position.X, marker.Position.Y, Direction.Right)
    GAME:MoveCamera(marker.Position.X + 29, marker.Position.Y, 1, false)
	local marker = MRKR("C1S2_CamPos_2")
	GROUND:TeleportTo(player, marker.Position.X, marker.Position.Y, Direction.Left)
	GAME:FadeIn(20)
	SOUND:LoopSE("Ambient/AMB_Ocean")
	UI:SetSpeaker(partner)
	UI:SetSpeakerEmotion("Happy")
	CharacterActions.HopTwice(partner, Direction.Right)
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_1_'..tostring(pTalkKind)]))
	ExplorerEssentials.SetSpeakerHero()
	UI:SetSpeakerEmotion("Worried")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Hero_1']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Hero_2']))
	UI:SetSpeakerEmotion("Happy")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Hero_3']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Hero_4']))

	GROUND:MoveInDirection(partner, Direction.Right, 16, false, 1)
    SOUND:PlayBattleSE("EVT_CH02_Item_Place")
    GROUND:TeleportTo(OBJ("RelicFragment"), partner.Position.X + 9, partner.Position.Y, Direction.Right, -1)
    GAME:WaitFrames(15)
	GROUND:AnimateInDirection(partner, "Walk", Direction.Right, Direction.Left, 16, 1, 1)
    GAME:WaitFrames(30)	

	UI:SetSpeaker(partner)
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_2']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_3']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_4']))

	SOUND:PlayBGM("BGM_Beach.ogg", true)
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_5']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_6']), {function() CharacterActions.HopOnce(partner, Direction.Right) end})
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_7']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_8']))
	GROUND:CharAnimateTurn(partner, Direction.Up, 4, true)
	UI:SetSpeakerEmotion("Inspired")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_9']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_10']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_11_'..tostring(pTalkKind)]))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_12_'..tostring(pTalkKind)]), {function() CharacterActions.HopOnce(partner, Direction.Up) end})
	GROUND:CharAnimateTurn(partner, Direction.Right, 4, true)
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_13_'..tostring(pTalkKind)]))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_14_'..tostring(pTalkKind)]))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_15_'..tostring(pTalkKind)]))
	GROUND:MoveInDirection(partner, Direction.Right, 8, false, 1)
	GROUND:MoveInDirection(player, Direction.Left, 8, false, 1)

	GAME:FadeOut(false, 30)
    GAME:WaitFrames(10)
	UI:WaitShowBG("RelicFragmentCloseup", 1, 30)
	GAME:WaitFrames(30)

	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_16_'..tostring(pTalkKind)]))
	
	ExplorerEssentials.SetSpeakerHero()
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Hero_5']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Hero_6']))
	
	UI:SetSpeaker(partner)
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_17_'..tostring(pTalkKind)]))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_18']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_19']))

	GAME:WaitFrames(10)
	UI:WaitHideBG(30)
	GAME:FadeIn(30)
    GAME:WaitFrames(30)

	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_20']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_21']), {function() CharacterActions.HopOnce(partner, Direction.Right) end})
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_22']), {function() CharacterActions.HopOnce(partner, Direction.Right) end})
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_23']))
	UI:SetSpeakerEmotion("Sad")
	GROUND:CharAnimateTurnTo(partner, Direction.Down, 4)
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_24_'..tostring(pTalkKind)]))
	GAME:WaitFrames(40)
	UI:SetSpeakerEmotion("Worried")
	GROUND:CharAnimateTurnTo(partner, Direction.Right, 2)
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_25'], player:GetDisplayName()))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_26']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_27_'..tostring(pTalkKind)]))
	
	ExplorerEssentials.SetSpeakerHero()
	UI:SetSpeakerEmotion("Worried")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Hero_7']))
	
	UI:SetSpeaker(partner)
	UI:SetSpeakerEmotion("Sad")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_28']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_29_'..tostring(pTalkKind)]))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_30_'..tostring(pTalkKind)], player:GetDisplayName()))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_31_'..tostring(pTalkKind)]), {function() CharacterActions.HopOnce(partner, Direction.Right) end})
	
	ExplorerEssentials.SetSpeakerHero()
	UI:SetSpeakerEmotion("Surprised")
	SOUND:PlayBattleSE("EVT_Emote_Sweating")
	GROUND:CharSetEmote(player, "sweating", 1)
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Hero_8_'..tostring(hTalkKind)]))
	UI:SetSpeakerEmotion("Worried")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Hero_9']))
	
	--begin dialogue choices
	local continue = false
	local choices = {STRINGS:Format(STRINGS.MapStrings['CH1_S3_Option_1']),
           STRINGS:Format(STRINGS.MapStrings['CH1_S3_Option_2']),
           STRINGS:Format(STRINGS.MapStrings['CH1_S3_Option_3'])}
	
	UI:BeginChoiceMenu(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Hero_10']), choices, 1, 3)
	UI:WaitForChoice()
	result = UI:ChoiceResult()
	
	while not continue do
		--A
		if result == 1 then --yes
			continue = true

			ExplorerEssentials.SetSpeakerHero()
			UI:SetSpeakerEmotion("Worried")			
			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Hero_11A']))
			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Hero_12A']))
			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Hero_13A'], partner:GetDisplayName()))
			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Hero_14A']))
			UI:SetSpeakerEmotion("Normal")
			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Hero_15A']))

			GAME:WaitFrames(10)
			CharacterActions.Explain(player)
			GAME:WaitFrames(20)
			
			UI:SetSpeaker(partner)
			SOUND:PlayBattleSE("EVT_Emote_Exclaim")
			GROUND:CharSetEmote(partner, "exclaim", 1)
			
			GAME:WaitFrames(20)
			UI:SetSpeakerEmotion("Inspired")
			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_32A_'..tostring(pTalkKind)]))
			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_33A_'..tostring(pTalkKind)]))
			UI:SetSpeakerEmotion("Joyous")
			CharacterActions.HopTwice(partner, Direction.Right)
			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_34A_'..tostring(pTalkKind)]))
			UI:SetSpeakerEmotion("Normal")
			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_35A_'..tostring(pTalkKind)]))

			GROUND:CharAnimateTurnTo(partner, Direction.UpRight, 4)
			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_36A_'..tostring(pTalkKind)], CH('Wigglytuff'):GetDisplayName())) --uses a dummy character since wigglytuff isn't in this scene
			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_37A_'..tostring(pTalkKind)]))
			GROUND:CharAnimateTurnTo(partner, Direction.Right, 4)

			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_38A_'..tostring(pTalkKind)]))
			CharacterActions.HopOnce(partner, Direction.Right)
			UI:SetSpeakerEmotion("Happy")
			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_39A_'..tostring(pTalkKind)], player:GetDisplayName()))

			local coro1 = TASK:BranchCoroutine(function() GROUND:CharAnimateTurnTo(partner, Direction.Down, 2) end)
			local coro2 = TASK:BranchCoroutine(function() GROUND:CharAnimateTurnTo(player, Direction.Down, 2) end)
			TASK:JoinCoroutines({coro1, coro2})
			
			GAME:WaitFrames(20)

			--pose
			local coro1 = TASK:BranchCoroutine(function() GROUND:CharSetAction(player, RogueEssence.Ground.PoseGroundAction(player.Position, player.Direction, RogueEssence.Content.GraphicsManager.GetAnimIndex("Pose"))) end) 
			local coro2 = TASK:BranchCoroutine(function() GROUND:CharSetAction(partner, RogueEssence.Ground.PoseGroundAction(partner.Position, partner.Direction, RogueEssence.Content.GraphicsManager.GetAnimIndex("Pose"))) end)
			TASK:JoinCoroutines({coro1, coro2})

			GAME:WaitFrames(120)
		--B
		elseif result == 2 then --no

			SOUND:PlayBattleSE("EVT_Emote_Startled")
			CharacterActions.ScaredJump(partner, Direction.Right)
		
			UI:SetSpeaker(partner)
			UI:SetSpeakerEmotion("Surprised")
			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_32B_'..tostring(pTalkKind)]))

			UI:SetSpeakerEmotion("Sad")
			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_33B'], player:GetDisplayName()))
			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_34B_'..tostring(pTalkKind)], CH('Koffing'):GetDisplayName()))
			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_35B'], player:GetDisplayName()))
			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_36B_'..tostring(pTalkKind)], player:GetDisplayName()))
			
			--back to choices
			UI:BeginChoiceMenu(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_37B_'..tostring(pTalkKind)]), choices, 1, 3)
			UI:WaitForChoice()
			result = UI:ChoiceResult()
			
		else --other

			SOUND:PlayBattleSE("EVT_Emote_Confused")
			GROUND:CharSetEmote(partner, "question", 1)
			GAME:WaitFrames(30)
		
			UI:SetSpeaker(partner)
			UI:SetSpeakerEmotion("Normal")
			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_38B']))
		
			--new choice menu
			choices = {STRINGS:Format(STRINGS.MapStrings['CH1_S3_Option_4'])}
			
			UI:BeginChoiceMenu(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_39B']), choices, 1, 1)
			UI:WaitForChoice()
			--there's only one option here so we don't need to check the result
			
			SOUND:PlayBattleSE("EVT_Emote_Startled")
			CharacterActions.ScaredJump(partner, Direction.Right)

			UI:SetSpeakerEmotion("Surprised")
			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_40B']))
			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_41B_'..tostring(pTalkKind)]))

			UI:SetSpeakerEmotion("Sad")
			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_42B']))
			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_43B'], player:GetDisplayName()))

			UI:SetSpeakerEmotion("Normal")
			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_44B'], CH('Koffing'):GetDisplayName()))
			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_45B']))
			UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_46B'], player:GetDisplayName()))
			
			--new choice menu
			choices = {STRINGS:Format(STRINGS.MapStrings['CH1_S3_Option_1']),
            STRINGS:Format(STRINGS.MapStrings['CH1_S3_Option_2'])} --eliminates option 3 since we already went through that dialogue
			
			UI:BeginChoiceMenu(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Partner_47B']), choices, 1, 2)
			UI:WaitForChoice()
			result = UI:ChoiceResult()
		
		end
	end
	
	--narration
	UI:SetAutoFinish(true)

	local coro1 = TASK:BranchCoroutine(function() GAME:FadeOut(false, 120) end) 
	local coro2 = TASK:BranchCoroutine(function() SOUND:FadeOutSE("Ambient/AMB_Ocean", 120) end)
	local coro3 = TASK:BranchCoroutine(function() SOUND:FadeOutBGM(120) end)
	TASK:JoinCoroutines({coro1, coro2, coro3})
	
	UI:WaitShowVoiceOver(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Narration_1']), -1)
	UI:WaitShowVoiceOver(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Narration_2'], player:GetDisplayName(), partner:GetDisplayName()), -1)
	UI:WaitShowVoiceOver(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Narration_3']), -1)
	UI:WaitShowVoiceOver(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Narration_4']), -1)
	UI:WaitShowVoiceOver(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Narration_5']), -1)
	UI:WaitShowVoiceOver(STRINGS:Format(STRINGS.MapStrings['CH1_S3_Narration_6']), -1)
	--chapter 2 start
	SV.Progression.Chapter = 2
	SV.Progression.SectionFlag = 0 -- reset flags
	GAME:WaitFrames(120)
	UI:SetAutoFinish(false)
	GAME:EnterGroundMap("title_catch", "Entrance")
end

function dusk_beach.CH1_FailedBeachCave()

	local player = CH('PLAYER')
	local partner = CH('PARTNER')
	
  	AI:DisableCharacterAI(partner)
	partner.CollisionDisabled = true
	
	local hTalkKind = SV.Personality.HeroTalkKind
	local pTalkKind = SV.Personality.PartnerTalkKind

	-- hotswap the fade effect for a background so we can fade out front
	local coro1 = TASK:BranchCoroutine(function() UI:WaitShowBG("Black", 1, 1) end)
	local coro2 = TASK:BranchCoroutine(function() GAME:FadeIn(1) end)
	TASK:JoinCoroutines({coro1, coro2})

	UI:SetSpeaker(partner)
	UI:SetSpeakerEmotion("Pain")

	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S2_Partner_1']))
	
	UI:SetAutoFinish(true)
	local coro1 = TASK:BranchCoroutine(function() UI:WaitShowTimedDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S2_Partner_1']), 120) end)
	local coro2 = TASK:BranchCoroutine(function() GAME:FadeOutFront(false, 120) end)
	TASK:JoinCoroutines({coro1, coro2})
	
	-- switch it back
	UI:SetAutoFinish(false)
	UI:WaitHideBG(1)
	
	local marker = MRKR("C1S1_PlayerSpawn")
	
	GROUND:TeleportTo(player, marker.Position.X + 20, marker.Position.Y + 32, Direction.Down)
	GROUND:TeleportTo(partner, marker.Position.X - 40, marker.Position.Y + 32, Direction.Down)
	GAME:MoveCamera(partner.Position.X + 30, partner.Position.Y, 1, false)
	GAME:WaitFrames(60)
	
	GROUND:CharSetAnim(player, "Laying", true)
	GROUND:CharSetAnim(partner, "Laying", true)
	
	local coro1 = TASK:BranchCoroutine(function() SOUND:FadeInSE("Ambient/AMB_Ocean", 60) end)
	local coro2 = TASK:BranchCoroutine(function() GAME:FadeInFront(60) end)
	TASK:JoinCoroutines({coro1, coro2})
	
	GAME:WaitFrames(15)
	
	local coro1 = TASK:BranchCoroutine(function() GROUND:CharSetDrawEffect(partner, DrawEffect.Shaking) --partner
												GAME:WaitFrames(30)
												GROUND:CharEndDrawEffect(partner, DrawEffect.Shaking)
												GROUND:CharWaitAnim(partner, "Wake")
												GAME:WaitFrames(30)
												GROUND:CharAnimateTurnTo(partner, Direction.Down, 4) 
												CharacterActions.LookAround(partner) end) 
	local coro2 = TASK:BranchCoroutine(function() GAME:WaitFrames(15) --player
												GROUND:CharSetDrawEffect(player, DrawEffect.Shaking) 
												GAME:WaitFrames(30)
												GROUND:CharEndDrawEffect(player, DrawEffect.Shaking)
												GROUND:CharWaitAnim(player, "Wake")
												GAME:WaitFrames(30)
												GROUND:CharAnimateTurnTo(player, Direction.Down, 4) 
												CharacterActions.LookAround(player) end)
	TASK:JoinCoroutines({coro1, coro2})
	
	GAME:WaitFrames(30)
	
	SOUND:PlayBattleSE("EVT_Emote_Sweating")
	GROUND:CharSetEmote(partner, "sweating", 1)
	
	GROUND:CharAnimateTurnTo(partner, Direction.Right, 4)
	GROUND:CharAnimateTurnTo(player, Direction.Left, 4)
	
	GAME:WaitFrames(30)
	
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S2_Partner_2_'..tostring(pTalkKind)]))
	
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S2_Partner_3']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S2_Partner_4']))
	
	SOUND:PlayBattleSE("EVT_Emote_Exclaim")
	GROUND:CharSetEmote(partner, "exclaim", 1)
	GAME:WaitFrames(30)
	
	UI:SetSpeakerEmotion("Surprised")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S2_Partner_5_'..tostring(pTalkKind)]))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S2_Partner_6_'..tostring(pTalkKind)], CH('Koffing'):GetDisplayName()))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_S2_Partner_7_'..tostring(pTalkKind)], player:GetDisplayName()))
	
	local coro1 = TASK:BranchCoroutine(function() posx = partner.Position.X - 16 --partner
												posy = partner.Position.Y + 16
												GROUND:MoveToPosition(partner, posx, posy, false, 1) 
												GROUND:MoveToPosition(partner, partner.Position.X - 200, partner.Position.Y, false, 1)
												GROUND:Hide("PARTNER") end) 
	local coro2 = TASK:BranchCoroutine(function() GAME:WaitFrames(10)
												posx = player.Position.X - 16 --player
												posy = player.Position.Y + 16
												GROUND:MoveToPosition(player, posx, posy, false, 1) 
												GROUND:MoveToPosition(player, player.Position.X - 200, player.Position.Y, false, 1)
												GROUND:Hide("PLAYER") end)
	TASK:JoinCoroutines({coro1, coro2})
	
	local coro1 = TASK:BranchCoroutine(function() GAME:FadeOut(false, 60) end) 
	local coro2 = TASK:BranchCoroutine(function() SOUND:FadeOutSE("Ambient/AMB_Ocean", 60) end)
	TASK:JoinCoroutines({coro1, coro2})
	
	--enter dungeon
	GAME:WaitFrames(60)
	GAME:CutsceneMode(false)
	GAME:EnterDungeon('beach_cave', 0, 0, 0, RogueEssence.Data.GameProgress.DungeonStakes.Risk, true, false)
end

function dusk_beach.CH16_BackInThePast()
	local hTalkKind = SV.Personality.HeroTalkKind
	local pTalkKind = SV.Personality.PartnerTalkKind
	SOUND:StopBGM()
	-- TODO: back_SetBanner2(407, 0, 152, 120, 16, { english="A New Dawn",     })
	GAME:FadeIn(45)
	GAME:WaitFrames(160)
	GAME:FadeOut(false, 45)
	GAME:WaitFrames(15)
	-- TODO: $SCENARIO_MAIN = scn[21, 1]
	-- ### back2_SetMode(4) [IRRELEVANT]
	-- ### back2_SetGround(LEVEL_V01P03A) [IRRELEVANT]
	-- back_SetGround(LEVEL_D01P11A) (ground mapping may be converted manually)
	-- ### supervision_Acting(0) [IRRELEVANT]
	-- ### camera2_SetPositionMark(Position<'m0', 33, 9.5>) [IRRELEVANT]
	GAME:MoveCamera(MRKR('PERF_0').Position.X, MRKR('PERF_0').Position.Y, 1, false)
	--GROUND:CharSetAnim(CH('PLAYER'), "UNK_76", false)
	--GROUND:CharSetAnim(CH('PARTNER'), "UNK_76", false)
	--GROUND:CharSetAnim(CH('Grovyle'), "UNK_29", false)
	SOUND:FadeInSE("Ambient/AMB_Ocean.ogg", 90)
	-- ### screen2_FadeIn(0, 60) [IRRELEVANT]
	GAME:FadeIn(60)
	GAME:WaitFrames(120)
	GROUND:AnimateToPosition(CH('PLAYER'), "None", CH('PLAYER').Direction, CH('PLAYER').Position.X + 1, CH('PLAYER').Position.Y + 0, 1, 1, 0) -- Replace with GROUND:CharSetDrawEffect(ch, DrawEffect.Shaking) if this is a shaking animation
	GAME:WaitFrames(2)
	GROUND:AnimateToPosition(CH('PLAYER'), "None", CH('PLAYER').Direction, CH('PLAYER').Position.X + -1, CH('PLAYER').Position.Y + 0, 1, 1, 0) -- Replace with GROUND:CharSetDrawEffect(ch, DrawEffect.Shaking) if this is a shaking animation
	GAME:WaitFrames(30)
	GROUND:AnimateToPosition(CH('PLAYER'), "None", CH('PLAYER').Direction, CH('PLAYER').Position.X + 1, CH('PLAYER').Position.Y + 0, 1, 1, 0) -- Replace with GROUND:CharSetDrawEffect(ch, DrawEffect.Shaking) if this is a shaking animation
	GAME:WaitFrames(2)
	GROUND:AnimateToPosition(CH('PLAYER'), "None", CH('PLAYER').Direction, CH('PLAYER').Position.X + -1, CH('PLAYER').Position.Y + 0, 1, 1, 0) -- Replace with GROUND:CharSetDrawEffect(ch, DrawEffect.Shaking) if this is a shaking animation
	GAME:WaitFrames(2)
	GROUND:AnimateToPosition(CH('PLAYER'), "None", CH('PLAYER').Direction, CH('PLAYER').Position.X + 1, CH('PLAYER').Position.Y + 0, 1, 1, 0) -- Replace with GROUND:CharSetDrawEffect(ch, DrawEffect.Shaking) if this is a shaking animation
	GAME:WaitFrames(2)
	GROUND:AnimateToPosition(CH('PLAYER'), "None", CH('PLAYER').Direction, CH('PLAYER').Position.X + -1, CH('PLAYER').Position.Y + 0, 1, 1, 0) -- Replace with GROUND:CharSetDrawEffect(ch, DrawEffect.Shaking) if this is a shaking animation
	GAME:WaitFrames(30)
	--GROUND:CharWaitAnim(CH('PLAYER'), "UNK_63")
	GAME:WaitFrames(60)
	GROUND:CharSetAnim(CH('PLAYER'), "None", false)
	GROUND:CharAnimateTurnTo(CH('PLAYER'), Dir8.Down, 8)
	ExplorerEssentials.SetSpeakerHero()
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_PLAYER_1']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_PLAYER_2']))
	CharacterActions.LookAround(CH('PLAYER'))
	GAME:WaitFrames(30)
	GROUND:AnimateToPosition(CH('PARTNER'), "None", CH('PARTNER').Direction, CH('PARTNER').Position.X + 1, CH('PARTNER').Position.Y + 0, 1, 1, 0) -- Replace with GROUND:CharSetDrawEffect(ch, DrawEffect.Shaking) if this is a shaking animation
	GAME:WaitFrames(2)
	GROUND:AnimateToPosition(CH('PARTNER'), "None", CH('PARTNER').Direction, CH('PARTNER').Position.X + -1, CH('PARTNER').Position.Y + 0, 1, 1, 0) -- Replace with GROUND:CharSetDrawEffect(ch, DrawEffect.Shaking) if this is a shaking animation
	GAME:WaitFrames(2)
	GROUND:AnimateToPosition(CH('PARTNER'), "None", CH('PARTNER').Direction, CH('PARTNER').Position.X + 1, CH('PARTNER').Position.Y + 0, 1, 1, 0) -- Replace with GROUND:CharSetDrawEffect(ch, DrawEffect.Shaking) if this is a shaking animation
	GAME:WaitFrames(2)
	GROUND:AnimateToPosition(CH('PARTNER'), "None", CH('PARTNER').Direction, CH('PARTNER').Position.X + -1, CH('PARTNER').Position.Y + 0, 1, 1, 0) -- Replace with GROUND:CharSetDrawEffect(ch, DrawEffect.Shaking) if this is a shaking animation
	UI:SetSpeaker(CH('PARTNER'))
	UI:SetSpeakerEmotion("Pain")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_PARTNER_1']))
	GROUND:CharTurnToCharAnimated(CH('PLAYER'), CH('PARTNER'), 4)
	--GROUND:CharWaitAnim(CH('PARTNER'), "UNK_63")
	GAME:WaitFrames(60)
	GROUND:CharSetAnim(CH('PARTNER'), "None", false)
	GROUND:CharAnimateTurnTo(CH('PARTNER'), Dir8.Down, 4)
	GAME:WaitFrames(15)
	CharacterActions.LookAround(CH('PARTNER'))
	GAME:WaitFrames(30)
	GROUND:CharTurnToCharAnimated(CH('PARTNER'), CH('PLAYER'), 4)
	UI:SetSpeaker(CH('PARTNER'))
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_PARTNER_2_'..tostring(pTalkKind)]))
		-- TODO: ExecuteCommon: ExecuteCommon(CORO_LOOK_AROUND_LEFT_FUNC_SERIES, 0)
	GAME:WaitFrames(20)
	GROUND:CharTurnToCharAnimated(CH('PARTNER'), CH('PLAYER'), 4)
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_PARTNER_3']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_PARTNER_4']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_PARTNER_5']))
	SOUND:PlayBattleSE("EVT_Emote_Complain_2")
	CharacterActions.HopTwice(CH('PARTNER'), CH('PARTNER').Direction)
	UI:SetSpeaker(CH('PARTNER'))
	UI:SetSpeakerEmotion("Surprised")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_PARTNER_6']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_PARTNER_7']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_PARTNER_8_'..tostring(pTalkKind)]))
	CharacterActions.HopOnce(CH('PARTNER'), CH('PARTNER').Direction)
	--GROUND:CharSetEmote(CH('PLAYER'), "UNK_EFFECT_LAUGHING", 1)
	--GROUND:CharSetEmote(CH('PARTNER'), "UNK_EFFECT_LAUGHING", 1)
	UI:SetSpeaker(CH('PARTNER'))
	UI:SetSpeakerEmotion("Joyous")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_PARTNER_9_'..tostring(pTalkKind)]))
	GAME:WaitFrames(45)
	GROUND:CharSetEmote(CH('PLAYER'), "none", 1)
	GROUND:CharSetEmote(CH('PARTNER'), "none", 1)
	GROUND:AnimateToPosition(CH('Grovyle'), "None", CH('Grovyle').Direction, CH('Grovyle').Position.X + 1, CH('Grovyle').Position.Y + 0, 1, 1, 0) -- Replace with GROUND:CharSetDrawEffect(ch, DrawEffect.Shaking) if this is a shaking animation
	GAME:WaitFrames(2)
	GROUND:AnimateToPosition(CH('Grovyle'), "None", CH('Grovyle').Direction, CH('Grovyle').Position.X + -1, CH('Grovyle').Position.Y + 0, 1, 1, 0) -- Replace with GROUND:CharSetDrawEffect(ch, DrawEffect.Shaking) if this is a shaking animation
	GAME:WaitFrames(2)
	GROUND:AnimateToPosition(CH('Grovyle'), "None", CH('Grovyle').Direction, CH('Grovyle').Position.X + 1, CH('Grovyle').Position.Y + 0, 1, 1, 0) -- Replace with GROUND:CharSetDrawEffect(ch, DrawEffect.Shaking) if this is a shaking animation
	GAME:WaitFrames(2)
	GROUND:AnimateToPosition(CH('Grovyle'), "None", CH('Grovyle').Direction, CH('Grovyle').Position.X + -1, CH('Grovyle').Position.Y + 0, 1, 1, 0) -- Replace with GROUND:CharSetDrawEffect(ch, DrawEffect.Shaking) if this is a shaking animation
	UI:SetSpeaker(CH('Grovyle'))
	UI:SetSpeakerEmotion("Pain")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_Grovyle_1']))
	GROUND:CharTurnToCharAnimated(CH('PARTNER'), CH('Grovyle'), 4)
	SOUND:PlayBattleSE("EVT_Emote_Exclaim_2")
	GROUND:CharSetEmote(CH('PARTNER'), "exclaim", 1)
	GAME:WaitFrames(30)
	GROUND:CharTurnToCharAnimated(CH('PLAYER'), CH('Grovyle'), 4)
	--GROUND:CharWaitAnim(CH('Grovyle'), "UNK_31")
	GROUND:CharSetAnim(CH('Grovyle'), "None", false)
	GAME:WaitFrames(30)
	GROUND:CharAnimateTurnTo(CH('Grovyle'), Dir8.UpLeft, 4)
	UI:SetSpeaker(CH('PARTNER'))
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_PARTNER_10']))
	GROUND:CharTurnToCharAnimated(CH('Grovyle'), CH('PARTNER'), 4)
	-- Moving Camera to (392, 180) with speed 2 and performer 0 | The reason the duration is so complicated is because Vanilla EoS camera movement measures in *speed*, not total duration
	GAME:MoveCamera(392, 180, math.floor(math.sqrt((MRKR('PERF_0').Position.X - 392) * (MRKR('PERF_0').Position.X - 392) + (MRKR('PERF_0').Position.Y - 180) * (MRKR('PERF_0').Position.Y - 180)) / 2), false)
	GROUND:TeleportTo(MRKR('PERF_0'), 392, 180)
	GROUND:MoveToPosition(CH('PARTNER'), 376, 164, false, 1)
	GAME:WaitFrames(10)
	GROUND:MoveToPosition(CH('PLAYER'), 376, 188, false, 1)
	GROUND:CharAnimateTurnTo(CH('PLAYER'), Dir8.UpRight, 4)
	GAME:WaitFrames(30)
	CharacterActions.HopOnce(CH('PARTNER'), CH('PARTNER').Direction)
	UI:SetSpeaker(CH('PARTNER'))
	UI:SetSpeakerEmotion("Happy")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_PARTNER_11_'..tostring(pTalkKind)]))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_PARTNER_12']))
	UI:SetSpeaker(CH('Grovyle'))
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_Grovyle_2']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_Grovyle_3']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_Grovyle_4']))
	CharacterActions.HopOnce(CH('PARTNER'), CH('PARTNER').Direction)
	GROUND:CharTurnToCharAnimated(CH('PLAYER'), CH('PARTNER'), 4)
	UI:SetSpeaker(CH('PARTNER'))
	UI:SetSpeakerEmotion("Happy")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_PARTNER_13_'..tostring(pTalkKind)]))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_PARTNER_14']))
	GROUND:CharAnimateTurnTo(CH('PARTNER'), Dir8.DownLeft, 4)
	GAME:WaitFrames(30)
	GROUND:CharAnimateTurnTo(CH('PARTNER'), Dir8.DownRight, 4)
	GAME:WaitFrames(30)
	GROUND:CharAnimateTurnTo(CH('PARTNER'), Dir8.Left, 4)
	UI:SetSpeaker(CH('PARTNER'))
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_PARTNER_15_'..tostring(pTalkKind)]))
	-- Moving Camera to (360, 180) with speed 2 and performer 0 | The reason the duration is so complicated is because Vanilla EoS camera movement measures in *speed*, not total duration
	GAME:MoveCamera(360, 180, math.floor(math.sqrt((MRKR('PERF_0').Position.X - 360) * (MRKR('PERF_0').Position.X - 360) + (MRKR('PERF_0').Position.Y - 180) * (MRKR('PERF_0').Position.Y - 180)) / 2), false)
	GROUND:TeleportTo(MRKR('PERF_0'), 360, 180)
	GROUND:MoveToPosition(CH('PARTNER'), 296, 164, false, 2)
	GROUND:CharAnimateTurnTo(CH('PLAYER'), Dir8.Left, 8)
	UI:SetSpeaker(CH('PARTNER'))
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_PARTNER_16_'..tostring(pTalkKind)]))
	GROUND:CharTurnToCharAnimated(CH('PARTNER'), CH('Grovyle'), 4)
	CharacterActions.HopOnce(CH('PARTNER'), CH('PARTNER').Direction)
	UI:SetSpeaker(CH('PARTNER'))
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_PARTNER_17_'..tostring(pTalkKind)]))
	UI:SetSpeaker(CH('Grovyle'))
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_Grovyle_5']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_Grovyle_6']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_Grovyle_7']))
	SOUND:PlayBattleSE("EVT_Emote_Exclaim")
	GROUND:CharSetEmote(CH('PARTNER'), "exclaim", 1)
	GAME:WaitFrames(30)
	UI:SetSpeaker(CH('PARTNER'))
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_PARTNER_18']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_PARTNER_19_'..tostring(pTalkKind)]))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_PARTNER_20_'..tostring(pTalkKind)]))
	GROUND:CharAnimateTurnTo(CH('PARTNER'), Dir8.DownLeft, 4)
	GAME:WaitFrames(30)
	GROUND:CharAnimateTurnTo(CH('PARTNER'), Dir8.DownRight, 4)
	GAME:WaitFrames(30)
	GROUND:CharAnimateTurnTo(CH('PARTNER'), Dir8.Down, 4)
	GAME:WaitFrames(30)
	GROUND:CharTurnToCharAnimated(CH('PARTNER'), CH('Grovyle'), 4)
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_PARTNER_21']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_PARTNER_22']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_PARTNER_23_'..tostring(pTalkKind)]))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_PARTNER_24_'..tostring(pTalkKind)]))
	GROUND:MoveToPosition(CH('PARTNER'), CH('PARTNER').Position.X + 32, CH('PARTNER').Position.Y + 32, false, 2)
	GROUND:MoveToPosition(CH('PARTNER'), 400, 196, false, 2)
	GAME:WaitFrames(30)
	-- Moving Camera to (392, 180) with speed 2 and performer 0 | The reason the duration is so complicated is because Vanilla EoS camera movement measures in *speed*, not total duration
	GAME:MoveCamera(392, 180, math.floor(math.sqrt((MRKR('PERF_0').Position.X - 392) * (MRKR('PERF_0').Position.X - 392) + (MRKR('PERF_0').Position.Y - 180) * (MRKR('PERF_0').Position.Y - 180)) / 2), false)
	GROUND:TeleportTo(MRKR('PERF_0'), 392, 180)
	GROUND:CharAnimateTurnTo(CH('PLAYER'), Dir8.DownRight, 16)
	GROUND:CharAnimateTurnTo(CH('Grovyle'), Dir8.DownLeft, 16)
	UI:SetSpeaker(CH('Grovyle'))
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_Grovyle_8']))
	SOUND:PlayBattleSE("EVT_Emote_Exclaim")
	GROUND:CharSetEmote(CH('PARTNER'), "notice", 1)
	GAME:WaitFrames(30)
	GROUND:CharAnimateTurnTo(CH('PARTNER'), Dir8.UpRight, 4)
	GROUND:CharAnimateTurnTo(CH('PLAYER'), Dir8.UpRight, 4)
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_Grovyle_9']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_Grovyle_10']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_Grovyle_11']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_Grovyle_12']))
	SOUND:PlayBattleSE("EVT_Emote_Sweating")
	GROUND:CharSetEmote(CH('PARTNER'), "sweating", 1)
	GAME:WaitFrames(30)
	GROUND:CharAnimateTurnTo(CH('PLAYER'), Dir8.DownRight, 4)
	UI:SetSpeaker(CH('PARTNER'))
	UI:SetSpeakerEmotion("Sad")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_PARTNER_25_'..tostring(pTalkKind)]))
	GAME:WaitFrames(20)
	SOUND:PlayBattleSE("EVT_Emote_Exclaim")
	GROUND:CharSetEmote(CH('PARTNER'), "exclaim", 1)
	GAME:WaitFrames(30)
	UI:SetSpeaker(CH('PARTNER'))
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_PARTNER_26']))
	UI:SetSpeaker(CH('PARTNER'))
	UI:SetSpeakerEmotion("Sad")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_PARTNER_27_'..tostring(pTalkKind)]))







	UI:SetSpeaker(CH('Grovyle'))
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_Grovyle_13']))


	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_Grovyle_14']))



	UI:SetSpeaker(CH('PARTNER'))
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_PARTNER_28_'..tostring(pTalkKind)]))








	GROUND:MoveToPosition(CH('PARTNER'), CH('PARTNER').Position.X + 160, CH('PARTNER').Position.Y + 0, false, 2)
	GROUND:CharAnimateTurnTo(CH('PLAYER'), Dir8.Right, 8)
	GROUND:CharAnimateTurnTo(CH('Grovyle'), Dir8.Right, 8)
	GAME:WaitFrames(60)
	GROUND:MoveToPosition(CH('PLAYER'), CH('PLAYER').Position.X + 160, CH('PLAYER').Position.Y + 0, false, 2)
	GAME:WaitFrames(30)
	GROUND:MoveToPosition(CH('Grovyle'), CH('Grovyle').Position.X + 160, CH('Grovyle').Position.Y + 0, false, 2)
	GAME:WaitFrames(30)
	-- ### screen2_FadeOut(0, 60) [IRRELEVANT]
	SOUND:FadeOutSE("Ambient/AMB_Ocean.ogg", 120)
	GAME:FadeOut(false, 60)
	-- ### back2_SetMode(0) [IRRELEVANT]
	GAME:WaitFrames(60)
	-- TODO: WaitBgm(BGM_OCEAN1)
	-- TODO: $SPECIAL_EPISODE_OPEN[3] = 1
	SOUND:PlayFanfare("Fanfare/Note.ogg")
	UI:ResetSpeaker()
	UI:SetCenter(true)
	UI:WaitShowVoiceOver(STRINGS:Format(STRINGS.MapStrings['CH16_NARRATION_1']), -1)
	UI:SetCenter(false)



	-- back_SetGround(LEVEL_P26P01A) (ground mapping may be converted manually)
	-- ### supervision_Acting(10) [IRRELEVANT]
	GAME:MoveCamera(MRKR('PERF_0').Position.X, MRKR('PERF_0').Position.Y, 1, false)
	GAME:FadeIn(15)
	GAME:WaitFrames(30)
	SOUND:PlayFanfare("UNK_5.ogg")
	UI:SetCenter(true)
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_NARRATION_2']))
	UI:SetCenter(false)


	UI:SetCenter(true)
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_NARRATION_3']))
	UI:SetCenter(false)


	UI:SetCenter(true)
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH16_NARRATION_4']))
	UI:SetCenter(false)



	GAME:FadeOut(false, 30)
	GAME:WaitFrames(60)
	-- TODO: $SCENARIO_MAIN_BIT_FLAG[8] = 1
	-- TODO: $COMPULSORY_SAVE_POINT = 16
	ExplorerEssentials.AutosaveWithNotification()

end

function dusk_beach.UTIL_PopulateBubbles()
	local anims = {
		RogueEssence.Content.AnimData("BeachBubble_1", 15, -1, -1, 255, Dir8.None),
		RogueEssence.Content.AnimData("BeachBubble_2", 15, -1, -1, 255, Dir8.None),
		RogueEssence.Content.AnimData("BeachBubble_3", 15, -1, -1, 255, Dir8.None),
		RogueEssence.Content.AnimData("BeachBubble_8", 15, -1, -1, 255, Dir8.None),
		RogueEssence.Content.AnimData("BeachBubble_9", 15, -1, -1, 255, Dir8.None),
		RogueEssence.Content.AnimData("BeachSmallBubble_1", 15, -1, -1, 255, Dir8.None),
		RogueEssence.Content.AnimData("BeachSmallBubble_2", 15, -1, -1, 255, Dir8.None),
		RogueEssence.Content.AnimData("BeachSmallBubble_3", 15, -1, -1, 255, Dir8.None),
		RogueEssence.Content.AnimData("BeachSmallBubble_4", 15, -1, -1, 255, Dir8.None)
	}

	for i = 1, 10 do -- spawn 10 random bubbles

		local bubbleEmitter = RogueEssence.Content.MoveToEmitter()
    	bubbleEmitter.Anim = anims[math.random(#anims)]
    	bubbleEmitter.ResultLayer = RogueEssence.Content.DrawLayer.Front
    	bubbleEmitter.OffsetStart = RogueElements.Loc(180, -10)
    	bubbleEmitter.OffsetEnd = RogueElements.Loc(-900, math.random(-100, 100) - 10)
		bubbleEmitter.HeightStart = 10
        bubbleEmitter.HeightEnd = 10
    	bubbleEmitter.MoveTime = 2400 + math.random(-600, 600)

		GROUND:PlayVFX(bubbleEmitter, GAME:GetCameraCenter().X - (330 + math.random(-120, 120)), GAME:GetCameraCenter().Y + math.random(-100, 100))
	end
end

function dusk_beach.UTIL_BubbleSpawnerLoop()
	local anims = {
		RogueEssence.Content.AnimData("BeachBubble_1", 15, -1, -1, 255, Dir8.None),
		RogueEssence.Content.AnimData("BeachBubble_2", 15, -1, -1, 255, Dir8.None),
		RogueEssence.Content.AnimData("BeachBubble_3", 15, -1, -1, 255, Dir8.None),
		RogueEssence.Content.AnimData("BeachBubble_8", 15, -1, -1, 255, Dir8.None),
		RogueEssence.Content.AnimData("BeachBubble_9", 15, -1, -1, 255, Dir8.None),
		RogueEssence.Content.AnimData("BeachSmallBubble_1", 15, -1, -1, 255, Dir8.None),
		RogueEssence.Content.AnimData("BeachSmallBubble_2", 15, -1, -1, 255, Dir8.None),
		RogueEssence.Content.AnimData("BeachSmallBubble_3", 15, -1, -1, 255, Dir8.None),
		RogueEssence.Content.AnimData("BeachSmallBubble_4", 15, -1, -1, 255, Dir8.None)
	}
	
	while stopBubbles == false do
		GAME:WaitFrames(30)

		local bubbleEmitter = RogueEssence.Content.MoveToEmitter()
    	bubbleEmitter.Anim = anims[math.random(#anims)]
    	bubbleEmitter.ResultLayer = RogueEssence.Content.DrawLayer.Front
    	bubbleEmitter.OffsetStart = RogueElements.Loc(180, -10)
    	bubbleEmitter.OffsetEnd = RogueElements.Loc(-900, math.random(-100, 100) - 10)
		bubbleEmitter.HeightStart = 10
        bubbleEmitter.HeightEnd = 10
    	bubbleEmitter.MoveTime = 2400 + math.random(-600, 600)

		GROUND:PlayVFX(bubbleEmitter, GAME:GetCameraCenter().X, GAME:GetCameraCenter().Y + math.random(-100, 100))
	end
end

return dusk_beach

