--[[
    init.lua
    Created: 12/02/2023 17:20:52
    Description: Autogenerated script file for the map beach_cave.
]]--
-- Commonly included lua functions and data
require 'eos.common'
require 'eos.CharacterActions'
require 'eos.ExplorerEssentials'

-- Package name
local beach_cave = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---beach_cave.Init(zone)
--Engine callback function
function beach_cave.Init(zone)


end

---beach_cave.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function beach_cave.EnterSegment(zone, rescuing, segmentID, mapID)
	if rescuing ~= true then
		COMMON.BeginDungeon(zone.ID, segmentID, mapID)
	end
end

---beach_cave.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function beach_cave.ExitSegment(zone, result, rescue, segmentID, mapID)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  PrintInfo("=>> ExitSegment_beach_cave (Beach Cave) result "..tostring(result).." segment "..tostring(segmentID))

	GAME:SetRescueAllowed(false)
	
	SV.Dungeon.Zone = zone
	SV.Dungeon.Result = result
	SV.Dungeon.Rescue = rescue
	SV.Dungeon.SegmentID = segmentID
	SV.Dungeon.MapID = mapID

	PrintInfo("Result: "..tostring(result))
	PrintInfo("SegmentID: "..tostring(segmentID))

	if result ~= RogueEssence.Data.GameProgress.ResultType.Cleared then
		SV.beach_cave.FailedDungeon = true
		if segmentID == 1 then --boss segment
			SV.beach_cave.FailedBoss = true
		end

		GAME:WaitFrames(20)
		ExplorerEssentials.EndDungeonWithFanfare(result, "cutscenes", -1, 6, 0)
	else
		if SV.Progression.Chapter == 1 and segmentID == 1 then
			SV.Progression.SectionFlag = 1
		end
		GAME:WaitFrames(20)
		GAME:EnterZone("beach_cave", -1, 0, 0)
	end
end

---beach_cave.Rescued(zone, name, mail)
--Engine callback function
function beach_cave.Rescued(zone, name, mail)
  COMMON.Rescued(zone, name, mail)
end

return beach_cave

