--[[
    init.lua
    Created: 10/31/2023 15:01:40
    Description: Autogenerated script file for the map dusk_beach.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local dusk_beach = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---dusk_beach.Init(map)
--Engine callback function
function dusk_beach.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---dusk_beach.Enter(map)
--Engine callback function
function dusk_beach.Enter(map)

  GAME:FadeIn(20)
  
end

---dusk_beach.Exit(map)
--Engine callback function
function dusk_beach.Exit(map)


end

---dusk_beach.Update(map)
--Engine callback function
function dusk_beach.Update(map)


end

---dusk_beach.GameSave(map)
--Engine callback function
function dusk_beach.GameSave(map)


end

---dusk_beach.GameLoad(map)
--Engine callback function
function dusk_beach.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return dusk_beach

