--[[
    init.lua
    Created: 10/31/2023 15:01:40
    Description: Autogenerated script file for the map dusk_beach.
]]--
-- Commonly included lua functions and data
require 'common'
require 'CharacterActions'
require 'ExplorerEssentials'

-- Package name
local dusk_beach = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---dusk_beach.Init(map)
--Engine callback function
function dusk_beach.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()
  
  COMMON:RespawnAllies()

end

---dusk_beach.Enter(map)
--Engine callback function
function dusk_beach.Enter(map)

  GAME:CutsceneMode(true)
  
  if SV.Progression.Chapter == 1 then
	if SV.beach_cave.FailedDungeon then
		dusk_beach.CH1_FailedBeachCave()
	elseif SV.Progression.SectionFlag == 1 then
		dusk_beach.CH1_ExplorerTeamInvite()
	else
		dusk_beach.CH1_PartnerFindsHero()
	end
  end
  
end

---dusk_beach.Exit(map)
--Engine callback function
function dusk_beach.Exit(map)


end

---dusk_beach.Update(map)
--Engine callback function
function dusk_beach.Update(map)


end

---dusk_beach.GameSave(map)
--Engine callback function
function dusk_beach.GameSave(map)


end

---dusk_beach.GameLoad(map)
--Engine callback function
function dusk_beach.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------



-------------------------------
-- Cutscene Functions
-------------------------------

function dusk_beach.CH1_PartnerFindsHero()
	
	local player = CH('PLAYER')
	local partner = CH('PARTNER')
	
	partner.CollisionDisabled = true
	
	local hTalkKind = SV.Personality.HeroTalkKind
	local pTalkKind = SV.Personality.PartnerTalkKind
	
	local marker = MRKR("Entrance")
	local cam = MRKR("C1S1_CamPos_1")
	
	GROUND:TeleportTo(partner, marker.Position.X - 120, marker.Position.Y, Direction.Left)
	GAME:MoveCamera(cam.Position.X, cam.Position.Y, 1, false)
	
	--fade in to initial shot
	local coro1 = TASK:BranchCoroutine(function() SOUND:FadeInSE("Ambient/AMB_Ocean", 60) end)
	local coro2 = TASK:BranchCoroutine(function() GAME:FadeIn(60) end)
	TASK:JoinCoroutines({coro1, coro2})
	
	GAME:WaitFrames(120)
	
	GAME:FadeOut(false, 60)
	
	--krabby 1
	UI:WaitShowBG("Krabby", 10, 60)
	ExplorerEssentials.SpawnBubbles(1)
	GAME:WaitFrames(120)
	UI:WaitHideBG(60)
	
	--krabby 2 & play bgm
	SOUND:PlayBGM("004 - On the Beach at Dusk.ogg", true)
	UI:WaitShowBG("Krabby2", 10, 60)
	ExplorerEssentials.SpawnBubbles(2)
	GAME:WaitFrames(120)
	UI:WaitHideBG(60)
	
	--partner walks up
	ExplorerEssentials.SpawnBubbles(3)
	GAME:FadeIn(60)
	
	GAME:WaitFrames(60)
	
	GROUND:MoveToPosition(partner, cam.Position.X, marker.Position.Y, false, 1)
	
	GAME:WaitFrames(10)
	
	UI:SetSpeaker(partner)
	UI:SetSpeakerEmotion("Inspired")
	
	local coro1 = TASK:BranchCoroutine(function() UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Partner_1_'..tostring(pTalkKind)])) end)
	local coro2 = TASK:BranchCoroutine(function() GROUND:MoveToPosition(partner, cam.Position.X, cam.Position.Y, false, 1) end)
	TASK:JoinCoroutines({coro1, coro2})
	
	GAME:WaitFrames(60)
	
	GAME:FadeOut(false, 60)
	
	--sunset view
	UI:WaitShowBG("OceanSunset", 1, 60)
	ExplorerEssentials.SpawnBubbles(4)
	
	GAME:WaitFrames(240)
	UI:WaitHideBG(60)
	
	--back to partner
	ExplorerEssentials.SpawnBubbles(3)
	GAME:FadeIn(60)
	GAME:WaitFrames(60)
	
	UI:SetSpeakerEmotion("Normal")
	
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Partner_2'], _DATA:GetMonster("krabby"):GetColoredName()))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Partner_3_'..tostring(pTalkKind)]))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Partner_4_'..tostring(pTalkKind)]))
	
	GAME:FadeOut(false, 60)
	
	--back to view
	UI:WaitShowBG("OceanSunset", 1, 60)
	ExplorerEssentials.SpawnBubbles(4)
	
	GAME:WaitFrames(240)
	UI:WaitHideBG(60)
	
	--partner exposition
	ExplorerEssentials.SpawnBubbles(3)
	GAME:FadeIn(60)
	GAME:WaitFrames(60)
	
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Partner_5']))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Partner_6_'..tostring(pTalkKind)]))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Partner_7']))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Partner_8_'..tostring(pTalkKind)]))
	
	--bgm fade out
	local coro1 = TASK:BranchCoroutine(function() SOUND:FadeOutBGM(120) end)
	local coro2 = TASK:BranchCoroutine(function() GAME:WaitFrames(60) end)
	TASK:JoinCoroutines({coro1, coro2})
	
	GROUND:CharAnimateTurnTo(partner, Direction.Left, 4)
	
	GAME:WaitFrames(30)
	
	SOUND:PlayBattleSE("EVT_Emote_Exclaim")
	GROUND:CharSetEmote(partner, "notice", 1)
	
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Partner_9']))
	
	--partner notices something
	local marker = MRKR("C1S1_PlayerSpawn")
	GROUND:TeleportTo(player, marker.Position.X, marker.Position.Y, Direction.Right)
	GROUND:CharSetAnim(player, "Laying", true)
	
	local coro1 = TASK:BranchCoroutine(function() GAME:MoveCamera(cam.Position.X - 60, cam.Position.Y, 60, false) end)
	local coro2 = TASK:BranchCoroutine(function() GROUND:MoveInDirection(partner, Direction.Left, 60, false, 1) end)
	TASK:JoinCoroutines({coro1, coro2})
	
	SOUND:PlayBattleSE("EVT_Emote_Startled")
	GROUND:CharSetEmote(partner, "shock", 1)
	CharacterActions.ScaredJump(partner, Direction.Left)
	
	UI:SetSpeakerEmotion("Surprised")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Partner_10']))
	
	local coro1 = TASK:BranchCoroutine(function() GAME:MoveCamera(player.Position.X + 20, cam.Position.Y, 60, false) end)
	local coro2 = TASK:BranchCoroutine(function() GROUND:MoveInDirection(partner, Direction.Left, 60, false, 2) end)
	TASK:JoinCoroutines({coro1, coro2})
	
	CharacterActions.HopTwice(partner, Direction.Left)
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Partner_11']))
	
	--partner wakes up hero
	GROUND:CharSetDrawEffect(player, DrawEffect.Shaking)
	GAME:WaitFrames(10)
	GROUND:CharEndDrawEffect(player, DrawEffect.Shaking)
	
	UI:SetSpeaker('', false, player.CurrentForm.Species, player.CurrentForm.Form, player.CurrentForm.Skin, player.CurrentForm.Gender)
	UI:SetSpeakerEmotion("Pain")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Hero_1']))
	
	local coro1 = TASK:BranchCoroutine(function() UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Hero_2'])) end)
	local coro2 = TASK:BranchCoroutine(function() GAME:WaitFrames(10)
												GROUND:CharSetDrawEffect(player, DrawEffect.Shaking)
												GAME:WaitFrames(20)
												GROUND:CharEndDrawEffect(player, DrawEffect.Shaking) end)
	TASK:JoinCoroutines({coro1, coro2})
	
	GROUND:CharWaitAnim(player, "Wake")
	GAME:WaitFrames(30)
	GROUND:CharAnimateTurnTo(player, Direction.Down, 4)
	
	SOUND:PlayBattleSE("EVT_Emote_Exclaim")
	GROUND:CharSetEmote(partner, "exclaim", 1)
	GAME:WaitFrames(30)
	
	UI:SetSpeaker(partner)
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Partner_12_'..tostring(pTalkKind)]))
	
	GAME:WaitFrames(10)
	
	local coro1 = TASK:BranchCoroutine(function() GROUND:CharAnimateTurnTo(player, Direction.Left, 4) end)
	local coro2 = TASK:BranchCoroutine(function() GROUND:AnimateInDirection(partner, "Walk", Direction.Left, Direction.Right, 32, 1, 1) end)
	TASK:JoinCoroutines({coro1, coro2})
	
	GAME:WaitFrames(15)
	GROUND:CharAnimateTurnTo(player, Direction.Right, 4)
	GAME:WaitFrames(30)
	GROUND:CharAnimateTurnTo(player, Direction.Down, 4)
	GAME:WaitFrames(45)
	
	UI:SetSpeaker('', false, player.CurrentForm.Species, player.CurrentForm.Form, player.CurrentForm.Skin, player.CurrentForm.Gender)
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Hero_3']))
	
	GAME:WaitFrames(10)
	GROUND:CharTurnToCharAnimated(player, partner, 4, true)
	
	UI:SetSpeaker(partner)
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Partner_13_'..tostring(pTalkKind)]))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Partner_14_'..tostring(pTalkKind)]))
	
	GAME:WaitFrames(10)
	UI:SetSpeaker('', false, player.CurrentForm.Species, player.CurrentForm.Form, player.CurrentForm.Skin, player.CurrentForm.Gender)
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Hero_4']))
	
	GAME:WaitFrames(10)
	UI:SetSpeaker(partner)
	UI:SetSpeakerEmotion("Happy")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Partner_15_'..tostring(pTalkKind)], partner:GetDisplayName()))
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Partner_16_'..tostring(pTalkKind)]))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Partner_17_'..tostring(pTalkKind)]))
	
	GAME:WaitFrames(15)
	GROUND:CharSetAnim(player, "Walk", true)
	GAME:WaitFrames(45)
	GROUND:CharEndAnim(player)
	GAME:WaitFrames(30)
	
	SOUND:PlayBattleSE("EVT_Emote_Startled")
	CharacterActions.ScaredJump(partner, Direction.Left)
	
	GAME:WaitFrames(10)
	UI:SetSpeaker(partner)
	UI:SetSpeakerEmotion("Surprised")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Partner_18_'..tostring(pTalkKind)]))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Partner_19'], _DATA:GetMonster(player.CurrentForm.Species):GetColoredName()))
	
	--look around
	
	UI:SetSpeaker('', false, player.CurrentForm.Species, player.CurrentForm.Form, player.CurrentForm.Skin, player.CurrentForm.Gender)
	UI:SetSpeakerEmotion("Surprised")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Hero_5']))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Hero_6'], _DATA:GetMonster(player.CurrentForm.Species):GetColoredName()))
	
	GAME:WaitFrames(15)
	UI:SetSpeakerEmotion("Worried")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Hero_7']))
	
	GAME:WaitFrames(10)
	UI:SetSpeaker(partner)
	UI:SetSpeakerEmotion("Worried")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Partner_20']))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Partner_21']))
	
	--shake head
	
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Partner_22']))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Partner_23_'..tostring(pTalkKind)]))
	
	UI:SetSpeaker('', false, player.CurrentForm.Species, player.CurrentForm.Form, player.CurrentForm.Skin, player.CurrentForm.Gender)
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Hero_8']))
	
	GAME:WaitFrames(10)
	
	--name entry
	local ch = false
	local name = ""
	while not ch do
		name = ""
		while name == "" do
		UI:NameMenu(STRINGS:Format(MapStrings['Name_Prompt']), "")
		UI:WaitForChoice()
		name = UI:ChoiceResult()
		end
	
		GAME:SetCharacterNickname(GAME:GetPlayerPartyMember(0), name)
		UI:ChoiceMenuYesNo(STRINGS:Format(MapStrings['Name_Confirm'], name), true)
		UI:WaitForChoice()
		ch = UI:ChoiceResult()
	end
	
	GAME:WaitFrames(10)
	UI:SetSpeaker(partner)
	UI:SetSpeakerEmotion("Worried")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Partner_24_'..tostring(pTalkKind), player:GetDisplayName()]))
	
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Partner_25']))
	
	GAME:WaitFrames(15)
	--sweat
	
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Partner_26']))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Partner_27']))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Partner_28_'..tostring(pTalkKind)]))
	
	--setup koffing and zubat
	local koffing = CH('Koffing')
	local zubat = CH('Zubat')
	
	--bonk
	UI:SetSpeakerEmotion("Shouting")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Partner_29_'..tostring(pTalkKind)])) --put in coro later
	
	--move bullies
	
	UI:SetSpeaker(koffing)
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Koffing_1']))
	
	--partner angy
	
	UI:SetSpeaker(partner)
	UI:SetSpeakerEmotion("Angry")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Partner_30']))
	
	GAME:WaitFrames(10)
	UI:SetSpeaker(zubat)
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Zubat_1']))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Zubat_2']))
	
	--partner jumps
	
	UI:SetSpeaker(partner)
	UI:SetSpeakerEmotion("Surprised")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Partner_31']))
	
	GAME:WaitFrames(10)
	UI:SetSpeaker(zubat)
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Zubat_3']))
	
	GAME:WaitFrames(10)
	UI:SetSpeaker(partner)
	UI:SetSpeakerEmotion("Surprised")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Partner_32_'..tostring(pTalkKind)]))
	
	GAME:WaitFrames(10)
	UI:SetSpeaker(zubat)
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Zubat_4']))
	
	GAME:WaitFrames(10)
	UI:SetSpeaker(partner)
	UI:SetSpeakerEmotion("Surprised")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Partner_33']))
	
	GAME:WaitFrames(10)
	UI:SetSpeaker(koffing)
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Koffing_2']))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Koffing_3']))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Koffing_4']))
	
	GAME:WaitFrames(10)
	UI:SetSpeaker(zubat)
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Zubat_5']))
	
	--leave
	
	UI:SetSpeaker(partner)
	UI:SetSpeakerEmotion("Sad")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Partner_34']))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Partner_35']))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Partner_36']))
	
	UI:SetSpeakerEmotion("Teary-Eyed")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Partner_37']))
	
	--shake head
	
	UI:SetSpeakerEmotion("Determined")
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Partner_38']))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S1_Partner_39_'..tostring(pTalkKind)])) --turn into choice menu
	
	--A
	
	--B
	
	--debug end
	GAME:CutsceneMode(false)
	
end

function dusk_beach.CH1_ExplorerTeamInvite()
	--debug end
	GAME:CutsceneMode(false)
end

function dusk_beach.CH1_FailedBeachCave()

	local player = CH('PLAYER')
	local partner = CH('PARTNER')
	
	partner.CollisionDisabled = true
	
	local hTalkKind = SV.Personality.HeroTalkKind
	local pTalkKind = SV.Personality.PartnerTalkKind

	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S2_Partner_1']))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S2_Partner_2_'..tostring(pTalkKind)]))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S2_Partner_3']))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S2_Partner_4']))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S2_Partner_5_'..tostring(pTalkKind)]))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S2_Partner_6_'..tostring(pTalkKind)]))
	UI:WaitShowDialogue(STRINGS:Format(MapStrings['CH1_S2_Partner_7_'..tostring(pTalkKind)]))
	
	--debug end
	GAME:CutsceneMode(false)
end

return dusk_beach

