--[[
    init.lua
    Created: 09/23/2026 14:26:06
    Description: Autogenerated script file for the map test_room.
]]--
-- Commonly included lua functions and data
require 'origin.common'
require 'eos.CharacterActions'
require 'eos.ExplorerEssentials'

-- Package name
local test_room = {}

-------------------------------
-- Map Callbacks
-------------------------------
---test_room.Init(map)
--Engine callback function
function test_room.Init(map)

  ExplorerEssentials.SpawnPartner()
end

---test_room.Enter(map)
--Engine callback function
function test_room.Enter(map)

  GAME:FadeIn(20)

end

---test_room.Exit(map)
--Engine callback function
function test_room.Exit(map)


end

---test_room.Update(map)
--Engine callback function
function test_room.Update(map)


end

---test_room.GameSave(map)
--Engine callback function
function test_room.GameSave(map)


end

---test_room.GameLoad(map)
--Engine callback function
function test_room.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function test_room.JobBoard_Action(obj, activator)
  UI:WaitShowDialogue("WIP")
end

function test_room.OutlawBoard_Action(obj, activator)
  UI:WaitShowDialogue("WIP")
end

function test_room.EffectTest_Action(obj, activator)
  UI:WaitShowDialogue("Dimensional Scream")
  GAME:FadeOut(false, 5)
  GAME:WaitFrames(30)
  SOUND:PlayBattleSE("EVT_Dimensional_Scream")
  CharacterActions.DimensionalScream_In()
  GAME:WaitFrames(60)
  SOUND:PlayBattleSE("EVT_Dimensional_Scream_End")
  CharacterActions.DimensionalScream_Out()
  GAME:WaitFrames(30)
  GAME:FadeIn(5)
end

return test_room

