--[[
    init.lua
    Created: 02/04/2026 12:50:34
    Description: Autogenerated script file for the map guild_guildmaster_chambers_night.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local guild_guildmaster_chambers_night = {}

-------------------------------
-- Map Callbacks
-------------------------------
---guild_guildmaster_chambers_night.Init(map)
--Engine callback function
function guild_guildmaster_chambers_night.Init(map)


end

---guild_guildmaster_chambers_night.Enter(map)
--Engine callback function
function guild_guildmaster_chambers_night.Enter(map)

  GAME:FadeIn(20)

end

---guild_guildmaster_chambers_night.Exit(map)
--Engine callback function
function guild_guildmaster_chambers_night.Exit(map)


end

---guild_guildmaster_chambers_night.Update(map)
--Engine callback function
function guild_guildmaster_chambers_night.Update(map)


end

---guild_guildmaster_chambers_night.GameSave(map)
--Engine callback function
function guild_guildmaster_chambers_night.GameSave(map)


end

---guild_guildmaster_chambers_night.GameLoad(map)
--Engine callback function
function guild_guildmaster_chambers_night.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

-------------------------------
-- Cutscene Functions
-------------------------------

function guild_guildmaster_chambers_night.CH2_TeamSupport()
  --[[
  
def 0 {
    sound_Stop();
    back_SetGround(LEVEL_G01P05C);
    supervision_Acting(0);
    camera_SetMyself<performer 0>();
    screen_FadeIn(1, 30);
    Wait(30);
    message_SetFace(ACTOR_NPC_PERAPPU, FACE_NORMAL, FACE_POS_BOTTOM_R_FACEINW);
    message_Talk({
        english="""
             Guildmaster, I've brought you
            Team [team:].
        """,
    });
    message_Close();
    Wait(60);
    se_Play(8964);
    SetEffect<actor ACTOR_NPC_PERAPPU>(EFFECT_TWO_ARROWS_AT_SIDE_LEFT, 3);
    WaitEffect<actor ACTOR_NPC_PERAPPU>();
    WaitExecuteLives(ACTOR_NPC_PERAPPU);
    message_Talk({
        english="""
             Guildmaster...[K] Guildmaster?
            
        """,
    });
    message_Close();
    Wait(60);
    Turn2Direction<actor ACTOR_NPC_PUKURIN>(1, 10, DIR_DOWN);
    WaitExecuteLives(ACTOR_NPC_PUKURIN);
    se_Play(8974);
    SetEffect<actor ACTOR_NPC_PERAPPU>(EFFECT_SHOCKED, 3);
    SetEffect<actor ACTOR_PLAYER>(EFFECT_EXCLAMATION_MARK, 3);
    ExecuteCommon<actor ACTOR_ATTENDANT1>(CORO_JUMP_SURPRISE_FUNC_SERIES, 0);
    WaitExecuteLives(ACTOR_ATTENDANT1);
    bgm_PlayFadeIn(BGM_GUILDMASTER_WIGGLYTUFF, 0, 256);
    message_SetFace(ACTOR_NPC_PUKURIN, FACE_NORMAL, FACE_POS_TOP_L_CENTER);
    message_Talk({
        english=" Hiya!",
    });
    message_Talk({
        english=" Job not going well? That stinks!",
    });
    message_Talk({
        english=" That's why I'm giving you these!",
    });
    CallCommon(CORO_MESSAGE_CLOSE_WAIT_FUNC);
    MovePositionMark<actor ACTOR_NPC_PUKURIN>(1, Position<'m0', 27.5, 28.5>);
    Turn2Direction<actor ACTOR_ATTENDANT1>(16, 10, DIR_UPRIGHT);
    Turn2Direction<actor ACTOR_NPC_PERAPPU>(16, 10, DIR_LEFT);
    WaitExecuteLives(ACTOR_NPC_PUKURIN);
    SetAnimation<actor ACTOR_NPC_PERAPPU>(5);
    SlidePositionOffset<actor ACTOR_NPC_PERAPPU>(1, 8, 0);
    Turn2DirectionLives<actor ACTOR_NPC_PUKURIN>(4, 10, ACTOR_PLAYER);
    WaitExecuteLives(ACTOR_NPC_PUKURIN);
    SetAnimation<actor ACTOR_NPC_PERAPPU>(2);
    Wait(20);
    me_Play(4);
    message_Mail({
        english="""
            [CN][CS:N]Wigglytuff[CR] gave you
            [CN]a [CS:I]Reviver Seed[CR]!
        """,
    });
    WaitMe(4);
    CallCommon(CORO_MESSAGE_CLOSE_WAIT_FUNC);
    item_Set(0, 73, 0);
    switch ( message_Menu(MENU_GIVE_ITEM) ) { }
    Wait(10);
    me_Play(4);
    message_Mail({
        english="[CN]In addition, he also gave you an [CS:I]Oran Berry[CR]!",
    });
    WaitMe(4);
    CallCommon(CORO_MESSAGE_CLOSE_WAIT_FUNC);
    item_Set(0, 70, 0);
    switch ( message_Menu(MENU_GIVE_ITEM) ) { }
    Wait(10);
    me_Play(4);
    message_Mail({
        english="[CN]Incredibly, he also gave you a [CS:I]Max Elixir[CR]!",
    });
    WaitMe(4);
    CallCommon(CORO_MESSAGE_CLOSE_WAIT_FUNC);
    item_Set(0, 99, 0);
    switch ( message_Menu(MENU_GIVE_ITEM) ) { }
    Wait(10);
    Wait(20);
    message_SetFace(ACTOR_NPC_PUKURIN, FACE_NORMAL, FACE_POS_BOTTOM_C_FACER);
    message_FacePositionOffset(2, -1);
    message_Talk({
        english="""
             Those items I gave you are all
            very useful in dungeons.
        """,
    });
    message_Talk({
        english="""
             Please give it your best effort
            again tomorrow!
        """,
    });
    message_Close();
    bgm_FadeOut(120);
    screen_FadeOut(1, 60);
    WaitBgm(BGM_GUILDMASTER_WIGGLYTUFF);
    end;
}

  ]]--
end

return guild_guildmaster_chambers_night

