--[[
    init.lua
    Created: 12/13/2023 20:43:47
    Description: Autogenerated script file for the map beach_cave_pit.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local beach_cave_pit = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---beach_cave_pit.Init(map)
--Engine callback function
function beach_cave_pit.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()
  
  COMMON:RespawnAllies()

end

---beach_cave_pit.Enter(map)
--Engine callback function
function beach_cave_pit.Enter(map)

  if SV.Progression.Chapter == 1 then
	
	if SV.Progression.SectionFlag == 1 then
		--defeated boss
		beach_cave_pit.BossDefeated()
	elseif SV.beach_cave.FailedBoss then
		--reentry dialogue
		beach_cave_pit.BossReEntry()
	else
		--normal dialogue
		beach_cave_pit.EncounterBoss()
	end
	
	--rest of the cutscene continues as normal
  else
	--nothing left, time to go back
	beach_cave_pit.NothingHere()
  end

end

---beach_cave_pit.Exit(map)
--Engine callback function
function beach_cave_pit.Exit(map)


end

---beach_cave_pit.Update(map)
--Engine callback function
function beach_cave_pit.Update(map)


end

---beach_cave_pit.GameSave(map)
--Engine callback function
function beach_cave_pit.GameSave(map)


end

---beach_cave_pit.GameLoad(map)
--Engine callback function
function beach_cave_pit.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


-------------------------------
-- Cutscene Functions
-------------------------------

function beach_cave_pit.NothingHere()
	--DO THIS LATER
end

function beach_cave_pit.EncounterBoss()

end

function beach_cave_pit.BossReEntry()

end

function beach_cave_pit.BossDefeated()

end

return beach_cave_pit

