--[[
    init.lua
    Created: 11/22/2023 12:14:44
    Description: Autogenerated script file for the map crossroads_assembly.
]]--
-- Commonly included lua functions and data
require 'eos.common'
require 'eos.CharacterActions'
require 'eos.ExplorerEssentials'
-- Package name
local crossroads_assembly = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---crossroads_assembly.Init(map)
--Engine callback function
function crossroads_assembly.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  
COMMON:RespawnAllies()
SOUND:PlayBGM("BGM_TreasureTown.ogg", true)
ExplorerEssentials.SpawnPartner()

end

---crossroads_assembly.Enter(map)
--Engine callback function
function crossroads_assembly.Enter(map)

  GAME:FadeIn(20)

  if SV.Progression.Chapter == 3 then
        if SV.Progression.SectionFlag == 5 then
        crossroads_assembly.CH2BidoofTutorialScene4()
        end

  end


end

---crossroads_assembly.Exit(map)
--Engine callback function
function crossroads_assembly.Exit(map)

GAME:FadeOut(false, 20)
end

---crossroads_assembly.Update(map)
--Engine callback function
function crossroads_assembly.Update(map)


end

---crossroads_assembly.GameSave(map)
--Engine callback function
function crossroads_assembly.GameSave(map)


end

---crossroads_assembly.GameLoad(map)
--Engine callback function
function crossroads_assembly.GameLoad(map)

  GAME:FadeIn(20)
  ExplorerEssentials.SpawnPartner()

end


-------------------------------
-- Cutscene Functions
-------------------------------

function DEF_0()
	local hTalkKind = SV.Personality.HeroTalkKind
	local pTalkKind = SV.Personality.PartnerTalkKind
	-- back_SetGround(LEVEL_P01P01A) (Should be the map you're currently on, or the map it sends you to next)
	-- ### supervision_Acting(0) [IRRELEVANT]
	GAME:MoveCamera(MRKR('PERF_0').Position.X, MRKR('PERF_0').Position.Y, 1, false)
	GAME:WaitFrames(1)
	GAME:FadeIn(30)
	SOUND:PlayBGM("UNK_BGM_TREASURE_TOWN.ogg", true)
	GAME:WaitFrames(30)
	GROUND:MoveToPosition(CH('Bidoof'), 212, 152, false, 1)
	GROUND:MoveToPosition(CH('PLAYER'), 212, 128, false, 1)
	GROUND:MoveToPosition(CH('PARTNER'), 212, 104, false, 1)
	-- !! WaitExecuteLives(ACTOR_NPC_BIPPA)
	GROUND:CharAnimateTurnTo(CH('Bidoof'), Dir8.Right, 2)
	GAME:WaitFrames(10)
	GROUND:CharAnimateTurnTo(CH('PLAYER'), Dir8.Right, 2)
	GAME:WaitFrames(6)
	GROUND:CharAnimateTurnTo(CH('PARTNER'), Dir8.DownRight, 2)
	-- !! WaitExecuteLives(ACTOR_ATTENDANT1)
ExplorerEssentials.MoveCameraAtSpeed(252, 160, 1, false)
	-- TODO: WaitExecutePerformer(0)
	GAME:WaitFrames(10)
	UI:SetSpeaker(CH('Bidoof'))
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH3_S1_Bidoof_1']))
	-- TODO: message_KeyWait()
	GROUND:MoveToPosition(CH('PARTNER'), 232, 112, false, 1)
	GROUND:CharAnimateTurnTo(CH('PARTNER'), Dir8.DownRight, 2)
	-- !! WaitExecuteLives(ACTOR_ATTENDANT1)
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH3_S1_Bidoof_2']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH3_S1_Bidoof_3']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH3_S1_Bidoof_4']))
	-- !! CallCommon(CORO_MESSAGE_CLOSE_WAIT_FUNC)
	GROUND:CharAnimateTurnTo(CH('Bidoof'), Dir8.Down, 2)
	GAME:WaitFrames(3)
	GROUND:CharAnimateTurnTo(CH('PLAYER'), Dir8.Down, 2)
	GAME:WaitFrames(2)
	GROUND:CharAnimateTurnTo(CH('PARTNER'), Dir8.Down, 2)
	-- !! WaitExecuteLives(ACTOR_ATTENDANT1)
	GROUND:MoveToPosition(CH('Bidoof'), 212, 192, false, 1)
	GAME:WaitFrames(10)
	GROUND:MoveToPosition(CH('PLAYER'), 212, 152, false, 1)
	GAME:WaitFrames(18)
	GROUND:MoveToPosition(CH('PARTNER'), 212, 152, false, 1)
	GAME:WaitFrames(80)
	GAME:FadeOut(false, 30)
end

function DEF_0()
	local hTalkKind = SV.Personality.HeroTalkKind
	local pTalkKind = SV.Personality.PartnerTalkKind
	SOUND:PlayBGM("UNK_BGM_OH_NO.ogg", true)
	-- back_SetGround(LEVEL_P01P01A) (Should be the map you're currently on, or the map it sends you to next)
	-- ### supervision_Acting(0) [IRRELEVANT]
	GAME:MoveCamera(MRKR('PERF_0').Position.X, MRKR('PERF_0').Position.Y, 1, false)
	GAME:WaitFrames(1)
	GROUND:MoveToPosition(CH('PARTNER'), 212, 96, false, 1)
	GROUND:MoveToPosition(CH('PLAYER'), 212, 72, false, 1)
	GAME:FadeIn(15)
	GROUND:CharSetEmote(CH('UNK_ACTOR_NPC_MARIRU'), "sweating", 1)
	-- !! WaitExecuteLives(ACTOR_ATTENDANT1)
	-- !! WaitExecuteLives(ACTOR_PLAYER)
	GROUND:CharSetEmote(CH('UNK_ACTOR_NPC_MARIRU'), "sweating", 1)
	GROUND:CharAnimateTurnTo(CH('PARTNER'), Dir8.DownRight, 2)
	GROUND:CharAnimateTurnTo(CH('PLAYER'), Dir8.DownRight, 2)
	-- !! WaitExecuteLives(ACTOR_ATTENDANT1)
	GROUND:CharSetEmote(CH('PARTNER'), "exclaim", 1)
	GAME:WaitFrames(30)
	UI:SetSpeaker(CH('PARTNER'))
	UI:SetSpeakerEmotion("Surprised")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH3_S2_PARTNER_1_'..tostring(pTalkKind)]))
ExplorerEssentials.MoveCameraAtSpeed(212, 184, 1, false)
	GROUND:MoveToPosition(CH('PARTNER'), 212, 200, false, 1)
	GROUND:MoveToPosition(CH('PLAYER'), 212, 176, false, 1)
	GROUND:CharAnimateTurnTo(CH('UNK_ACTOR_NPC_MARIRU'), Dir8.Left, 1)
	-- !! WaitExecuteLives(ACTOR_NPC_MARIRU)
	GROUND:CharSetEmote(CH('UNK_ACTOR_NPC_MARIRU'), "exclaim", 1)
	GAME:WaitFrames(30)
	GROUND:MoveToPosition(CH('UNK_ACTOR_NPC_MARIRU'), 256, 192, false, 1)
	GAME:WaitFrames(10)
	-- !! WaitExecuteLives(ACTOR_ATTENDANT1)
	GROUND:CharAnimateTurnTo(CH('PARTNER'), Dir8.Right, 2)
	-- !! WaitExecuteLives(ACTOR_PLAYER)
	GROUND:CharAnimateTurnTo(CH('PLAYER'), Dir8.Right, 2)
	-- TODO: WaitExecutePerformer(0)
	UI:SetSpeaker(CH('PARTNER'))
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH3_S2_PARTNER_2_'..tostring(pTalkKind)]))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH3_S2_PARTNER_3']))
	-- !! CallCommon(CORO_MESSAGE_CLOSE_WAIT_FUNC)
	CharacterActions.HopOnce(CH('UNK_ACTOR_NPC_MARIRU'), CH('UNK_ACTOR_NPC_MARIRU').Direction)
	-- !! WaitExecuteLives(ACTOR_NPC_MARIRU)
	GROUND:CharSetEmote(CH('UNK_ACTOR_NPC_MARIRU'), "sweating", 1)
	UI:SetSpeaker(CH('UNK_ACTOR_NPC_MARIRU'))
	UI:SetSpeakerEmotion("Sigh")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH3_S2_UNK_ACTOR_NPC_MARIRU_1']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH3_S2_UNK_ACTOR_NPC_MARIRU_2']))
	UI:WaitShowTimedDialogue(STRINGS:Format(STRINGS.MapStrings['CH3_S2_UNK_ACTOR_NPC_MARIRU_3']), CH('DROWZEE'):GetDisplayName(), CH('AZURILL'):GetDisplayName())
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH3_S2_UNK_ACTOR_NPC_MARIRU_4']))
	-- !! CallCommon(CORO_MESSAGE_CLOSE_WAIT_FUNC)
	UI:SetSpeaker(CH('PARTNER'))
	UI:SetSpeakerEmotion("Surprised")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH3_S2_PARTNER_4']))
	-- !! CallCommon(CORO_MESSAGE_CLOSE_WAIT_FUNC)
	UI:SetSpeaker(CH('UNK_ACTOR_NPC_MARIRU'))
	UI:SetSpeakerEmotion("Sigh")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH3_S2_UNK_ACTOR_NPC_MARIRU_5']))
	ExplorerEssentials.MoveToPositionOffset(CH('UNK_ACTOR_NPC_MARIRU'), 120, 0, false, 2)
	GAME:WaitFrames(10)
	ExplorerEssentials.MoveToPositionOffset(CH('PLAYER'), 160, 0, false, 2)
	GAME:WaitFrames(5)
	ExplorerEssentials.MoveToPositionOffset(CH('PARTNER'), 160, 0, false, 2)
	GAME:WaitFrames(45)
	SOUND:FadeOutBGM(120)
	GAME:FadeOut(false, 60)
	-- TODO: WaitBgm(BGM_OH_NO)
	-- TODO: dungeon_mode(4) = DMODE_OPEN
end

function crossroads_assembly.CH2BidoofTutorialScene4()
        player = CH("PLAYER")
        partner = CH("TEAMMATE_1") --why does this have to be like this?
        Bidoof = CH("Bidoof")
	AI:DisableCharacterAI(partner)
        GAME:MoveCamera(0, 0, 1, true)
        local hTalkKind = SV.Personality.HeroTalkKind
        local pTalkKind = SV.Personality.PartnerTalkKind
        Bidoof.CollisionDisabled = true
        partner.CollisionDisabled = true
        player.CollisionDisabled = true
        local marker = MRKR("GuildOutsideEntranceMarker")

        GAME:FadeIn(20)
        GROUND:TeleportTo(Bidoof, marker.Position.X, marker.Position.Y, Direction.Down)
        GROUND:TeleportTo(player, marker.Position.X, marker.Position.Y, Direction.Down)
        GROUND:TeleportTo(partner, marker.Position.X, marker.Position.Y, Direction.Down)

        local coro2 = TASK:BranchCoroutine(function() GROUND:MoveToPosition(Bidoof, 211, 153, false, 1) end)
        local coro3 = TASK:BranchCoroutine(function() GAME:WaitFrames(30) GROUND:MoveToPosition(player, 211, 132, false, 1) end)
        local coro4 = TASK:BranchCoroutine(function() GAME:WaitFrames(60) GROUND:MoveToPosition(partner, 211, 107, false, 1) end )
        TASK:JoinCoroutines({coro2, coro3, coro4})
	GROUND:CharAnimateTurnTo(partner, Direction.DownRight, 2)
	GROUND:CharAnimateTurnTo(player, Direction.Right, 2)
	GROUND:CharAnimateTurnTo(Bidoof, Direction.Right, 2)
	GAME:MoveCamera(marker.Position.X + 80, marker.Position.Y, 1, true)
	--bidoof talks 1
	--bidoof talks 2
	GROUND:MoveToPosition(partner, 239, 107, false, 1)
	GROUND:CharAnimateTurnTo(partner, Direction.DownRight, 2)
	--bidoof talks 3
	--bidoof talks 4
	--bidoof talks 5
	GROUND:CharAnimateTurnTo(partner, Direction.Down, 2)
	GROUND:CharAnimateTurnTo(player, Direction.Down, 2)
	GROUND:CharAnimateTurnTo(Bidoof, Direction.Down, 2)
        local marker1 = MRKR("TreasureTownEntranceMarker")
        local coro5 = TASK:BranchCoroutine(function() GROUND:MoveToPosition(Bidoof, 215, 194, false, 1) GROUND:MoveToPosition(Bidoof, marker1.Position.X, marker1.Position.Y, false, 1) end)
        local coro6 = TASK:BranchCoroutine(function() GAME:WaitFrames(30) GROUND:MoveToPosition(player, 215, 194, false, 1) GROUND:MoveToPosition(player, marker1.Position.X, marker1.Position.Y, false, 1)  end)
        local coro7 = TASK:BranchCoroutine(function() GAME:WaitFrames(60) GROUND:MoveToPosition(partner, 211, 107, false, 1) GROUND:MoveToPosition(partner, 215, 194, false, 1) GROUND:MoveToPosition(partner, marker1.Position.X, marker1.Position.Y, false, 1) end)
	local coro8 = TASK:BranchCoroutine(function() GAME:WaitFrames(180) GAME:FadeOut(false, 10) end)
        TASK:JoinCoroutines({coro5, coro6, coro7, coro8})

        SV.Progression.SectionFlag = 6
        GAME:EnterGroundMap("treasure_town", "CrossRoadsAssemblyEntranceMarker")

end


-------------------------------
-- Entities Callbacks
-------------------------------

function crossroads_assembly.GuildOutsideEntrance_Touch(obj, activator)
SV.partner.Spawn = 'CrossRoadsEntranceMarker'
GAME:EnterGroundMap("guild_outside", "CrossRoadsEntranceMarker")

end

function crossroads_assembly.CrossRoadsSouthEntrance_Touch(obj, activator)
SV.partner.Spawn = 'CrossRoadsAssemblyEntranceMarker'
GAME:EnterGroundMap("crossroads_south", "CrossRoadsAssemblyEntranceMarker")

end

function crossroads_assembly.TreasureTownEntrance_Touch(obj, activator)
SV.partner.Spawn = 'CrossRoadsAssemblyEntranceMarker'
GAME:EnterGroundMap("treasure_town", "CrossRoadsAssemblyEntranceMarker")

end

return crossroads_assembly

