--[[
    init.lua
    Created: 02/04/2026 13:42:16
    Description: Autogenerated script file for the map guild_dining_hall_night.
]]--
-- Commonly included lua functions and data
require 'eos.common'
require 'eos.ExplorerEssentials'
require 'eos.CharacterActions'

-- Package name
local guild_dining_hall_night = {}

-------------------------------
-- Map Callbacks
-------------------------------
---guild_dining_hall_night.Init(map)
--Engine callback function
function guild_dining_hall_night.Init(map)
    SV.MajorFlags = SV.MajorFlags or {}
    COMMON.RespawnStarterPartner()
end

---guild_dining_hall_night.Enter(map)
--Engine callback function
function guild_dining_hall_night.Enter(map)
    guild_dining_hall_night.COMMON_DinnerTime()
end

---guild_dining_hall_night.Exit(map)
--Engine callback function
function guild_dining_hall_night.Exit(map)


end

---guild_dining_hall_night.Update(map)
--Engine callback function
function guild_dining_hall_night.Update(map)


end

---guild_dining_hall_night.GameSave(map)
--Engine callback function
function guild_dining_hall_night.GameSave(map)


end

---guild_dining_hall_night.GameLoad(map)
--Engine callback function
function guild_dining_hall_night.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

-------------------------------
-- Cutscene Functions
-------------------------------

function guild_dining_hall_night.COMMON_DinnerTime()
  --[[
  
def 0 {
    sound_Stop();
    back_SetGround(LEVEL_G01P06B);
    supervision_Acting(0);
    camera_SetMyself<performer 0>();
    MovePositionOffset<performer 0>(0.5, -200, 0);
    Wait(1);
    SetAnimation<actor ACTOR_PLAYER>(64);
    SetAnimation<actor ACTOR_ATTENDANT1>(64);
    SetAnimation<actor ACTOR_NPC_PERAPPU>(43);
    SetAnimation<actor ACTOR_NPC_DOGOOMU>(42);
    SetAnimation<actor ACTOR_NPC_DIGUDA>(42);
    SetAnimation<actor ACTOR_NPC_DAGUTORIO>(42);
    SetAnimation<actor ACTOR_NPC_KIMAWARI>(42);
    SetAnimation<actor ACTOR_NPC_HEIGANI>(42);
    SetAnimation<actor ACTOR_NPC_BIPPA>(42);
    SetAnimation<actor ACTOR_NPC_GUREGGURU>(42);
    SetAnimation<actor ACTOR_NPC_CHIRIIN>(42);
    SetAnimation<actor ACTOR_NPC_ZUBATTO>(43);
    SetAnimation<actor ACTOR_NPC_DOGAASU>(43);
    SetAnimation<actor ACTOR_NPC_SUKATANKU>(42);
    SetEffect<actor ACTOR_NPC_PERAPPU>(EFFECT_EATING, 3);
    SetEffect<actor ACTOR_NPC_CHIRIIN>(EFFECT_EATING, 3);
    SetEffect<actor ACTOR_NPC_HEIGANI>(EFFECT_EATING, 3);
    SetEffect<actor ACTOR_NPC_BIPPA>(EFFECT_EATING, 3);
    SetEffect<actor ACTOR_NPC_DOGOOMU>(EFFECT_EATING, 3);
    SetEffect<actor ACTOR_PLAYER>(EFFECT_EATING, 3);
    SetEffect<actor ACTOR_ATTENDANT1>(EFFECT_EATING, 3);
    SetEffect<actor ACTOR_NPC_SUKATANKU>(EFFECT_EATING, 3);
    SetEffect<actor ACTOR_NPC_DIGUDA>(EFFECT_EATING_SLOW, 3);
    SetEffect<actor ACTOR_NPC_DAGUTORIO>(EFFECT_EATING_SLOW, 3);
    SetEffect<actor ACTOR_NPC_GUREGGURU>(EFFECT_EATING_SLOW, 3);
    SetEffect<actor ACTOR_NPC_KIMAWARI>(EFFECT_EATING_SLOW, 3);
    SetEffect<actor ACTOR_NPC_ZUBATTO>(EFFECT_EATING_SLOW, 3);
    SetEffect<actor ACTOR_NPC_DOGAASU>(EFFECT_EATING_SLOW, 3);
    switch ( sector() ) {
        case 1:
            @label_0;
            Destroy<actor ACTOR_NPC_PUKURIN>();
            @label_2;
            SetAnimation<object OBJECT_G01P06B1_107>(20);
            bgm_PlayFadeIn(BGM_EATING, 60, 256);
            screen_FadeIn(1, 30);
            message_ImitationSound({
                english="""
                    Crunch-munch! Chew-chew! Snuffle-slurp!
                    Crunch-munch! Chew-chew! Snuffle-slurp!
                """,
            });
            message_ImitationSound({
                english="""
                    Crunch-munch! Chew-chew! Snuffle-slurp!
                    Crunch-munch! Chew-chew! Snuffle-slurp!
                """,
            });
            message_ImitationSound({
                english="""
                    Crunch-munch! Chew-chew! Snuffle-slurp!
                    Crunch-munch! Chew-chew! Snuffle-slurp!
                """,
            });
            message_ImitationSound({
                english="""
                    Crunch-munch! Chew-chew! Snuffle-slurp!
                    Crunch-munch! Chew-chew! Snuffle-slurp!
                """,
            });
            message_ImitationSound({
                english="""
                    Crunch-munch! Chew-chew! Snuffle-slurp!
                    Crunch-munch! Chew-chew! Snuffle-slurp!
                """,
            });
            message_ImitationSound({
                english="""
                    Crunch-munch! Chew-chew! Snuffle-slurp!
                    Crunch-munch! Chew-chew! Snuffle-slurp!
                """,
            });
            message_CloseEnforce();
            bgm_FadeOut(60);
            screen_FadeOut(1, 30);
            WaitBgm(BGM_EATING);
            Wait(30);
            end;
        default:
            @label_1;
            WaitLockLives(5, ACTOR_NPC_PUKURIN);
            Unlock(5);
            jump @label_2;
    }
}

def 1 for actor ACTOR_NPC_PUKURIN {
    SetAnimation(5);
    SetEffect(EFFECT_APPLE_ON_HEAD, 3);
    Lock(5);
    @label_3;
    forever {
        Turn2Direction(8, 1, DIR_UP);
        Wait(20);
        Turn2Direction(8, 1, DIR_DOWN);
        Wait(20);
        continue;  // may be redundant
    }
}

  ]]--

    local continue = true 

    ExplorerEssentials.SetupCameraPos(45.5, 26)
    ExplorerEssentials.SetupInitialPos(CH('Wigglytuff'), 45, 27, Direction.Down)
    ExplorerEssentials.SetupInitialPos(CH('Chatot'), 41.5, 24.5, Direction.Left)
    ExplorerEssentials.SetupInitialPos(CH('Diglett'), 38.5, 27.5, Direction.Up)
    ExplorerEssentials.SetupInitialPos(CH('Dugtrio'), 35.5, 27.5, Direction.Up)
    ExplorerEssentials.SetupInitialPos(CH('Croagunk'), 32.5, 27.5, Direction.Up)
    ExplorerEssentials.SetupInitialPos(CH('Sunflora'), 29.5, 27.5, Direction.Up)
    ExplorerEssentials.SetupInitialPos(CH('Chimecho'), 38.5, 21.5, Direction.Down)
    ExplorerEssentials.SetupInitialPos(CH('Corphish'), 35.5, 21.5, Direction.Down)
    ExplorerEssentials.SetupInitialPos(CH('Bidoof'), 32.5, 21.5, Direction.Down)
    ExplorerEssentials.SetupInitialPos(CH('Loudred'), 29.5, 21.5, Direction.Down)
    ExplorerEssentials.SetupInitialPos(CH('PLAYER'), 26.5, 21.5, Direction.Down)
    ExplorerEssentials.SetupInitialPos(CH('PARTNER'), 23.5, 21.5, Direction.Down)
    if SV.MajorFlags.TeamSkullInGuild == true then
        ExplorerEssentials.SetupInitialPos(CH('UNK_ACTOR_NPC_ZUBATTO'), 26.5, 27.5, Direction.Up)
        ExplorerEssentials.SetupInitialPos(CH('UNK_ACTOR_NPC_DOGAASU'), 23.5, 27.5, Direction.Up)
        ExplorerEssentials.SetupInitialPos(CH('UNK_ACTOR_NPC_SUKATANKU'), 20.5, 24.5, Direction.Right)
    end

    -- setting up food
    -- 0 (default): everyone
    -- 1: everyone except hero + partner
    -- 2: everyone except hero + partner + loudred / everyone except bidoof (?)
    -- 3: everyone + team skull
    -- 4: everyone + team skull except hero + partner

    if SV.MajorFlags.TeamSkullInGuild == true then
        GROUND:ObjectSetDefaultAnim(OBJ('GuildFood'), "GuildFood", 1, 3, 3, Direction.Down)
    end
    
    local coro1 = TASK:BranchCoroutine(function()

        SOUND:StopBGM()

        -- back_SetGround(LEVEL_G01P06B) (Should be the map you're currently on, or the map it sends you to next)
        -- ### supervision_Acting(0) [IRRELEVANT]

        GROUND:CharSetAnim(CH('PLAYER'), "Eat", true)
        GROUND:CharSetAnim(CH('PARTNER'), "Eat", true)
        GROUND:CharSetAnim(CH('Chatot'), "Eat", true)
        GROUND:CharSetAnim(CH('Loudred'), "Eat", true)
        GROUND:CharSetAnim(CH('Diglett'), "Eat", true)
        GROUND:CharSetAnim(CH('Dugtrio'), "Eat", true)
        GROUND:CharSetAnim(CH('Sunflora'), "Eat", true)
        GROUND:CharSetAnim(CH('Corphish'), "Eat", true)
        GROUND:CharSetAnim(CH('Bidoof'), "Eat", true)
        GROUND:CharSetAnim(CH('Croagunk'), "Eat", true)
        GROUND:CharSetAnim(CH('Chimecho'), "Eat", true)
        if SV.MajorFlags.TeamSkullInGuild == true then
            GROUND:CharSetAnim(CH('UNK_ACTOR_NPC_ZUBATTO'), "Eat", true)
            GROUND:CharSetAnim(CH('UNK_ACTOR_NPC_DOGAASU'), "Eat", true)
            GROUND:CharSetAnim(CH('UNK_ACTOR_NPC_SUKATANKU'), "Eat", true)
        end

        GROUND:CharSetEmote(CH('Chatot'), "eating", -1)
        GROUND:CharSetEmote(CH('Chimecho'), "eating", -1)
        GROUND:CharSetEmote(CH('Corphish'), "eating", -1)
        GROUND:CharSetEmote(CH('Bidoof'), "eating", -1)
        GROUND:CharSetEmote(CH('Loudred'), "eating", -1)
        GROUND:CharSetEmote(CH('PLAYER'), "eating", -1)
        GROUND:CharSetEmote(CH('PARTNER'), "eating", -1)
        if SV.MajorFlags.TeamSkullInGuild == true then
            GROUND:CharSetEmote(CH('UNK_ACTOR_NPC_SUKATANKU'), "eating", -1)
        end

        GROUND:CharSetEmote(CH('Diglett'), "eating_slow", -1)
        GROUND:CharSetEmote(CH('Dugtrio'), "eating_slow", -1)
        GROUND:CharSetEmote(CH('Croagunk'), "eating_slow", -1)
        GROUND:CharSetEmote(CH('Sunflora'), "eating_slow", -1)
        if SV.MajorFlags.TeamSkullInGuild == true then
            GROUND:CharSetEmote(CH('UNK_ACTOR_NPC_ZUBATTO'), "eating_slow", -1)
            GROUND:CharSetEmote(CH('UNK_ACTOR_NPC_DOGAASU'), "eating_slow", -1)
        end

        -- TODO: @label_0
        -- GROUND:Hide("Wigglytuff")
        -- TODO: @label_2
        -- TODO SetAnimation: SetAnimation<object OBJECT_G01P06B1_107>(20)

        local coro1B = TASK:BranchCoroutine(function () SOUND:FadeInSE("Battle/EVT_Dinner", 60) end)
        local coro2B = TASK:BranchCoroutine(function () GAME:FadeIn(30) end)
        TASK:JoinCoroutines({coro1B, coro2B})

        UI:SetSpeaker('', false)
        for i = 1, 6, 1 do
            UI:WaitShowTimedDialogue(STRINGS:Format(STRINGS.MapStrings['C_EATING']), 1)
        end

        local coro1B = TASK:BranchCoroutine(function () SOUND:FadeOutSE("Battle/EVT_Dinner", 60) end)
        local coro2B = TASK:BranchCoroutine(function () 
            GAME:FadeOut(false, 30)
            GAME:WaitFrames(30)
        end)
        TASK:JoinCoroutines({coro1B, coro2B})

        continue = false
    end)
    local coro2 = TASK:BranchCoroutine(function() -- wigglytuff
        -- DEF_1 for actor ACTOR_NPC_PUKURIN()
       
        GROUND:CharSetEmote(CH('Wigglytuff'), "apple_on_head", -1)
        GROUND:CharSetAnim(CH('Wigglytuff'), "Walk", true)

        -- TODO: Lock(5)
        -- TODO: @label_3
        while continue do
            -- Turn2Direction(8, 1, DIR_UP)
            GROUND:CharAnimateTurnTo(CH('Wigglytuff'), Dir8.Up, 8)
            GAME:WaitFrames(20)
            GROUND:CharAnimateTurnTo(CH('Wigglytuff'), Dir8.Down, 8)
            GAME:WaitFrames(20)
        end
    end)
    local coro3 = TASK:BranchCoroutine(function() -- camera
        -- TODO MovePositionOffset: MovePositionOffset<performer 0>(0.5, -200, 0)
        ExplorerEssentials.MoveCameraAtSpeedOffset(-200, 0, 0.5, false)
    end)
    TASK:JoinCoroutines({coro1, coro2, coro3})

    if SV.MajorFlags.SawDinnerCutscene ~= true then
        guild_dining_hall_night.CH2_FirstDinner()
    end

    GAME:EnterGroundMap("guild_bedroom_night", 'Entrance', false)
end

function guild_dining_hall_night.CH2_FirstDinner()
  --[[
  
def 0 {
    sound_Stop();
    back_SetGround(LEVEL_G01P06B);
    supervision_Acting(0);
    camera_SetMyself<performer 0>();
    MovePositionOffset<performer 0>(0.5, -200, 0);
    Wait(1);
    SetAnimation<actor ACTOR_PLAYER>(64);
    SetAnimation<actor ACTOR_ATTENDANT1>(64);
    SetAnimation<actor ACTOR_NPC_PERAPPU>(43);
    SetAnimation<actor ACTOR_NPC_DOGOOMU>(42);
    SetAnimation<actor ACTOR_NPC_DIGUDA>(42);
    SetAnimation<actor ACTOR_NPC_DAGUTORIO>(42);
    SetAnimation<actor ACTOR_NPC_KIMAWARI>(42);
    SetAnimation<actor ACTOR_NPC_HEIGANI>(42);
    SetAnimation<actor ACTOR_NPC_BIPPA>(42);
    SetAnimation<actor ACTOR_NPC_GUREGGURU>(42);
    SetAnimation<actor ACTOR_NPC_CHIRIIN>(42);
    SetEffect<actor ACTOR_NPC_PERAPPU>(EFFECT_EATING, 3);
    SetEffect<actor ACTOR_NPC_CHIRIIN>(EFFECT_EATING, 3);
    SetEffect<actor ACTOR_NPC_HEIGANI>(EFFECT_EATING, 3);
    SetEffect<actor ACTOR_NPC_BIPPA>(EFFECT_EATING, 3);
    SetEffect<actor ACTOR_NPC_DOGOOMU>(EFFECT_EATING, 3);
    SetEffect<actor ACTOR_PLAYER>(EFFECT_EATING, 3);
    SetEffect<actor ACTOR_ATTENDANT1>(EFFECT_EATING, 3);
    SetEffect<actor ACTOR_NPC_DIGUDA>(EFFECT_EATING_SLOW, 3);
    SetEffect<actor ACTOR_NPC_DAGUTORIO>(EFFECT_EATING_SLOW, 3);
    SetEffect<actor ACTOR_NPC_GUREGGURU>(EFFECT_EATING_SLOW, 3);
    SetEffect<actor ACTOR_NPC_KIMAWARI>(EFFECT_EATING_SLOW, 3);
    switch ( sector() ) {
        case 1:
            @label_0;
            Destroy<actor ACTOR_NPC_PUKURIN>();
            @label_1;
            bgm_PlayFadeIn(BGM_EATING, 60, 256);
            screen_FadeIn(1, 30);
            message_ImitationSound({
                english="""
                    Crunch-munch! Chew-chew! Snuffle-slurp!
                    Crunch-munch! Chew-chew! Snuffle-slurp!
                """,
            });
            message_ImitationSound({
                english="""
                    Crunch-munch! Chew-chew! Snuffle-slurp!
                    Crunch-munch! Chew-chew! Snuffle-slurp!
                """,
            });
            message_ImitationSound({
                english="""
                    Crunch-munch! Chew-chew! Snuffle-slurp!
                    Crunch-munch! Chew-chew! Snuffle-slurp!
                """,
            });
            message_ImitationSound({
                english="""
                    Crunch-munch! Chew-chew! Snuffle-slurp!
                    Crunch-munch! Chew-chew! Snuffle-slurp!
                """,
            });
            message_ImitationSound({
                english="""
                    Crunch-munch! Chew-chew! Snuffle-slurp!
                    Crunch-munch! Chew-chew! Snuffle-slurp!
                """,
            });
            message_ImitationSound({
                english="""
                    Crunch-munch! Chew-chew! Snuffle-slurp!
                    Crunch-munch! Chew-chew! Snuffle-slurp!
                """,
            });
            message_CloseEnforce();
            bgm_FadeOut(60);
            screen_FadeOut(1, 30);
            WaitBgm(BGM_EATING);
            Wait(30);
            if ( scn($SCENARIO_MAIN) == [3, 3] || scn($SCENARIO_MAIN) == [3, 6] ) {
                supervision_RemoveActing(0);
                message_ResetActor();
                message_Talk({
                    english=" Aaaaah! I'm done eating! Excellent meal!",
                });
                CallCommon(CORO_MESSAGE_CLOSE_WAIT_FUNC);
                message_Talk({
                    english=" I'm stuffed, and now I'm getting sleepy...",
                });
                CallCommon(CORO_MESSAGE_CLOSE_WAIT_FUNC);
                message_Talk({
                    english=" Yep, I'm off to bed! Good night, gang!",
                });
                CallCommon(CORO_MESSAGE_CLOSE_WAIT_FUNC);
                message_Talk({
                    english=" Good night!",
                });
                message_Close();
                Wait(30);
                end;
            } else {
                end;
            }
            break;
        default:
            WaitLockLives(5, ACTOR_NPC_PUKURIN);
            Unlock(5);
            jump @label_1;
    }
}

def 1 for actor ACTOR_NPC_PUKURIN {
    SetAnimation(5);
    SetEffect(EFFECT_APPLE_ON_HEAD, 3);
    Lock(5);
    @label_3;
    forever {
        Turn2Direction(8, 1, DIR_UP);
        Wait(20);
        Turn2Direction(8, 1, DIR_DOWN);
        Wait(20);
        continue;  // may be redundant
    }
}

  ]]--

    -- ### supervision_RemoveActing(0) [IRRELEVANT]
    ExplorerEssentials.SetSpeakerUnknown(nil)
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Unknown_1']))
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Unknown_2']))
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Unknown_3']))
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Unknown_4']))

    GAME:WaitFrames(30)

    SV.MajorFlags.SawDinnerCutscene = true
  
end

return guild_dining_hall_night

