--[[
    init.lua
    Created: 02/04/2026 12:43:09
    Description: Autogenerated script file for the map guild_bedroom.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local guild_bedroom = {}

-------------------------------
-- Map Callbacks
-------------------------------
---guild_bedroom.Init(map)
--Engine callback function
function guild_bedroom.Init(map)


end

---guild_bedroom.Enter(map)
--Engine callback function
function guild_bedroom.Enter(map)

  GAME:FadeIn(20)

end

---guild_bedroom.Exit(map)
--Engine callback function
function guild_bedroom.Exit(map)


end

---guild_bedroom.Update(map)
--Engine callback function
function guild_bedroom.Update(map)


end

---guild_bedroom.GameSave(map)
--Engine callback function
function guild_bedroom.GameSave(map)


end

---guild_bedroom.GameLoad(map)
--Engine callback function
function guild_bedroom.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

-------------------------------
-- Cutscene Functions
-------------------------------

function guild_bedroom.COMMON_WakeUp()
  --[[
  
def 0 {
    sound_Stop();
    if ( scn($SCENARIO_MAIN) == [4, 0] ) {
        @label_0;
        back_SetBanner2(LEVEL_S21P01A, 0, 128, 96, 3, {
            english="The Scream",
        });
        screen_FadeIn(1, 45);
        Wait(160);
        screen_FadeOut(1, 45);
        Wait(15);
        @label_4;
        $SCENARIO_MAIN_BIT_FLAG[1] = 1;
        message_Narration(30, {
            english="[CN]The next morning...",
        });
        message_Close();
        Wait(30);
        message_SetFace(ACTOR_NPC_DOGOOMU, FACE_NORMAL, FACE_POS_BOTTOM_L_FACEINW);
        message_Talk({
            english=" UP AND AT 'EM![K] IT'S MORNING!",
        });
        message_Close();
        back_SetGround(LEVEL_G01P07A);
        supervision_StationCommon(0);
        supervision_Acting(0);
        camera_SetMyself<performer 0>();
        SetAnimation<actor ACTOR_PLAYER>(76);
        SetAnimation<actor ACTOR_ATTENDANT1>(76);
        screen_FadeIn(1, 30);
        se_Play(8971);
        camera_SetEffect(2, 2, 3.0);
        SetAnimation<actor ACTOR_NPC_DOGOOMU>(18);
        WaitAnimation<actor ACTOR_NPC_DOGOOMU>();
        WaitExecuteLives(ACTOR_NPC_DOGOOMU);
        SetAnimation<actor ACTOR_NPC_DOGOOMU>(2);
        camera_SetEffect(0, 0, 0);
        Wait(10);
        MovePositionOffset<actor ACTOR_NPC_DOGOOMU>(1.5, -96, 0);
        WaitExecuteLives(ACTOR_NPC_DOGOOMU);
        Destroy<actor ACTOR_NPC_DOGOOMU>();
        SlidePositionOffset<actor ACTOR_ATTENDANT1>(1, 1, 0);
        WaitExecuteLives(ACTOR_ATTENDANT1);
        Wait(2);
        SlidePositionOffset<actor ACTOR_PLAYER>(1, 1, 0);
        SlidePositionOffset<actor ACTOR_ATTENDANT1>(1, -1, 0);
        WaitExecuteLives(ACTOR_ATTENDANT1);
        Wait(2);
        SlidePositionOffset<actor ACTOR_PLAYER>(1, -1, 0);
        SlidePositionOffset<actor ACTOR_ATTENDANT1>(1, 1, 0);
        WaitExecuteLives(ACTOR_ATTENDANT1);
        Wait(2);
        SlidePositionOffset<actor ACTOR_PLAYER>(1, 1, 0);
        SlidePositionOffset<actor ACTOR_ATTENDANT1>(1, -1, 0);
        WaitExecuteLives(ACTOR_ATTENDANT1);
        Wait(2);
        SlidePositionOffset<actor ACTOR_PLAYER>(1, -1, 0);
        message_SetFace(ACTOR_ATTENDANT1, FACE_DIZZY, FACE_POS_STANDARD);
        message_SwitchTalk ($PARTNER_TALK_KIND) {
            case 1:
                {
                    english="""
                         Ugh! Good morning,
                        [hero]...
                    """,
                }
            case 2:
                {
                    english="""
                         Ugh! Good morning,
                        [hero]...
                    """,
                }
            default:
                {
                    english="""
                         Ugh! Good morning,
                        [hero]...
                    """,
                }
        }
        message_Close();
        Wait(30);
        bgm_PlayFadeIn(BGM_WIGGLYTUFFS_GUILD, 0, 256);
        SetAnimation<actor ACTOR_PLAYER>(63);
        SetAnimation<actor ACTOR_ATTENDANT1>(63);
        WaitAnimation<actor ACTOR_PLAYER>();
        WaitAnimation<actor ACTOR_ATTENDANT1>();
        Wait(10);
        SetAnimation<actor ACTOR_PLAYER>(2);
        Turn2Direction<actor ACTOR_PLAYER>(4, 10, DIR_DOWN);
        SetAnimation<actor ACTOR_ATTENDANT1>(2);
        Turn2Direction<actor ACTOR_ATTENDANT1>(4, 10, DIR_DOWN);
        Wait(30);
        main_SetGround(LEVEL_G01P07A);
        $SCENARIO_MAIN_BIT_FLAG[7] = 1;
        CallCommon(CORO_HANYOU_SAVE_FUNC);
        CallCommon(CORO_EVENT_END_MAPIN);
        supervision_ExecuteStationCommon(LEVEL_G01P07A, 1);
        end;
    } elseif ( scn($SCENARIO_MAIN) == [5, 0] ) {
        back_SetBanner2(LEVEL_V04P02A, 0, 156, 136, 4, {
            english="The Gatekeepers",
        });
        screen_FadeIn(1, 45);
        Wait(160);
        screen_FadeOut(1, 45);
        Wait(15);
        jump @label_4;
    } elseif ( scn($SCENARIO_MAIN) == [6, 0] ) {
        back_SetBanner2(LEVEL_D04P11A, 0, 252, 180, 5, {
            english="""
                The First
                Official
                Exploration
            """,
        });
        screen_FadeIn(1, 45);
        Wait(160);
        screen_FadeOut(1, 45);
        Wait(15);
        jump @label_4;
    } elseif ( scn($SCENARIO_MAIN) == [7, 0] ) {
        back_SetBanner2(LEVEL_D05P31A, 0, 276, 128, 6, {
            english="Team Skull",
        });
        screen_FadeIn(1, 45);
        Wait(160);
        screen_FadeOut(1, 45);
        Wait(15);
        jump @label_4;
    } else {
        jump @label_4;
    }
}

  ]]--
end

function guild_bedroom.CH2_BedroomTour()
  --[[
  
def 0 {
    back_SetGround(LEVEL_G01P07A);
    supervision_Acting(0);
    camera_SetMyself<performer 0>();
    screen_FadeIn(1, 30);
    bgm_PlayFadeIn(BGM_WIGGLYTUFFS_GUILD_REMIX, 0, 256);
    Wait(30);
    message_SetFace(ACTOR_NPC_PERAPPU, FACE_NORMAL, FACE_POS_TOP_L_FACEINW);
    message_Talk({
        english=" This is your room! ♪",
    });
    CallCommon(CORO_MESSAGE_CLOSE_WAIT_FUNC);
    MovePositionMark<actor ACTOR_PLAYER>(1, Position<'m0', 25.5, 23>);
    Wait(10);
    MovePositionMark<actor ACTOR_ATTENDANT1>(1, Position<'m1', 19.5, 23>);
    WaitExecuteLives(ACTOR_PLAYER);
    Turn2Direction<actor ACTOR_PLAYER>(4, 1, DIR_LEFT);
    WaitExecuteLives(ACTOR_ATTENDANT1);
    Turn2Direction<actor ACTOR_ATTENDANT1>(4, 10, DIR_DOWN);
    WaitExecuteLives(ACTOR_ATTENDANT1);
    Wait(20);
    SetAnimation<actor ACTOR_ATTENDANT1>(3);
    MoveHeight<actor ACTOR_ATTENDANT1>(2, 10);
    Wait(1);
    MoveHeight<actor ACTOR_ATTENDANT1>(2, 0);
    Wait(2);
    MoveHeight<actor ACTOR_ATTENDANT1>(2, 10);
    Wait(1);
    MoveHeight<actor ACTOR_ATTENDANT1>(2, 0);
    SetAnimation<actor ACTOR_ATTENDANT1>(2);
    SetEffect<actor ACTOR_ATTENDANT1>(EFFECT_LAUGHING, 3);
    message_SetFace(ACTOR_ATTENDANT1, FACE_JOYOUS, FACE_POS_BOTTOM_C_FACEL);
    message_FacePositionOffset(-2, -1);
    message_SwitchTalk ($PARTNER_TALK_KIND) {
        case 1:
            {
                english=" Wow! We get beds!",
            }
        case 2:
            {
                english=" Great! We get beds!",
            }
        default:
            {
                english=" Yay! We get beds!",
            }
    }
    CallCommon(CORO_MESSAGE_CLOSE_WAIT_FUNC);
    SetEffect<actor ACTOR_ATTENDANT1>(EFFECT_NONE, 3);
    Turn2Direction<actor ACTOR_ATTENDANT1>(4, 10, DIR_UPLEFT);
    Turn2DirectionLives<actor ACTOR_PLAYER>(4, 10, ACTOR_NPC_PERAPPU);
    message_SetFace(ACTOR_NPC_PERAPPU, FACE_NORMAL, FACE_POS_TOP_L_FACEINW);
    message_Talk({
        english="""
             You will live here while you
            work for us.
        """,
    });
    message_Talk({
        english="""
             Things will start getting busy
            for you tomorrow! ♪[K] So rise early and start
            living up to our code!
        """,
    });
    message_Talk({
        english="""
             Don't stay up late. Get to sleep
            early tonight! ♪[K] That is all.
        """,
    });
    CallCommon(CORO_MESSAGE_CLOSE_WAIT_FUNC);
    MovePositionOffset<actor ACTOR_NPC_PERAPPU>(1, -8, 8);
    WaitExecuteLives(ACTOR_NPC_PERAPPU);
    Turn2Direction<actor ACTOR_ATTENDANT1>(4, 10, DIR_LEFT);
    MovePositionOffset<actor ACTOR_NPC_PERAPPU>(1, -88, 0);
    WaitExecuteLives(ACTOR_NPC_PERAPPU);
    Destroy<actor ACTOR_NPC_PERAPPU>();
    Wait(30);
    bgm_FadeOut(120);
    screen_FadeOut(1, 90);
    WaitBgm(BGM_WIGGLYTUFFS_GUILD_REMIX);
    end;
}

  ]]--
end

function guild_bedroom.CH2_WakeUp()
  
end

return guild_bedroom

