--[[
    init.lua
    Created: 02/04/2026 12:43:09
    Description: Autogenerated script file for the map guild_bedroom.
]]--
-- Commonly included lua functions and data
require 'eos.common'
require 'eos.CharacterActions'
require 'eos.ExplorerEssentials'

-- Package name
local guild_bedroom = {}

-------------------------------
-- Map Callbacks
-------------------------------
---guild_bedroom.Init(map)
--Engine callback function
function guild_bedroom.Init(map)

    ExplorerEssentials.SpawnPartner()
end

---guild_bedroom.Enter(map)
--Engine callback function
function guild_bedroom.Enter(map)

    if SV.Progression.Chapter == 2 then
        if SV.Progression.SectionFlag == 1 and SV.drenched_bluff.TimesFailed == 0 then
            guild_bedroom.CH2_WakeUp()
        elseif SV.Progression.SectionFlag == 0 then
            guild_bedroom.CH2_BedroomTour()
        else
            guild_bedroom.COMMON_WakeUp()
        end
    else
        guild_bedroom.COMMON_WakeUp()
    end

end

---guild_bedroom.Exit(map)
--Engine callback function
function guild_bedroom.Exit(map)


end

---guild_bedroom.Update(map)
--Engine callback function
function guild_bedroom.Update(map)


end

---guild_bedroom.GameSave(map)
--Engine callback function
function guild_bedroom.GameSave(map)


end

---guild_bedroom.GameLoad(map)
--Engine callback function
function guild_bedroom.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function guild_bedroom.Exit_Touch()
    if not SV.DailyFlags.DidMorningCheers then
        GROUND:EnterGroundMap("guild_basement", "Entrance", true)
    end    
end

-------------------------------
-- Cutscene Functions
-------------------------------

function guild_bedroom.COMMON_WakeUp()
  --[[
  
def 0 {
    sound_Stop();
    if ( scn($SCENARIO_MAIN) == [4, 0] ) {
        @label_0;
        back_SetBanner2(LEVEL_S21P01A, 0, 128, 96, 3, {
            english="The Scream",
        });
        screen_FadeIn(1, 45);
        Wait(160);
        screen_FadeOut(1, 45);
        Wait(15);
        @label_4;
        $SCENARIO_MAIN_BIT_FLAG[1] = 1;
        message_Narration(30, {
            english="[CN]The next morning...",
        });
        message_Close();
        Wait(30);
        message_SetFace(ACTOR_NPC_DOGOOMU, FACE_NORMAL, FACE_POS_BOTTOM_L_FACEINW);
        message_Talk({
            english=" UP AND AT 'EM![K] IT'S MORNING!",
        });
        message_Close();
        back_SetGround(LEVEL_G01P07A);
        supervision_StationCommon(0);
        supervision_Acting(0);
        camera_SetMyself<performer 0>();
        SetAnimation<actor ACTOR_PLAYER>(76);
        SetAnimation<actor ACTOR_ATTENDANT1>(76);
        screen_FadeIn(1, 30);
        se_Play(8971);
        camera_SetEffect(2, 2, 3.0);
        SetAnimation<actor ACTOR_NPC_DOGOOMU>(18);
        WaitAnimation<actor ACTOR_NPC_DOGOOMU>();
        WaitExecuteLives(ACTOR_NPC_DOGOOMU);
        SetAnimation<actor ACTOR_NPC_DOGOOMU>(2);
        camera_SetEffect(0, 0, 0);
        Wait(10);
        MovePositionOffset<actor ACTOR_NPC_DOGOOMU>(1.5, -96, 0);
        WaitExecuteLives(ACTOR_NPC_DOGOOMU);
        Destroy<actor ACTOR_NPC_DOGOOMU>();
        SlidePositionOffset<actor ACTOR_ATTENDANT1>(1, 1, 0);
        WaitExecuteLives(ACTOR_ATTENDANT1);
        Wait(2);
        SlidePositionOffset<actor ACTOR_PLAYER>(1, 1, 0);
        SlidePositionOffset<actor ACTOR_ATTENDANT1>(1, -1, 0);
        WaitExecuteLives(ACTOR_ATTENDANT1);
        Wait(2);
        SlidePositionOffset<actor ACTOR_PLAYER>(1, -1, 0);
        SlidePositionOffset<actor ACTOR_ATTENDANT1>(1, 1, 0);
        WaitExecuteLives(ACTOR_ATTENDANT1);
        Wait(2);
        SlidePositionOffset<actor ACTOR_PLAYER>(1, 1, 0);
        SlidePositionOffset<actor ACTOR_ATTENDANT1>(1, -1, 0);
        WaitExecuteLives(ACTOR_ATTENDANT1);
        Wait(2);
        SlidePositionOffset<actor ACTOR_PLAYER>(1, -1, 0);
        message_SetFace(ACTOR_ATTENDANT1, FACE_DIZZY, FACE_POS_STANDARD);
        message_SwitchTalk ($PARTNER_TALK_KIND) {
            case 1:
                {
                    english="""
                         Ugh! Good morning,
                        [hero]...
                    """,
                }
            case 2:
                {
                    english="""
                         Ugh! Good morning,
                        [hero]...
                    """,
                }
            default:
                {
                    english="""
                         Ugh! Good morning,
                        [hero]...
                    """,
                }
        }
        message_Close();
        Wait(30);
        bgm_PlayFadeIn(BGM_WIGGLYTUFFS_GUILD, 0, 256);
        SetAnimation<actor ACTOR_PLAYER>(63);
        SetAnimation<actor ACTOR_ATTENDANT1>(63);
        WaitAnimation<actor ACTOR_PLAYER>();
        WaitAnimation<actor ACTOR_ATTENDANT1>();
        Wait(10);
        SetAnimation<actor ACTOR_PLAYER>(2);
        Turn2Direction<actor ACTOR_PLAYER>(4, 10, DIR_DOWN);
        SetAnimation<actor ACTOR_ATTENDANT1>(2);
        Turn2Direction<actor ACTOR_ATTENDANT1>(4, 10, DIR_DOWN);
        Wait(30);
        main_SetGround(LEVEL_G01P07A);
        $SCENARIO_MAIN_BIT_FLAG[7] = 1;
        CallCommon(CORO_HANYOU_SAVE_FUNC);
        CallCommon(CORO_EVENT_END_MAPIN);
        supervision_ExecuteStationCommon(LEVEL_G01P07A, 1);
        end;
    } elseif ( scn($SCENARIO_MAIN) == [5, 0] ) {
        back_SetBanner2(LEVEL_V04P02A, 0, 156, 136, 4, {
            english="The Gatekeepers",
        });
        screen_FadeIn(1, 45);
        Wait(160);
        screen_FadeOut(1, 45);
        Wait(15);
        jump @label_4;
    } elseif ( scn($SCENARIO_MAIN) == [6, 0] ) {
        back_SetBanner2(LEVEL_D04P11A, 0, 252, 180, 5, {
            english="""
                The First
                Official
                Exploration
            """,
        });
        screen_FadeIn(1, 45);
        Wait(160);
        screen_FadeOut(1, 45);
        Wait(15);
        jump @label_4;
    } elseif ( scn($SCENARIO_MAIN) == [7, 0] ) {
        back_SetBanner2(LEVEL_D05P31A, 0, 276, 128, 6, {
            english="Team Skull",
        });
        screen_FadeIn(1, 45);
        Wait(160);
        screen_FadeOut(1, 45);
        Wait(15);
        jump @label_4;
    } else {
        jump @label_4;
    }
}

  ]]--

	AI:DisableCharacterAI(CH('PARTNER'))
    CH('Loudred').CollisionDisabled = true
	
	UI:WaitShowVoiceOver(STRINGS:Format(STRINGS.MapStrings['C_NARRATION_1']), -1)
	GAME:WaitFrames(30)

	UI:SetSpeaker(CH('Loudred'))
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['C_Loudred_1']))

	-- back_SetGround(LEVEL_G01P07A) (Should be the map you're currently on, or the map it sends you to next)
	-- ### supervision_StationCommon(0) [IRRELEVANT]
	-- ### supervision_Acting(0) [IRRELEVANT]
	ExplorerEssentials.SetupCameraPos(22, 22.5)
    ExplorerEssentials.SetupInitialPos(CH('PLAYER'), 25, 22, Direction.Right)
    ExplorerEssentials.SetupInitialPos(CH('PARTNER'), 19, 22, Direction.Left)
    ExplorerEssentials.SetupInitialPos(CH('Loudred'), 13.5, 21.5, Direction.Right)

	GROUND:CharSetAction(CH('PLAYER'), RogueEssence.Ground.PoseGroundAction(CH('PLAYER').Position, CH('PLAYER').Direction, RogueEssence.Content.GraphicsManager.GetAnimIndex("Pain")))
    GROUND:CharSetAction(CH('PARTNER'), RogueEssence.Ground.PoseGroundAction(CH('PARTNER').Position, CH('PARTNER').Direction, RogueEssence.Content.GraphicsManager.GetAnimIndex("Pain")))

	GAME:FadeIn(30)
	
    SOUND:PlayBattleSE("EVT_Emote_Complain_2")
	-- TODO: camera_SetEffect(2, 2, 3.0)
    GROUND:MoveScreen(RogueEssence.Content.ScreenMover(2, 2, 80))
	GROUND:CharWaitAnim(CH('Loudred'), "Hop")
	
	GAME:WaitFrames(10)
	ExplorerEssentials.MoveToPositionOffset(CH('Loudred'), -96, 0, false, 2)
	-- !! WaitExecuteLives(ACTOR_NPC_DOGOOMU)

	GROUND:Hide("Loudred")

    GROUND:CharSetDrawEffect(CH('PARTNER'), DrawEffect.Shaking)
	GAME:WaitFrames(2)
    GROUND:CharSetDrawEffect(CH('PLAYER'), DrawEffect.Shaking)
	GAME:WaitFrames(4)
    GROUND:CharEndDrawEffect(CH('PARTNER'), DrawEffect.Shaking)
	GAME:WaitFrames(2)
	GROUND:CharEndDrawEffect(CH('PLAYER'), DrawEffect.Shaking)
	
    UI:SetSpeaker(CH('PARTNER'))
	UI:SetSpeakerEmotion("Dizzy")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['C_PARTNER_1']))

	GAME:WaitFrames(30)
	SOUND:PlayBGM("008 - Wigglytuff's Guild.ogg")
	
    local coro1 = TASK:BranchCoroutine(function () GROUND:CharWaitAnim(CH('PLAYER'), "Wake", false) end)
	local coro2 = TASK:BranchCoroutine(function () GROUND:CharWaitAnim(CH('PARTNER'), "Wake", false) end)
    TASK:JoinCoroutines({coro1, coro2})

	GAME:WaitFrames(10)

	local coro1 = TASK:BranchCoroutine(function () GROUND:CharAnimateTurnTo(CH('PLAYER'), Dir8.Down, 4) end)
	local coro2 = TASK:BranchCoroutine(function () GROUND:CharAnimateTurnTo(CH('PARTNER'), Dir8.Down, 4) end)
    TASK:JoinCoroutines({coro1, coro2})

	GAME:WaitFrames(30)

	-- TODO: main_SetGround(LEVEL_G01P07A)
	-- TODO: $SCENARIO_MAIN_BIT_FLAG[7] = 1

    ExplorerEssentials.MoveCameraAtSpeed(0, 0, 1, true)
	ExplorerEssentials.AutosaveWithNotification()

    GAME:CutsceneMode(false)
    AI:EnableCharacterAI(CH('PARTNER'))
	-- TODO CallCommon: CallCommon(CORO_EVENT_END_MAPIN)
	-- ### supervision_ExecuteStationCommon(LEVEL_G01P07A, 1) [IRRELEVANT]
end

function guild_bedroom.CH2_BedroomTour()
  --[[
  
def 0 {
    back_SetGround(LEVEL_G01P07A);
    supervision_Acting(0);
    camera_SetMyself<performer 0>();
    screen_FadeIn(1, 30);
    bgm_PlayFadeIn(BGM_WIGGLYTUFFS_GUILD_REMIX, 0, 256);
    Wait(30);
    message_SetFace(ACTOR_NPC_PERAPPU, FACE_NORMAL, FACE_POS_TOP_L_FACEINW);
    message_Talk({
        english=" This is your room! ♪",
    });
    CallCommon(CORO_MESSAGE_CLOSE_WAIT_FUNC);
    MovePositionMark<actor ACTOR_PLAYER>(1, Position<'m0', 25.5, 23>);
    Wait(10);
    MovePositionMark<actor ACTOR_ATTENDANT1>(1, Position<'m1', 19.5, 23>);
    WaitExecuteLives(ACTOR_PLAYER);
    Turn2Direction<actor ACTOR_PLAYER>(4, 1, DIR_LEFT);
    WaitExecuteLives(ACTOR_ATTENDANT1);
    Turn2Direction<actor ACTOR_ATTENDANT1>(4, 10, DIR_DOWN);
    WaitExecuteLives(ACTOR_ATTENDANT1);
    Wait(20);
    SetAnimation<actor ACTOR_ATTENDANT1>(3);
    MoveHeight<actor ACTOR_ATTENDANT1>(2, 10);
    Wait(1);
    MoveHeight<actor ACTOR_ATTENDANT1>(2, 0);
    Wait(2);
    MoveHeight<actor ACTOR_ATTENDANT1>(2, 10);
    Wait(1);
    MoveHeight<actor ACTOR_ATTENDANT1>(2, 0);
    SetAnimation<actor ACTOR_ATTENDANT1>(2);
    SetEffect<actor ACTOR_ATTENDANT1>(EFFECT_LAUGHING, 3);
    message_SetFace(ACTOR_ATTENDANT1, FACE_JOYOUS, FACE_POS_BOTTOM_C_FACEL);
    message_FacePositionOffset(-2, -1);
    message_SwitchTalk ($PARTNER_TALK_KIND) {
        case 1:
            {
                english=" Wow! We get beds!",
            }
        case 2:
            {
                english=" Great! We get beds!",
            }
        default:
            {
                english=" Yay! We get beds!",
            }
    }
    CallCommon(CORO_MESSAGE_CLOSE_WAIT_FUNC);
    SetEffect<actor ACTOR_ATTENDANT1>(EFFECT_NONE, 3);
    Turn2Direction<actor ACTOR_ATTENDANT1>(4, 10, DIR_UPLEFT);
    Turn2DirectionLives<actor ACTOR_PLAYER>(4, 10, ACTOR_NPC_PERAPPU);
    message_SetFace(ACTOR_NPC_PERAPPU, FACE_NORMAL, FACE_POS_TOP_L_FACEINW);
    message_Talk({
        english="""
             You will live here while you
            work for us.
        """,
    });
    message_Talk({
        english="""
             Things will start getting busy
            for you tomorrow! ♪[K] So rise early and start
            living up to our code!
        """,
    });
    message_Talk({
        english="""
             Don't stay up late. Get to sleep
            early tonight! ♪[K] That is all.
        """,
    });
    CallCommon(CORO_MESSAGE_CLOSE_WAIT_FUNC);
    MovePositionOffset<actor ACTOR_NPC_PERAPPU>(1, -8, 8);
    WaitExecuteLives(ACTOR_NPC_PERAPPU);
    Turn2Direction<actor ACTOR_ATTENDANT1>(4, 10, DIR_LEFT);
    MovePositionOffset<actor ACTOR_NPC_PERAPPU>(1, -88, 0);
    WaitExecuteLives(ACTOR_NPC_PERAPPU);
    Destroy<actor ACTOR_NPC_PERAPPU>();
    Wait(30);
    bgm_FadeOut(120);
    screen_FadeOut(1, 90);
    WaitBgm(BGM_WIGGLYTUFFS_GUILD_REMIX);
    end;
}

  ]]--

    GAME:CutsceneMode(true)
    AI:DisableCharacterAI(CH('PARTNER'))
	local pTalkKind = SV.Personality.PartnerTalkKind

    CH('Chatot').CollisionDisabled = true
    CH('PLAYER').CollisionDisabled = true
    CH('PARTNER').CollisionDisabled = true

	-- back_SetGround(LEVEL_G01P07A) (Should be the map you're currently on, or the map it sends you to next)
	-- ### supervision_Acting(0) [IRRELEVANT]
    
    ExplorerEssentials.SetupInitialPos(CH('Chatot'), 13.5, 20.5, Direction.Right)
    ExplorerEssentials.SetupInitialPos(CH('PLAYER'), 12, 22, Direction.Right) -- player 12, 22
    ExplorerEssentials.SetupInitialPos(CH('PARTNER'), 9, 22, Direction.Right) -- partner 9, 22
	ExplorerEssentials.SetupCameraPos(20.5, 22.5)

	GAME:FadeIn(30)
	SOUND:PlayBGM("011 - Wigglytuff's Guild Remix.ogg", true)
	GAME:WaitFrames(30)

	UI:SetSpeaker(CH('Chatot'))
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Chatot_1']))

    local coro1 = TASK:BranchCoroutine(function ()
        GROUND:MoveToPosition(CH('PLAYER'), 196, 168, false, 2)
        GROUND:CharAnimateTurnTo(CH('PLAYER'), Dir8.Left, 4)
    end)
    local coro2 = TASK:BranchCoroutine(function ()
        GAME:WaitFrames(10)
	    GROUND:MoveToPosition(CH('PARTNER'), 148, 168, false, 2)
        GROUND:CharAnimateTurnTo(CH('PARTNER'), Dir8.Down, 4)
    end)
    TASK:JoinCoroutines({coro1, coro2})
	
	GAME:WaitFrames(20)

    -- i'm guessing this is supoosed to be a hopping animation?
	--[[GROUND:CharSetAnim(CH('PARTNER'), "UNK_3", false)
	-- TODO: MoveHeight<actor ACTOR_ATTENDANT1>(2, 10)
	GAME:WaitFrames(1)
	-- TODO: MoveHeight<actor ACTOR_ATTENDANT1>(2, 0)
	GAME:WaitFrames(2)
	-- TODO: MoveHeight<actor ACTOR_ATTENDANT1>(2, 10)
	GAME:WaitFrames(1)
	-- TODO: MoveHeight<actor ACTOR_ATTENDANT1>(2, 0)
	GROUND:CharSetAnim(CH('PARTNER'), "None", false)]]--
	GROUND:CharSetEmote(CH('PARTNER'), "happy", 1)
    CharacterActions.HopTwice(CH('PARTNER'), CH('PARTNER').Direction)
	
    UI:SetSpeaker(CH('PARTNER'))
	UI:SetSpeakerEmotion("Joyous")
	-- TODO: message_FacePositionOffset(-2, -1)
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_PARTNER_1_'..tostring(pTalkKind)]))

	--GROUND:CharSetEmote(CH('PARTNER'), "none", -1)
	GROUND:CharAnimateTurnTo(CH('PARTNER'), Dir8.UpLeft, 4)
	GROUND:CharTurnToCharAnimated(CH('PLAYER'), CH('Chatot'), 4)
	
    UI:SetSpeaker(CH('Chatot'))
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Chatot_2']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Chatot_3']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Chatot_4']))

	GROUND:MoveToPosition(CH('Chatot'), CH('Chatot').Position.X + -8, CH('Chatot').Position.Y + 8, false, 2)
	
	local coro1 = TASK:BranchCoroutine(function ()
        GROUND:CharAnimateTurnTo(CH('PARTNER'), Dir8.Left, 4)
    end)
    local coro2 = TASK:BranchCoroutine(function ()
        GROUND:MoveToPosition(CH('Chatot'), CH('Chatot').Position.X + -132, CH('Chatot').Position.Y + 0, false, 2)
    end)
	TASK:JoinCoroutines({coro1, coro2})

	GROUND:Hide("Chatot")

    local coro1 = TASK:BranchCoroutine(function ()
        GAME:WaitFrames(30)
        GAME:FadeOut(false, 90)
    end)
    local coro2 = TASK:BranchCoroutine(function ()
        SOUND:FadeOutBGM(120)
    end)
    TASK:JoinCoroutines({coro1, coro2})

    SV.Progression.SectionFlag = 1
    GAME:EnterGroundMap("cutscenes", "guild_bedroom_night", "Entrance", false)
end

function guild_bedroom.CH2_WakeUp()
  --[[
def 0 {
    sound_Stop();
    message_Narration(30, {
        english="[CN]The next morning...",
    });
    message_Close();
    Wait(30);
    se_Play(8971);
    message_ResetActor();
    message_Talk({
        english=" HEY![K] HEY THERE!",
    });
    message_KeyWait();
    se_Play(8970);
    message_Talk({
        english=" RISE AND SHINE!",
    });
    WaitSe(8970);
    CallCommon(CORO_MESSAGE_CLOSE_WAIT_FUNC);
    message_SetFace(ACTOR_PLAYER, FACE_DIZZY, FACE_POS_BOTTOM_R_FACEINW);
    message_SwitchMonologue ($HERO_TALK_KIND) {
        case 4:
            {
                english="(Ugh!)",
            }
        default:
            {
                english="(Ugh!)",
            }
    }
    message_SwitchMonologue ($HERO_TALK_KIND) {
        case 4:
            {
                english="(M-my head is pounding!)",
            }
        default:
            {
                english="(M-my head is pounding!)",
            }
    }
    message_SwitchMonologue ($HERO_TALK_KIND) {
        case 4:
            {
                english="""
                    (Wh-what a ridiculously loud voice! It almost
                    blasted my eardrums!)
                """,
            }
        default:
            {
                english="""
                    (Wh-what a ridiculously loud voice! It almost
                    blasted my eardrums!)
                """,
            }
    }
    message_Close();
    back_SetGround(LEVEL_G01P07A);
    supervision_Acting(0);
    camera_SetMyself<performer 0>();
    SetAnimation<actor ACTOR_PLAYER>(68);
    SetAnimation<actor ACTOR_ATTENDANT1>(68);
    WaitAnimation<actor ACTOR_ATTENDANT1>();
    WaitExecuteLives(ACTOR_ATTENDANT1);
    screen_FadeIn(1, 30);
    Wait(30);
    se_Play(8971);
    camera_SetEffect(2, 2, 3.0);
    SetAnimation<actor ACTOR_NPC_DOGOOMU>(19);
    WaitAnimation<actor ACTOR_NPC_DOGOOMU>();
    SetAnimation<actor ACTOR_NPC_DOGOOMU>(2);
    camera_SetEffect(0, 0, 0);
    SetEffect<actor ACTOR_NPC_DOGOOMU>(EFFECT_ANGRY, 3);
    message_SetFaceOnly(ACTOR_NPC_DOGOOMU, FACE_ANGRY, FACE_POS_TOP_L_FACEINW);
    message_Talk({
        english=" Why are you still ASLEEP?![K] WAKE UP!",
    });
    message_Close();
    SetEffect<actor ACTOR_NPC_DOGOOMU>(EFFECT_NONE, 3);
    message_SetFace(ACTOR_PLAYER, FACE_DIZZY, FACE_POS_BOTTOM_R_FACEINW);
    message_SwitchMonologue ($HERO_TALK_KIND) {
        case 4:
            {
                english="(Ugh!)",
            }
        default:
            {
                english="(Ugh!)",
            }
    }
    CallCommon(CORO_MESSAGE_CLOSE_WAIT_FUNC);
    message_SetFace(ACTOR_ATTENDANT1, FACE_DIZZY, FACE_POS_BOTTOM_C_FACEL);
    message_FacePositionOffset(-3, 0);
    message_SwitchTalk ($PARTNER_TALK_KIND) {
        case 1:
            {
                english=" M-my ears...",
            }
        case 2:
            {
                english=" M-my poor ears...",
            }
        default:
            {
                english=" M-my poor ears...",
            }
    }
    CallCommon(CORO_MESSAGE_CLOSE_WAIT_FUNC);
    se_Play(8971);
    camera_SetEffect(2, 2, 3.0);
    SetAnimation<actor ACTOR_NPC_DOGOOMU>(18);
    WaitAnimation<actor ACTOR_NPC_DOGOOMU>();
    SetAnimation<actor ACTOR_NPC_DOGOOMU>(2);
    camera_SetEffect(0, 0, 0);
    message_SetFaceOnly(ACTOR_NPC_DOGOOMU, FACE_NORMAL, FACE_POS_TOP_L_FACEINW);
    message_Talk({
        english=" C'mon! Snap OUT of it!",
    });
    message_Talk({
        english=" I'm [CS:N]Loudred[CR]![K] And I'm a fellow apprentice!",
    });
    message_SetFace(ACTOR_NPC_DOGOOMU, FACE_NORMAL, FACE_POS_TOP_L_FACEINW);
    message_Talk({
        english="""
             If you're late for our morning
            briefing, you'll be SORRY! So MOVE it!
        """,
    });
    message_Talk({
        english="""
             Guildmaster [CS:N]Wigglytuff[CR] has got
            a BIG temper. If you make him lose it...
        """,
    });
    message_Close();
    Turn2DirectionTurn<actor ACTOR_NPC_DOGOOMU>(4, 10, 5);
    WaitExecuteLives(ACTOR_NPC_DOGOOMU);
    message_SetFace(ACTOR_NPC_DOGOOMU, FACE_NORMAL, FACE_POS_TOP_L_FACEOUTW);
    message_Talk({
        english="""
             YOWEEE! That would be one very
            scary scene!
        """,
    });
    CallCommon(CORO_MESSAGE_CLOSE_WAIT_FUNC);
    se_Play(5143);
    screen_WhiteOut(1, 2);
    Wait(2);
    screen_FadeIn(1, 2);
    Wait(5);
    se_Play(5143);
    screen_WhiteOut(1, 2);
    Wait(2);
    screen_FadeIn(1, 2);
    Wait(30);
    SetAnimation<actor ACTOR_NPC_DOGOOMU>(9);
    message_Talk({
        english="""
             I've got goose bumps just
            thinking about it! YEESH!
        """,
    });
    message_Close();
    SetAnimation<actor ACTOR_NPC_DOGOOMU>(2);
    Wait(45);
    Turn2DirectionTurn<actor ACTOR_NPC_DOGOOMU>(1, 10, 5);
    WaitExecuteLives(ACTOR_NPC_DOGOOMU);
    se_Play(8971);
    camera_SetEffect(2, 2, 3.0);
    SetAnimation<actor ACTOR_NPC_DOGOOMU>(18);
    WaitAnimation<actor ACTOR_NPC_DOGOOMU>();
    WaitExecuteLives(ACTOR_NPC_DOGOOMU);
    SetAnimation<actor ACTOR_NPC_DOGOOMU>(2);
    camera_SetEffect(0, 0, 0);
    message_SetFace(ACTOR_NPC_DOGOOMU, FACE_NORMAL, FACE_POS_TOP_L_FACEINW);
    message_Talk({
        english=" So ANYWAY...",
    });
    message_Talk({
        english="""
             I'm not about to get in trouble
            because you rookies got up LATE!
        """,
    });
    message_Talk({
        english=" SO GET IT IN GEAR!",
    });
    CallCommon(CORO_MESSAGE_CLOSE_WAIT_FUNC);
    MovePositionOffset<actor ACTOR_NPC_DOGOOMU>(1.5, -96, 0);
    WaitExecuteLives(ACTOR_NPC_DOGOOMU);
    Destroy<actor ACTOR_NPC_DOGOOMU>();
    Wait(60);
    message_SetFace(ACTOR_ATTENDANT1, FACE_DIZZY, FACE_POS_STANDARD);
    message_SwitchTalk ($PARTNER_TALK_KIND) {
        case 1:
            {
                english=" Urk! My ears are still ringing...",
            }
        case 2:
            {
                english=" Urk! My ears are still ringing...",
            }
        default:
            {
                english=" Urk! My ears are still ringing...",
            }
    }
    message_SwitchTalk ($PARTNER_TALK_KIND) {
        case 1:
            {
                english="""
                     What did he say? Something
                    about getting ready?
                """,
            }
        case 2:
            {
                english="""
                     What did he say? Something
                    about getting ready?
                """,
            }
        default:
            {
                english="""
                     What did he say? Something
                    about getting ready?
                """,
            }
    }
    message_Close();
    Wait(20);
    SetAnimation<actor ACTOR_PLAYER>(2);
    SetAnimation<actor ACTOR_ATTENDANT1>(2);
    se_Play(8967);
    SetEffect<actor ACTOR_PLAYER>(EFFECT_EXCLAMATION_MARK, 3);
    SetEffect<actor ACTOR_ATTENDANT1>(EFFECT_EXCLAMATION_MARK, 3);
    WaitEffect<actor ACTOR_ATTENDANT1>();
    WaitExecuteLives(ACTOR_ATTENDANT1);
    message_SetFace(ACTOR_ATTENDANT1, FACE_SURPRISED, FACE_POS_STANDARD);
    message_SwitchTalk ($PARTNER_TALK_KIND) {
        case 1:
            {
                english=" Er...[K] Oh yeah!",
            }
        case 2:
            {
                english=" Er...[K] Oh yeah!",
            }
        default:
            {
                english=" Er...[K] Oh yeah!",
            }
    }
    CallCommon(CORO_MESSAGE_CLOSE_WAIT_FUNC);
    Turn2DirectionLives<actor ACTOR_PLAYER>(4, 10, ACTOR_ATTENDANT1);
    Turn2DirectionLives<actor ACTOR_ATTENDANT1>(4, 10, ACTOR_PLAYER);
    WaitExecuteLives(ACTOR_ATTENDANT1);
    message_SetFace(ACTOR_ATTENDANT1, FACE_NORMAL, FACE_POS_STANDARD);
    message_SwitchTalk ($PARTNER_TALK_KIND) {
        case 1:
            {
                english="""
                     We signed up as apprentices at
                    [CS:N]Wigglytuff[CR]'s guild, that's right!
                """,
            }
        case 2:
            {
                english="""
                     We signed up as apprentices at
                    [CS:N]Wigglytuff[CR]'s guild, that's right!
                """,
            }
        default:
            {
                english="""
                     We signed up as apprentices at
                    [CS:N]Wigglytuff[CR]'s guild, that's right!
                """,
            }
    }
    CallCommon(CORO_MESSAGE_CLOSE_WAIT_FUNC);
    message_SetFace(ACTOR_ATTENDANT1, FACE_WORRIED, FACE_POS_STANDARD);
    message_SwitchTalk ($PARTNER_TALK_KIND) {
        case 1:
            {
                english=" But that means...",
            }
        case 2:
            {
                english=" But that means...",
            }
        default:
            {
                english=" But that means...",
            }
    }
    CallCommon(CORO_MESSAGE_CLOSE_WAIT_FUNC);
    se_Play(8974);
    ExecuteCommon<actor ACTOR_ATTENDANT1>(CORO_JUMP_SURPRISE_FUNC_SERIES, 0);
    WaitExecuteLives(ACTOR_ATTENDANT1);
    message_SetFace(ACTOR_ATTENDANT1, FACE_SURPRISED, FACE_POS_STANDARD);
    message_SwitchTalk ($PARTNER_TALK_KIND) {
        case 1:
            {
                english="""
                     Oh no! We totally overslept!
                    Hurry up, [hero]!
                """,
            }
        case 2:
            {
                english="""
                     Waaaah! We totally overslept!
                    We've got to hurry, [hero]!
                """,
            }
        default:
            {
                english="""
                     Waaaah! We overslept!
                    Come on, [hero]!
                """,
            }
    }
    CallCommon(CORO_MESSAGE_CLOSE_WAIT_FUNC);
    MovePositionOffset<actor ACTOR_PLAYER>(3, -180, 0);
    MovePositionOffset<actor ACTOR_ATTENDANT1>(3, -160, 0);
    Wait(45);
    screen_FadeOut(1, 30);
    end;
}
]]--

    AI:DisableCharacterAI(CH('PARTNER'))
	local pTalkKind = SV.Personality.PartnerTalkKind
	SOUND:StopBGM()
    
    UI:SetAutoFinish(true)
    UI:WaitShowVoiceOver(STRINGS:Format(STRINGS.MapStrings['CH2_S2_NARRATION_1']), -1)
	UI:SetAutoFinish(false)

    GAME:WaitFrames(30)

	SOUND:PlayBattleSE("EVT_Emote_Complain_2")
    ExplorerEssentials.SetSpeakerUnknown(nil)
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_S2_Unknown_1']))
	
	SOUND:PlayBattleSE("EVT_Emote_Complain")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_S2_Unknown_2']))

    GROUND:CharSetAction(CH('PLAYER'), RogueEssence.Ground.PoseGroundAction(CH('PLAYER').Position, CH('PLAYER').Direction, RogueEssence.Content.GraphicsManager.GetAnimIndex("Pain")))
    GROUND:CharSetAction(CH('PARTNER'), RogueEssence.Ground.PoseGroundAction(CH('PARTNER').Position, CH('PARTNER').Direction, RogueEssence.Content.GraphicsManager.GetAnimIndex("Pain")))

	ExplorerEssentials.SetSpeakerHero()
	UI:SetSpeakerEmotion("Dizzy")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_S2_PLAYER_1']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_S2_PLAYER_2']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_S2_PLAYER_3']))

    ExplorerEssentials.SetupCameraPos(22, 22.5)
    ExplorerEssentials.SetupInitialPos(CH('PLAYER'), 25, 22, Direction.Down)
    ExplorerEssentials.SetupInitialPos(CH('PARTNER'), 19, 22, Direction.Down)
    ExplorerEssentials.SetupInitialPos(CH('Loudred'), 13.5, 21.5, Direction.Right)

	-- back_SetGround(LEVEL_G01P07A) (Should be the map you're currently on, or the map it sends you to next)
	-- ### supervision_Acting(0) [IRRELEVANT]
	--GAME:MoveCamera(MRKR('PERF_0').Position.X, MRKR('PERF_0').Position.Y, 1, false)
	--GROUND:CharSetAnim(CH('PLAYER'), "UNK_68", false)
	--GROUND:CharSetAnim(CH('PARTNER'), "UNK_68", false)
	-- TODO WaitAnimation: WaitAnimation<actor ACTOR_ATTENDANT1>()

	-- !! WaitExecuteLives(ACTOR_ATTENDANT1)
	
    GAME:FadeIn(30)
	GAME:WaitFrames(30)

	SOUND:PlayBattleSE("EVT_Emote_Complain_2")
    GROUND:MoveScreen(RogueEssence.Content.ScreenMover(2, 2, 80))
	-- TODO: camera_SetEffect(2, 2, 3.0) // camera shake i think
	GROUND:CharWaitAnim(CH('Loudred'), "Hop", false)
	-- TODO: camera_SetEffect(0, 0, 0)

	GROUND:CharSetEmote(CH('Loudred'), "angry", -1)

	ExplorerEssentials.SetSpeakerUnknown(CH('Loudred'))
	UI:SetSpeakerEmotion("Angry")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_S2_Loudred_1']))
	GROUND:CharSetEmote(CH('Loudred'), "none", 1)
	
    ExplorerEssentials.SetSpeakerHero()
	UI:SetSpeakerEmotion("Dizzy")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_S2_PLAYER_4']))
	
    UI:SetSpeaker(CH('PARTNER'))
	UI:SetSpeakerEmotion("Dizzy")
	-- TODO: message_FacePositionOffset(-3, 0)
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_S2_PARTNER_1_'..tostring(pTalkKind)]))
	
    SOUND:PlayBattleSE("EVT_Emote_Complain_2")
    GROUND:MoveScreen(RogueEssence.Content.ScreenMover(2, 2, 80))
	-- TODO: camera_SetEffect(2, 2, 3.0) // camera shake i think
	GROUND:CharWaitAnim(CH('Loudred'), "Hop", false)
	-- TODO: camera_SetEffect(0, 0, 0)
	
    ExplorerEssentials.SetSpeakerUnknown(CH('Loudred'))
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_S2_Loudred_2']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_S2_Loudred_3'], CH('Loudred'):GetDisplayName()))
	
    UI:SetSpeaker(CH('Loudred'))
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_S2_Loudred_4']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_S2_Loudred_5'], CH('Wigglytuff'):GetDisplayName()))
	
    GROUND:CharAnimateTurnTo(CH('Loudred'), Dir8.Left, 5)
	
    UI:SetSpeaker(CH('Loudred'))
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_S2_Loudred_6']))
	
    SOUND:PlayBattleSE("EVT_Battle_Flash")
	GAME:FadeOut(true, 2)
	GAME:WaitFrames(2)
	GAME:FadeIn(2)
	GAME:WaitFrames(5)
	SOUND:PlayBattleSE("EVT_Battle_Flash")
	GAME:FadeOut(true, 2)
	GAME:WaitFrames(2)
	GAME:FadeIn(2)
	GAME:WaitFrames(30)
	
    GROUND:CharSetAnim(CH('Loudred'), "Charge", true)
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_S2_Loudred_7']))
	
    GROUND:CharSetAnim(CH('Loudred'), "None", false)
	GAME:WaitFrames(45)
	GROUND:CharAnimateTurnTo(CH('Loudred'), Dir8.Right, 5)

	SOUND:PlayBattleSE("EVT_Emote_Complain_2")
    GROUND:MoveScreen(RogueEssence.Content.ScreenMover(2, 2, 80))
	-- TODO: camera_SetEffect(2, 2, 3.0) // camera shake i think
	GROUND:CharWaitAnim(CH('Loudred'), "Hop")
	-- TODO: camera_SetEffect(0, 0, 0)
	
    UI:SetSpeaker(CH('Loudred'))
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_S2_Loudred_8']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_S2_Loudred_9']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_S2_Loudred_10']))
	
    GROUND:MoveToPosition(CH('Loudred'), CH('Loudred').Position.X + -96, CH('Loudred').Position.Y + 0, false, 2)
	GROUND:Hide("Loudred")
	GAME:WaitFrames(60)
	
    UI:SetSpeaker(CH('PARTNER'))
	UI:SetSpeakerEmotion("Dizzy")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_S2_PARTNER_2']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_S2_PARTNER_3']))
	GAME:WaitFrames(20)
	
    GROUND:CharEndAnim(CH('PLAYER'))
	GROUND:CharEndAnim(CH('PARTNER'))
	
    SOUND:PlayBattleSE("EVT_Emote_Exclaim_Surprised")
	GROUND:CharSetEmote(CH('PLAYER'), "exclaim", 1)
	GROUND:CharSetEmote(CH('PARTNER'), "exclaim", 1)
	GAME:WaitFrames(30)
	
    UI:SetSpeaker(CH('PARTNER'))
	UI:SetSpeakerEmotion("Surprised")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_S2_PARTNER_4']))
	
    local coro1 = TASK:BranchCoroutine(function () GROUND:CharTurnToCharAnimated(CH('PLAYER'), CH('PARTNER'), 4) end)
	local coro2 = TASK:BranchCoroutine(function () GROUND:CharTurnToCharAnimated(CH('PARTNER'), CH('PLAYER'), 4) end)
	TASK:JoinCoroutines({coro1, coro2})
	
    UI:SetSpeaker(CH('PARTNER'))
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_S2_PARTNER_5'], CH('Wigglytuff'):GetDisplayName()))
	
    UI:SetSpeaker(CH('PARTNER'))
	UI:SetSpeakerEmotion("Worried")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_S2_PARTNER_6']))

	SOUND:PlayBattleSE("EVT_Emote_Startled")
	CharacterActions.ScaredJump(CH('PARTNER'), CH('PARTNER').Direction)
	
    UI:SetSpeaker(CH('PARTNER'))
	UI:SetSpeakerEmotion("Surprised")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_S2_PARTNER_7_'..tostring(pTalkKind)], CH('PLAYER'):GetDisplayName()))

	local coro1 = TASK:BranchCoroutine(function () GROUND:MoveToPosition(CH('PLAYER'), CH('PLAYER').Position.X + -180, CH('PLAYER').Position.Y + 0, true, 6) end)
	local coro2 = TASK:BranchCoroutine(function () GROUND:MoveToPosition(CH('PARTNER'), CH('PARTNER').Position.X + -160, CH('PARTNER').Position.Y + 0, true, 6) end)
    local coro3 = TASK:BranchCoroutine(function ()
        GAME:WaitFrames(45)
	    GAME:FadeOut(false, 30)
    end)
	TASK:JoinCoroutines({coro1, coro2, coro3})

    GAME:EnterGroundMap("guild_basement", "Entrance", true)
end

return guild_bedroom

