--[[
    init.lua
    Created: 01/31/2026 16:08:00
    Description: Autogenerated script file for the map sentry_hole.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local sentry_hole = {}

-------------------------------
-- Map Callbacks
-------------------------------
---sentry_hole.Init(map)
--Engine callback function
function sentry_hole.Init(map)


end

---sentry_hole.Enter(map)
--Engine callback function
function sentry_hole.Enter(map)

  GAME:FadeIn(20)

end

---sentry_hole.Exit(map)
--Engine callback function
function sentry_hole.Exit(map)


end

---sentry_hole.Update(map)
--Engine callback function
function sentry_hole.Update(map)


end

---sentry_hole.GameSave(map)
--Engine callback function
function sentry_hole.GameSave(map)


end

---sentry_hole.GameLoad(map)
--Engine callback function
function sentry_hole.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return sentry_hole

