--[[
    init.lua
    Created: 01/31/2026 16:08:00
    Description: Autogenerated script file for the map sentry_hole.
]]--
-- Commonly included lua functions and data
require 'origin.common'
require 'eos.ExplorerEssentials'

-- Package name
local sentry_hole = {}

-------------------------------
-- Map Callbacks
-------------------------------
---sentry_hole.Init(map)
--Engine callback function
function sentry_hole.Init(map)


end

---sentry_hole.Enter(map)
--Engine callback function
function sentry_hole.Enter(map)

  local diglett = CH("Diglett")
  local player = CH("PLAYER")

  GROUND:Hide("PLAYER")
  GAME:CutsceneMode(true)

  GAME:FadeIn(60)

  GAME:WaitFrames(120)

  GAME:MoveCamera(diglett.Position.X, diglett.Position.Y, 300, false)

  GAME:WaitFrames(30)

  SOUND:PlayBattleSE("EVT_Emote_Sweatdrop")
  GROUND:CharSetEmote(diglett, "sweatdrop", 1)
  GAME:WaitFrames(60)

  UI:SetSpeaker(diglett)
  UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Diglett_1']))

  GROUND:CharAnimateTurnTo(diglett, Direction.Left, 8)

  UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Diglett_2'], _DATA:GetMonster(player.CurrentForm.Species):GetColoredName()))

  ExplorerEssentials.SetSpeakerUnknown(nil)
  UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Unknown_1']))

  SOUND:PlayBattleSE("EVT_Emote_Sweating")
  GROUND:CharSetEmote(diglett, "sweating", 1)
  GAME:WaitFrames(45)

  UI:SetSpeaker(diglett)
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Diglett_3']))

  ExplorerEssentials.SetSpeakerUnknown(nil)
  UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Unknown_2']))
  UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Unknown_3']))
  UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Unknown_4'], diglett:GetDisplayName()))

  SOUND:PlayBattleSE("EVT_Emote_Sweating")
  GROUND:CharSetEmote(diglett, "sweating", 1)
  GAME:WaitFrames(45)

  UI:SetSpeaker(diglett)
  UI:SetSpeakerEmotion("Pain")
  UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Diglett_4']))

  GAME:FadeOut(false, 60)
  GAME:EnterGroundMap('guild_outside_dusk', 'Entrance', false)

end

---sentry_hole.Exit(map)
--Engine callback function
function sentry_hole.Exit(map)


end

---sentry_hole.Update(map)
--Engine callback function
function sentry_hole.Update(map)


end

---sentry_hole.GameSave(map)
--Engine callback function
function sentry_hole.GameSave(map)


end

---sentry_hole.GameLoad(map)
--Engine callback function
function sentry_hole.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return sentry_hole

