--[[
    init.lua
    Created: 10/31/2023 15:01:40
    Description: Autogenerated script file for the map beach.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local beach = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---beach.Init(map)
--Engine callback function
function beach.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---beach.Enter(map)
--Engine callback function
function beach.Enter(map)

  --Normal Entry
  if not SV.beach.Cutscene then
	GAME:FadeIn(20)
	--Handle NPCs based on progression
  else
  --Cutscenes
	--GROUND:AddMapStatus("dusk")
	
	if (SV.Chapter = 1 and SV.SectionFlag = 0) then
		
		local player = CH('PLAYER')

		GAME:CutsceneMode(true)
		GROUND:CharSetAnim(player, "Laying", true)
		
		GAME:WaitFrames(120)
		
        UI:WaitShowDialogue(STRINGS:Format("......"))
		UI:WaitShowDialogue(STRINGS:Format("............"))
		UI:WaitShowDialogue(STRINGS:Format(".................."))
		UI:WaitShowDialogue(STRINGS:Format("Urrgh..."))
    
		GAME:WaitFrames(60)
		
		UI:WaitShowDialogue(STRINGS:Format("Where..."))
		UI:WaitShowDialogue(STRINGS:Format("...Where am I?"))
		
		GAME:FadeIn(120)
		
		UI:SetSpeaker(player)
		UI:SetSpeakerEmotion("Pain")
		
		UI:WaitShowDialogue(STRINGS:Format("...[pause=0]I can\'t...[pause=0] Drifting off..."))
		
		GAME:WaitFrames(30)
		GAME:FadeOut(false, 150)
		GAME:WaitFrames(60)
		
    end
  end
end

---beach.Exit(map)
--Engine callback function
function beach.Exit(map)


end

---beach.Update(map)
--Engine callback function
function beach.Update(map)


end

---beach.GameSave(map)
--Engine callback function
function beach.GameSave(map)


end

---beach.GameLoad(map)
--Engine callback function
function beach.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return beach

