--[[
    init.lua
    Created: 02/03/2026 16:40:53
    Description: Autogenerated script file for the map guild_entrance.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local guild_entrance = {}

-------------------------------
-- Map Callbacks
-------------------------------
---guild_entrance.Init(map)
--Engine callback function
function guild_entrance.Init(map)


end

---guild_entrance.Enter(map)
--Engine callback function
function guild_entrance.Enter(map)

  GAME:FadeIn(20)

end

---guild_entrance.Exit(map)
--Engine callback function
function guild_entrance.Exit(map)


end

---guild_entrance.Update(map)
--Engine callback function
function guild_entrance.Update(map)


end

---guild_entrance.GameSave(map)
--Engine callback function
function guild_entrance.GameSave(map)


end

---guild_entrance.GameLoad(map)
--Engine callback function
function guild_entrance.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return guild_entrance

