--[[
    init.lua
    Created: 02/03/2026 16:40:53
    Description: Autogenerated script file for the map guild_entrance.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local guild_entrance = {}

-------------------------------
-- Map Callbacks
-------------------------------
---guild_entrance.Init(map)
--Engine callback function
function guild_entrance.Init(map)

  COMMON.RespawnStarterPartner()

end

---guild_entrance.Enter(map)
--Engine callback function
function guild_entrance.Enter(map)

  if SV.Progression.Chapter == 2 then
    guild_entrance.CH2_Entrance() -- afaik this is the only ch2 cutscene in this room
  else
    -- No Cutscenes are occurring
    ExplorerEssentials.SpawnPartner()

    GAME:FadeIn(20)

  end

  --GAME:EnterGroundMap("guild_outside", "GuildEntranceMarker") --TEMP

end

---guild_entrance.Exit(map)
--Engine callback function
function guild_entrance.Exit(map)


end

---guild_entrance.Update(map)
--Engine callback function
function guild_entrance.Update(map)


end

---guild_entrance.GameSave(map)
--Engine callback function
function guild_entrance.GameSave(map)


end

---guild_entrance.GameLoad(map)
--Engine callback function
function guild_entrance.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function guild_entrance.Exit_Touch(obj, activator)

  GAME:FadeOut(false, 20)
  GAME:EnterGroundMap("guild_outside", "GuildEntranceMarker")

end

function guild_entrance.F2_Touch(obj, activator)

  --GAME:EnterGroundMap("crossroads_south", "CrossRoadsAssemblyEntranceMarker")

end

function guild_entrance.LeftSign_Action(obj, activator)

end

function guild_entrance.RightSign_Action(obj, activator)

end

-------------------------------
-- Cutscene Functions
-------------------------------

function guild_entrance.CH2_Entrance()

end

return guild_entrance

