--[[
    init.lua
    Created: 06/23/2026 14:29:43
    Description: Autogenerated script file for the map guild_gate_view.
]]--
-- Commonly included lua functions and data
require 'eos.common'
require 'eos.ExplorerEssentials'

-- Package name
local guild_gate_view = {}

-------------------------------
-- Map Callbacks
-------------------------------
---guild_gate_view.Init(map)
--Engine callback function
function guild_gate_view.Init(map)


end

---guild_gate_view.Enter(map)
--Engine callback function
function guild_gate_view.Enter(map)

  GROUND:Hide("PLAYER")
  GAME:MoveCamera(0, 360, 1, false)

  GAME:FadeIn(60)

  GAME:WaitFrames(60)

  ExplorerEssentials.MoveCameraAtSpeed(0, 120, 1, false)

  GAME:WaitFrames(60)

  GAME:FadeOut(false, 60)

end

---guild_gate_view.Exit(map)
--Engine callback function
function guild_gate_view.Exit(map)


end

---guild_gate_view.Update(map)
--Engine callback function
function guild_gate_view.Update(map)


end

---guild_gate_view.GameSave(map)
--Engine callback function
function guild_gate_view.GameSave(map)


end

---guild_gate_view.GameLoad(map)
--Engine callback function
function guild_gate_view.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return guild_gate_view

