--[[
    init.lua
    Created: 09/05/2026 15:33:52
    Description: Autogenerated script file for the map scene_stormclouds.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local scene_stormclouds = {}

-------------------------------
-- Map Callbacks
-------------------------------
---scene_stormclouds.Init(map)
--Engine callback function
function scene_stormclouds.Init(map)


end

---scene_stormclouds.Enter(map)
--Engine callback function
function scene_stormclouds.Enter(map)

  GAME:FadeIn(20)

end

---scene_stormclouds.Exit(map)
--Engine callback function
function scene_stormclouds.Exit(map)


end

---scene_stormclouds.Update(map)
--Engine callback function
function scene_stormclouds.Update(map)


end

---scene_stormclouds.GameSave(map)
--Engine callback function
function scene_stormclouds.GameSave(map)


end

---scene_stormclouds.GameLoad(map)
--Engine callback function
function scene_stormclouds.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

-------------------------------
-- Cutscene Functions
-------------------------------

function DEF_0()
	local hTalkKind = SV.Personality.HeroTalkKind
	local pTalkKind = SV.Personality.PartnerTalkKind
	SOUND:StopBGM()
	GAME:WaitFrames(60)
	-- back_SetGround(LEVEL_V03P05C) (Should be the map you're currently on, or the map it sends you to next)
	-- ### supervision_Acting(0) [IRRELEVANT]
	-- TODO camera_SetPositionMark: camera_SetPositionMark(Position<'m0', 17.5, 17.5>)
	-- TODO SetEffect: SetEffect<performer 3>(EFFECT_VERY_HEAVY_RAIN, 3)
	SOUND:PlayBGM("UNK_BGM_STORM.ogg", true, 160)
	GAME:FadeIn(30)
	GAME:WaitFrames(60)
	SOUND:PlayBattleSE("UNK_6401")
	-- TODO SetAnimation: SetAnimation<object OBJECT_V01P07B1_191>(18)
	-- TODO WaitAnimation: WaitAnimation<object OBJECT_V01P07B1_191>()
	-- TODO: WaitExecuteObject(OBJECT_V01P07B1_191)
	GAME:WaitFrames(120)
	SOUND:FadeOutBGM(120)
	GAME:FadeOut(false, 60)
	-- TODO: WaitBgm(BGM_STORM)
	-- TODO SetEffect: SetEffect<performer 3>(EFFECT_NONE, 3)
end

function DEF_0()
	local hTalkKind = SV.Personality.HeroTalkKind
	local pTalkKind = SV.Personality.PartnerTalkKind
	SOUND:StopBGM()
	-- back_SetGround(LEVEL_V03P05C) (Should be the map you're currently on, or the map it sends you to next)
	-- ### supervision_Acting(0) [IRRELEVANT]
	-- TODO camera_SetPositionMark: camera_SetPositionMark(Position<'m0', 17.5, 17.5>)
	-- TODO SetEffect: SetEffect<performer 3>(EFFECT_VERY_HEAVY_RAIN, 3)
	SOUND:PlayBGM("UNK_BGM_STORM.ogg", true, 120)
	GAME:FadeIn(30)
	GAME:WaitFrames(120)
	-- TODO: screen_WhiteOut(1, 2)
	GAME:WaitFrames(2)
	GAME:FadeIn(2)
	GAME:WaitFrames(10)
	-- TODO: screen_WhiteOut(1, 2)
	GAME:WaitFrames(2)
	GAME:FadeIn(2)
	SOUND:PlayBattleSE("UNK_6424")
	GAME:WaitFrames(120)
	SOUND:FadeOutBGM(120)
	GAME:FadeOut(false, 60)
	-- TODO: WaitBgm(BGM_STORM)
	-- TODO SetEffect: SetEffect<performer 3>(EFFECT_NONE, 3)
end

function DEF_0()
	local hTalkKind = SV.Personality.HeroTalkKind
	local pTalkKind = SV.Personality.PartnerTalkKind
	SOUND:PlayBGM("UNK_BGM_TIME_GEAR_REMIX.ogg", true)
	-- back_SetGround(LEVEL_V03P05C) (Should be the map you're currently on, or the map it sends you to next)
	-- ### supervision_Acting(0) [IRRELEVANT]
	-- TODO camera_SetPositionMark: camera_SetPositionMark(Position<'m0', 17.5, 17.5>)
	-- TODO SetEffect: SetEffect<performer 3>(EFFECT_VERY_HEAVY_RAIN, 3)
	-- TODO: bgm2_PlayFadeIn(BGM_STORM, 60, 256)
	GAME:FadeIn(30)
	GAME:WaitFrames(60)
	SOUND:PlayBattleSE("UNK_6401")
	-- TODO SetAnimation: SetAnimation<object OBJECT_V01P07B1_191>(18)
	-- TODO WaitAnimation: WaitAnimation<object OBJECT_V01P07B1_191>()
	-- TODO: WaitExecuteObject(OBJECT_V01P07B1_191)
	GAME:WaitFrames(60)
	GAME:FadeOut(false, 15)
	-- TODO SetEffect: SetEffect<performer 3>(EFFECT_NONE, 3)
end

return scene_stormclouds

