--[[
    init.lua
    Created: 02/24/2024 15:51:21
    Description: Autogenerated script file for the map drenched_bluff.
]]--
-- Commonly included lua functions and data
require 'eos.common'

-- Package name
local drenched_bluff = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---drenched_bluff.Init(zone)
--Engine callback function
function drenched_bluff.Init(zone)


end

---drenched_bluff.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function drenched_bluff.EnterSegment(zone, rescuing, segmentID, mapID)


end

---drenched_bluff.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function drenched_bluff.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---drenched_bluff.Rescued(zone, name, mail)
--Engine callback function
function drenched_bluff.Rescued(zone, name, mail)


end

return drenched_bluff

