--[[
    init.lua
    Created: 02/24/2024 15:51:21
    Description: Autogenerated script file for the map drenched_bluff.
]]--
-- Commonly included lua functions and data
require 'eos.common'

-- Package name
local drenched_bluff = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---drenched_bluff.Init(zone)
--Engine callback function
function drenched_bluff.Init(zone)


end

---drenched_bluff.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function drenched_bluff.EnterSegment(zone, rescuing, segmentID, mapID)
    if rescuing ~= true then
		COMMON.BeginDungeon(zone.ID, segmentID, mapID)
	end
end

---drenched_bluff.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function drenched_bluff.ExitSegment(zone, result, rescue, segmentID, mapID)
    DEBUG.EnableDbgCoro() --Enable debugging this coroutine
    PrintInfo("=>> ExitSegment_drenched_bluff (Drenched Bluff) result "..tostring(result).." segment "..tostring(segmentID))

	GAME:SetRescueAllowed(false)
	
	SV.Dungeon.Zone = zone
	SV.Dungeon.Result = result
	SV.Dungeon.Rescue = rescue
	SV.Dungeon.SegmentID = segmentID
	SV.Dungeon.MapID = mapID

	if result ~= RogueEssence.Data.GameProgress.ResultType.Cleared then
		SV.drenched_bluff.TimesFailed = SV.drenched_bluff.TimesFailed + 1

		GAME:WaitFrames(20)
		ExplorerEssentials.EndDungeonWithFanfare(result, "hub", -1, 10, 0)
	else
		GAME:WaitFrames(20)
		GAME:EnterZone("drenched_bluff", -1, 1, 0)
	end

end

---drenched_bluff.Rescued(zone, name, mail)
--Engine callback function
function drenched_bluff.Rescued(zone, name, mail)


end

return drenched_bluff

