--[[
    init.lua
    Created: 09/26/2023 13:56:09
    Description: Autogenerated script file for the map intro_cutscene.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local intro_cutscene = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = MapStrings['SomeStringName']
local MapStrings = {}

-------------------------------
-- Map Callbacks
-------------------------------
---intro_cutscene.Init(map)
--Engine callback function
function intro_cutscene.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  MapStrings = COMMON.AutoLoadLocalizedStrings()

end

---intro_cutscene.Enter(map)
--Engine callback function
function intro_cutscene.Enter(map)

  GAME:FadeIn(20)

end

---intro_cutscene.Exit(map)
--Engine callback function
function intro_cutscene.Exit(map)


end

---intro_cutscene.Update(map)
--Engine callback function
function intro_cutscene.Update(map)


end

---intro_cutscene.GameSave(map)
--Engine callback function
function intro_cutscene.GameSave(map)


end

---intro_cutscene.GameLoad(map)
--Engine callback function
function intro_cutscene.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return intro_cutscene

