--[[
    init.lua
    Created: 05/30/2025 16:26:11
    Description: Autogenerated script file for the map krabby_scene_a.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local krabby_scene_a = {}

-------------------------------
-- Map Vars
-------------------------------

local bubbleSpawnTimer = 0
local bigBubbleSpawnTimer = 0
local sinTick = 0
local bubblesSpawned = 0
local bigBubblesSpawned = 0

local bubbleSpawnA = MRKR('KrabbyBubbleSpawnerA')
local bubbleSpawnB = MRKR('KrabbyBubbleSpawnerA')
local bigBubbleSpawn = MRKR('BigBubbleSpawner')

-------------------------------
-- Map Callbacks
-------------------------------
---krabby_scene_a.Init(map)
--Engine callback function
function krabby_scene_a.Init(map)

  
end

---krabby_scene_a.Enter(map)
--Engine callback function
function krabby_scene_a.Enter(map)

  GAME:MoveCamera(160, 120, 1, false)
  GROUND:Hide("PLAYER")

  -- iirc these scenes only show up in chapters 1 and 20 so we're probably fine to just leave it like this

  --krabby 1
	GAME:FadeIn(60)

  local bigBubbleSpawn = MRKR('BigBubbleSpawner')
  local krabbySpawnA = MRKR('KrabbyBubbleSpawnerA')
  local krabbySpawnB = MRKR('KrabbyBubbleSpawnerB')

  local anim_list = luanet.make_array(RogueEssence.Content.AnimData, {
		RogueEssence.Content.AnimData("Ice_Shard_Hit_Sparkle", 120, 1, 1, 255, Dir8.None),
		RogueEssence.Content.AnimData("Ice_Shard_Hit_Sparkle", 120, 2, 2, 255, Dir8.None),
		RogueEssence.Content.AnimData("Ice_Shard_Hit_Sparkle", 120, 3, 3, 255, Dir8.None)
	})
	
	local emitter = RogueEssence.Content.FiniteSprinkleEmitter(anim_list)
	emitter.Layer = RogueEssence.Content.DrawLayer.Front
	emitter.Range = 50
	emitter.Speed = 80
	emitter.HeightSpeed = -120
	emitter.SpeedDiff = 120
	emitter.TotalParticles = 25
	
	GROUND:PlayVFX(emitter, krabbySpawnB.Bounds.Center.X, krabbySpawnB.Bounds.Center.Y)

	GAME:WaitFrames(120)
	GAME:FadeOut(false, 60)

  GAME:EnterGroundMap("krabby_scene_b", "Entrance")

end

---krabby_scene_a.Exit(map)
--Engine callback function
function krabby_scene_a.Exit(map)


end

---krabby_scene_a.Update(map)
--Engine callback function
function krabby_scene_a.Update(map)

end

---krabby_scene_a.GameSave(map)
--Engine callback function
function krabby_scene_a.GameSave(map)


end

---krabby_scene_a.GameLoad(map)
--Engine callback function
function krabby_scene_a.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return krabby_scene_a

