--[[
    init.lua
    Created: 02/04/2026 12:46:26
    Description: Autogenerated script file for the map guild_bedroom_night.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local guild_bedroom_night = {}

-------------------------------
-- Map Callbacks
-------------------------------
---guild_bedroom_night.Init(map)
--Engine callback function
function guild_bedroom_night.Init(map)


end

---guild_bedroom_night.Enter(map)
--Engine callback function
function guild_bedroom_night.Enter(map)

  GAME:FadeIn(20)

end

---guild_bedroom_night.Exit(map)
--Engine callback function
function guild_bedroom_night.Exit(map)


end

---guild_bedroom_night.Update(map)
--Engine callback function
function guild_bedroom_night.Update(map)


end

---guild_bedroom_night.GameSave(map)
--Engine callback function
function guild_bedroom_night.GameSave(map)


end

---guild_bedroom_night.GameLoad(map)
--Engine callback function
function guild_bedroom_night.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

-------------------------------
-- Cutscene Functions
-------------------------------

function guild_bedroom_night.COMMON_GoToSleep()
  --[[
  
def 0 {
    sound_Stop();
    back_SetGround(LEVEL_G01P07C);
    supervision_Acting(0);
    camera_SetMyself<performer 0>();
    screen_FadeIn(1, 30);
    bgm_PlayFadeIn(BGM_GOODNIGHT, 0, 256);
    Wait(30);
    message_SetFace(ACTOR_ATTENDANT1, FACE_NORMAL, FACE_POS_STANDARD);
    message_SwitchTalk ($PARTNER_TALK_KIND) {
        case 1:
            {
                english=" We should get some sleep too.",
            }
        case 2:
            {
                english=" We should get some sleep too.",
            }
        default:
            {
                english=" We should get some sleep too.",
            }
    }
    message_SwitchTalk ($PARTNER_TALK_KIND) {
        case 1:
            {
                english="""
                     Let's make tomorrow another
                    good day, [hero]!
                """,
            }
        case 2:
            {
                english="""
                     Let's make tomorrow another
                    good day, [hero]!
                """,
            }
        default:
            {
                english="""
                     Let's make tomorrow another
                    good day, [hero]!
                """,
            }
    }
    message_SwitchTalk ($PARTNER_TALK_KIND) {
        case 1:
            {
                english=" All right, good night.",
            }
        case 2:
            {
                english=" OK, good night.",
            }
        default:
            {
                english=" OK, good night.",
            }
    }
    message_Close();
    bgm_FadeOut(120);
    screen_FadeOut(1, 60);
    WaitBgm(BGM_GOODNIGHT);
    end;
}

  ]]--
  
end

function guild_bedroom_night.CH2_FirstNight()
  --[[

def 0 {
    sound_Stop();
    if ( $SCENARIO_MAIN_BIT_FLAG[8] ) {
        @label_0;
        $SCENARIO_MAIN_BIT_FLAG[8] = 0;
        Wait(30);
        me_Play(7);
        message_Explanation({
            english="""
                [CN]Exploration Team
                [CN]Quick Tip[W:30]
            """,
        });
        CallCommon(CORO_MESSAGE_CLOSE_WAIT_FUNC);
        message_Explanation({
            english="""
                [CN]You can save a record of your progress
                [CN]by climbing onto your bed from now on.
            """,
        });
        message_Explanation({
            english="""
                [CN]So whenever you want to save your
                [CN]progress, just climb onto your bed.
            """,
        });
        message_Close();
        Wait(60);
        end;
    } else {
        back2_SetMode(4);
        back2_SetGround(LEVEL_V02P06A);
        camera2_SetPositionMark(Position<'m0', 19.5, 15.5>);
        screen2_FadeIn(1, 60);
        Wait(150);
        screen2_FadeOut(1, 60);
        back2_SetMode(0);
        back_SetGround(LEVEL_G01P07C);
        supervision_Acting(0);
        camera_SetMyself<performer 0>();
        SetAnimation<actor ACTOR_PLAYER>(76);
        SetAnimation<actor ACTOR_ATTENDANT1>(76);
        screen_FadeChange(1, 60, 0, 192);
        bgm_PlayFadeIn(BGM_GOODNIGHT, 0, 256);
        Wait(30);
        message_SetActor(ACTOR_ATTENDANT1);
        message_SwitchTalk ($PARTNER_TALK_KIND) {
            case 1:
                {
                    english=" ...",
                }
            case 2:
                {
                    english=" ...",
                }
            default:
                {
                    english=" ...",
                }
        }
        message_SwitchTalk ($PARTNER_TALK_KIND) {
            case 1:
                {
                    english=" ......",
                }
            case 2:
                {
                    english=" ......",
                }
            default:
                {
                    english=" ......",
                }
        }
        message_SwitchTalk ($PARTNER_TALK_KIND) {
            case 1:
                {
                    english="""
                         Hey, are you still awake,
                        [hero]?
                    """,
                }
            case 2:
                {
                    english="""
                         Oh, are you still awake,
                        [hero]?
                    """,
                }
            default:
                {
                    english="""
                         Say, are you still awake,
                        [hero]?
                    """,
                }
        }
        CallCommon(CORO_MESSAGE_CLOSE_WAIT_FUNC);
        message_SwitchTalk ($PARTNER_TALK_KIND) {
            case 1:
                {
                    english="""
                         My heart's been pounding over
                        every little thing today...
                    """,
                }
            case 2:
                {
                    english="""
                         My heart's been racing all
                        day today over every little thing...
                    """,
                }
            default:
                {
                    english=" My heart's been racing all day...",
                }
        }
        message_SwitchTalk ($PARTNER_TALK_KIND) {
            case 1:
                {
                    english="""
                         But I'm glad I finally worked up
                        the courage to come here.
                    """,
                }
            case 2:
                {
                    english="""
                         But I'm glad I finally made
                        myself come here.
                    """,
                }
            default:
                {
                    english="""
                         But I'm glad I finally forced
                        myself to come here.
                    """,
                }
        }
        message_SwitchTalk ($PARTNER_TALK_KIND) {
            case 1:
                {
                    english="""
                         I thought [CS:N]Wigglytuff[CR] would be
                        a lot scarier, but he seems pretty nice.
                    """,
                }
            case 2:
                {
                    english="""
                         I thought [CS:N]Wigglytuff[CR] would be
                        scary, but he seems pretty friendly.
                    """,
                }
            default:
                {
                    english="""
                         I thought [CS:N]Wigglytuff[CR] would be
                        kind of scary, but he was pretty nice.
                    """,
                }
        }
        message_SwitchTalk ($PARTNER_TALK_KIND) {
            case 1:
                {
                    english="""
                         Even though tomorrow has all
                        sorts of new stuff in store for us, I'm not
                        scared at all!
                    """,
                }
            case 2:
                {
                    english="""
                         We're going to experience all
                        sorts of things starting tomorrow, but I'm not
                        very scared.
                    """,
                }
            default:
                {
                    english="""
                         We'll experience all sorts of
                        new stuff starting tomorrow, but I'm not
                        very frightened.
                    """,
                }
        }
        message_SwitchTalk ($PARTNER_TALK_KIND) {
            case 1:
                {
                    english="""
                         Actually, I'm excited about the
                        new adventures we'll face!
                    """,
                }
            case 2:
                {
                    english="""
                         In fact, it's the other way
                        around. I'm super excited about the adventures
                        we'll face!
                    """,
                }
            default:
                {
                    english="""
                         Actually, I can't wait to find
                        out what new adventures are in store for us!
                    """,
                }
        }
        CallCommon(CORO_MESSAGE_CLOSE_WAIT_FUNC);
        message_SwitchTalk ($PARTNER_TALK_KIND) {
            case 1:
                {
                    english=" Yawn... I'm getting sleepy...",
                }
            case 2:
                {
                    english=" I'm feeling a little sleepy...",
                }
            default:
                {
                    english=" I'm getting a little sleepy...",
                }
        }
        message_SwitchTalk ($PARTNER_TALK_KIND) {
            case 1:
                {
                    english=" Let's do our best tomorrow.",
                }
            case 2:
                {
                    english=" Let's give it our all tomorrow.",
                }
            default:
                {
                    english=" Let's give it our all tomorrow.",
                }
        }
        message_SwitchTalk ($PARTNER_TALK_KIND) {
            case 1:
                {
                    english="""
                         All right then. Good night,
                        [hero]...
                    """,
                }
            case 2:
                {
                    english=" OK, [hero]. Good night.",
                }
            default:
                {
                    english=" OK, [hero]. Sleep tight.",
                }
        }
        CallCommon(CORO_MESSAGE_CLOSE_WAIT_FUNC);
        SetAnimation<actor ACTOR_ATTENDANT1>(62);
        Wait(90);
        bgm_FadeOut(120);
        message_EmptyActor();
        message_SwitchMonologue ($HERO_TALK_KIND) {
            case 4:
                {
                    english="(Um...)",
                }
            default:
                {
                    english="(Um...)",
                }
        }
        message_SwitchMonologue ($HERO_TALK_KIND) {
            case 4:
                {
                    english="(Now I'm suddenly apprenticing at the guild...)",
                }
            default:
                {
                    english="(Now I'm suddenly apprenticing at the guild...)",
                }
        }
        message_SwitchMonologue ($HERO_TALK_KIND) {
            case 4:
                {
                    english="""
                        (I gotta admit, it's pretty exciting to be in an
                        exploration team.)
                    """,
                }
            default:
                {
                    english="""
                        (I gotta admit, it's pretty exciting to be in an
                        exploration team.)
                    """,
                }
        }
        message_SwitchMonologue ($HERO_TALK_KIND) {
            case 4:
                {
                    english="""
                        (And it's fun to be friends with
                        [partner]...)
                    """,
                }
            default:
                {
                    english="""
                        (And it's fun to be friends with
                        [partner]...)
                    """,
                }
        }
        message_SwitchMonologue ($HERO_TALK_KIND) {
            case 4:
                {
                    english="(But first things first...)",
                }
            default:
                {
                    english="(But first things first...)",
                }
        }
        message_SwitchMonologue ($HERO_TALK_KIND) {
            case 4:
                {
                    english="(Who am I?)",
                }
            default:
                {
                    english="(Who am I?)",
                }
        }
        message_SwitchMonologue ($HERO_TALK_KIND) {
            case 4:
                {
                    english="(How did I turn into a Pokémon?)",
                }
            default:
                {
                    english="(How did I turn into a Pokémon?)",
                }
        }
        message_SwitchMonologue ($HERO_TALK_KIND) {
            case 4:
                {
                    english="(How did I end up unconscious on that beach?)",
                }
            default:
                {
                    english="(How did I end up unconscious on that beach?)",
                }
        }
        message_SwitchMonologue ($HERO_TALK_KIND) {
            case 4:
                {
                    english="(I'm feeling sleepy too...)",
                }
            default:
                {
                    english="(I'm feeling sleepy too...)",
                }
        }
        message_SwitchMonologue ($HERO_TALK_KIND) {
            case 4:
                {
                    english="""
                        (Well, thinking about it won't help right now.
                        I'd better focus on the guild's work for now...)
                    """,
                }
            default:
                {
                    english="""
                        (Well, thinking about it won't help right now.
                        I'd better focus on the guild's work for now...)
                    """,
                }
        }
        message_SwitchMonologue ($HERO_TALK_KIND) {
            case 4:
                {
                    english="""
                        (If I do that, well, everything should become
                        clear eventually...)
                    """,
                }
            default:
                {
                    english="""
                        (If I do that, well, everything should become
                        clear eventually...)
                    """,
                }
        }
        message_SwitchMonologue ($HERO_TALK_KIND) {
            case 4:
                {
                    english="(I'll surely get to the bottom of this in time.)",
                }
            default:
                {
                    english="(I'll surely get to the bottom of this in time.)",
                }
        }
        message_Close();
        Wait(30);
        SetAnimation<actor ACTOR_PLAYER>(62);
        Wait(120);
        screen_FadeOut(1, 120);
        Wait(60);
        $SCENARIO_MAIN_BIT_FLAG[8] = 1;
        $COMPULSORY_SAVE_POINT = 1;
        CallCommon(CORO_HANYOU_SAVE_FUNC);
        jump @label_0;
    }
}

]]--
end

function guild_bedroom_night.CH2_OfferHelp()
  --[[
  
def 0 {
    sound_Stop();
    back_SetGround(LEVEL_G01P07C);
    supervision_Acting(0);
    camera_SetMyself<performer 0>();
    screen_FadeIn(1, 30);
    Wait(30);
    message_SetFace(ACTOR_ATTENDANT1, FACE_NORMAL, FACE_POS_STANDARD);
    message_SwitchTalk ($PARTNER_TALK_KIND) {
        case 1:
            {
                english=" Let's get some sleep.",
            }
        case 2:
            {
                english=" We should get some sleep.",
            }
        default:
            {
                english=" Why don't we get some sleep?",
            }
    }
    CallCommon(CORO_MESSAGE_CLOSE_WAIT_FUNC);
    supervision_Acting(1);
    Wait(1);
    MovePositionMark<actor ACTOR_NPC_PERAPPU>(1.1992, Position<'m0', 14, 23>);
    Wait(20);
    se_Play(8978);
    SetEffect<actor ACTOR_PLAYER>(EFFECT_TWO_ARROWS_AT_SIDE_LEFT, 3);
    WaitExecuteLives(ACTOR_NPC_PERAPPU);
    message_SetFace(ACTOR_NPC_PERAPPU, FACE_NORMAL, FACE_POS_TOP_L_FACEINW);
    message_Talk({
        english=" Hey, beginners!",
    });
    CallCommon(CORO_MESSAGE_CLOSE_WAIT_FUNC);
    se_Play(8964);
    SetEffect<actor ACTOR_ATTENDANT1>(EFFECT_EXCLAMATION_MARK, 3);
    WaitEffect<actor ACTOR_ATTENDANT1>();
    WaitExecuteLives(ACTOR_ATTENDANT1);
    Turn2Direction<actor ACTOR_ATTENDANT1>(4, 10, DIR_LEFT);
    message_Talk({
        english="""
             Before you go to bed, our
            Guildmaster wants to speak with you.
        """,
    });
    message_Close();
    screen_FadeOut(1, 30);
    end;
}

  ]]--  
end

return guild_bedroom_night

