--[[
    init.lua
    Created: 02/04/2026 14:50:50
    Description: Autogenerated script file for the map guild_dining_hall.
]]--
-- Commonly included lua functions and data
require 'eos.common'

-- Package name
local guild_dining_hall = {}

-------------------------------
-- Map Callbacks
-------------------------------
---guild_dining_hall.Init(map)
--Engine callback function
function guild_dining_hall.Init(map)


end

---guild_dining_hall.Enter(map)
--Engine callback function
function guild_dining_hall.Enter(map)

  GAME:FadeIn(20)

end

---guild_dining_hall.Exit(map)
--Engine callback function
function guild_dining_hall.Exit(map)


end

---guild_dining_hall.Update(map)
--Engine callback function
function guild_dining_hall.Update(map)


end

---guild_dining_hall.GameSave(map)
--Engine callback function
function guild_dining_hall.GameSave(map)


end

---guild_dining_hall.GameLoad(map)
--Engine callback function
function guild_dining_hall.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------


return guild_dining_hall

