--[[
    init.lua
    Created: 02/03/2026 20:09:12
    Description: Autogenerated script file for the map guild_guildmaster_chambers.
]] --
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local guild_guildmaster_chambers = {}

-------------------------------
-- Map Callbacks
-------------------------------
---guild_guildmaster_chambers.Init(map)
--Engine callback function
function guild_guildmaster_chambers.Init(map)

end

---guild_guildmaster_chambers.Enter(map)
--Engine callback function
function guild_guildmaster_chambers.Enter(map)
    GAME:FadeIn(20)
end

---guild_guildmaster_chambers.Exit(map)
--Engine callback function
function guild_guildmaster_chambers.Exit(map)

end

---guild_guildmaster_chambers.Update(map)
--Engine callback function
function guild_guildmaster_chambers.Update(map)

end

---guild_guildmaster_chambers.GameSave(map)
--Engine callback function
function guild_guildmaster_chambers.GameSave(map)

end

---guild_guildmaster_chambers.GameLoad(map)
--Engine callback function
function guild_guildmaster_chambers.GameLoad(map)
    GAME:FadeIn(20)
end

-------------------------------
-- Entities Callbacks
-------------------------------

-------------------------------
-- Cutscene Functions
-------------------------------

function guild_guildmaster_chambers.CH2_FormingTeam()

    local hTalkKind = SV.Personality.HeroTalkKind
    local pTalkKind = SV.Personality.PartnerTalkKind
    -- back_SetGround(LEVEL_G01P05A) (Should be the map you're currently on, or the map it sends you to next)
    -- ### supervision_Acting(0) [IRRELEVANT]
    GAME:MoveCamera(MRKR('PERF_0').Position.X, MRKR('PERF_0').Position.Y, 1, false)
    GAME:FadeIn(30)
    GAME:WaitFrames(30)

    UI:SetSpeaker(CH('Chatot'))
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Chatot_1']))

    GAME:WaitFrames(60)

    SOUND:PlayBattleSE("EVT_Emote_Exclaim")
    GROUND:CharSetEmote(CH('Chatot'), "notice", 1)
    GAME:WaitFrames(30)

    GAME:WaitFrames(30)
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Chatot_2']))
    
    GAME:WaitFrames(60)
    GROUND:CharAnimateTurnTo(CH('Wigglytuff'), Dir8.Down, 0)
    -- !! WaitExecuteLives(ACTOR_NPC_PUKURIN)

    local coro1 = TASK:BranchCoroutine(function ()
        SOUND:PlayBattleSE("EVT_Emote_Startled")
        CharacterActions.ScaredJump(CH('PARTNER'), CH('PARTNER').Direction)
    end)
    local coro2 = TASK:BranchCoroutine(function ()
        GROUND:CharSetEmote(CH('PLAYER'), "exclaim", 1)
    end)
    local coro3 = TASK:BranchCoroutine(function ()
        SOUND:PlayBGM("009 - Guildmaster Wigglytuff.ogg")
        UI:SetSpeaker(CH('Wigglytuff'))
        UI:SetSpeakerEmotion("Normal")
        UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Wigglytuff_1']))
    end)
    TASK:JoinCoroutines({coro1, coro2, coro3})
    
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Wigglytuff_2'], CH('Wigglytuff'):GetDisplayName()))
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Wigglytuff_3']))
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Wigglytuff_4']))
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Wigglytuff_5']))
    
    SOUND:PlayBattleSE("EVT_Emote_Sweating")
    GROUND:CharSetEmote(CH('PARTNER'), "sweating", 1)
    GAME:WaitFrames(30)

    UI:SetSpeaker(CH('PARTNER'))
    UI:SetSpeakerEmotion("Surprised")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_PARTNER_1_' .. tostring(pTalkKind)]))

    UI:SetSpeaker(CH('PARTNER'))
    UI:SetSpeakerEmotion("Worried")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_PARTNER_2_' .. tostring(pTalkKind)]))
    
    GROUND:CharTurnToCharAnimated(CH('PARTNER'), CH('PLAYER'), 4)
    -- !! WaitExecuteLives(ACTOR_ATTENDANT1)

    local coro1 = TASK:BranchCoroutine(function ()
        GROUND:CharTurnToCharAnimated(CH('PLAYER'), CH('PARTNER'), 4)
    end)
    local coro2 = TASK:BranchCoroutine(function ()
        GROUND:CharAnimateTurnTo(CH('Chatot'), Dir8.DownLeft, 4)
    end)
    local coro3 = TASK:BranchCoroutine(function ()
        UI:SetSpeaker(CH('PARTNER'))
        UI:SetSpeakerEmotion("Normal")
        UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_PARTNER_3_' .. tostring(pTalkKind)], CH('PLAYER'):GetDisplayName()))
    end)
    TASK:JoinCoroutines({coro1, coro2, coro3})

    -- TEAM NAME STUFF
    UI:ResetSpeaker()
	local ch = false
	local name = ""
	while not ch do
		name = ""
		while name == "" do
            UI:NameMenu(STRINGS:Format(STRINGS.MapStrings['TEAM_NAME_PROMPT']), "")
            UI:WaitForChoice()
            name = UI:ChoiceResult()
		end
		
		GAME:SetTeamName(name)
		UI:ChoiceMenuYesNo(STRINGS:Format(STRINGS.MapStrings['TEAM_NAME_CONFIRM'], GAME:GetTeamName()), true)
		UI:WaitForChoice()
		ch = UI:ChoiceResult()
	end

    SOUND:PlayBattleSE("EVT_Emote_Exclaim_Idea")
    GROUND:CharSetEmote(CH('PARTNER'), "exclaim", 1)
    GAME:WaitFrames(30)

    UI:SetSpeaker(CH('PARTNER'))
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_PARTNER_4'], GAME:GetTeamName()))

    GROUND:CharWaitAnim(CH('PARTNER'), "UNK_71")
    GROUND:CharWaitAnim(CH('PARTNER'), "UNK_71")

    UI:SetSpeaker(CH('PARTNER'))
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_PARTNER_5_' .. tostring(pTalkKind)]))

    GROUND:CharAnimateTurnTo(CH('PLAYER'), Dir8.Up, 4)
    GROUND:CharAnimateTurnTo(CH('PARTNER'), Dir8.Up, 4)
    GROUND:CharAnimateTurnTo(CH('Chatot'), Dir8.UpLeft, 4)
    
    UI:SetSpeaker(CH('Wigglytuff'))
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Wigglytuff_6']))
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Wigglytuff_7']))
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Wigglytuff_8']))
    UI:SetSpeakerEmotion("UNK_FACE_SIGH")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Wigglytuff_9']))
    GROUND:CharWaitAnim(CH('Wigglytuff'), "UNK_17")
    
    SOUND:StopBGM()
    
    SOUND:PlayBattleSE("EVT_Battle_Flash")
    GAME:FadeOut(true, 2)
    GAME:WaitFrames(2)
    GAME:FadeIn(2)

    GAME:WaitFrames(5)
    SOUND:PlayBattleSE("EVT_Battle_Flash")
    GAME:FadeOut(true, 2)
    GAME:WaitFrames(2)
    GAME:FadeIn(2)

    -- !! WaitExecuteLives(ACTOR_NPC_PUKURIN)

    SOUND:PlayBGM("008 - Wigglytuff's Guild.ogg")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Wigglytuff_10']))
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Wigglytuff_11']))
    GROUND:MoveToPosition(CH('Wigglytuff'), CH('Wigglytuff').Position.X + 0, CH('Wigglytuff').Position.Y + 16, false, 0)
    -- !! WaitExecuteLives(ACTOR_NPC_PUKURIN)

    GROUND:CharAnimateTurnTo(CH('Chatot'), Dir8.Left, 4)
    SOUND:PlayBattleSE("EVT_CH02_Item_Place")
    -- ### supervision_Acting(1) [IRRELEVANT]
    -- TODO: $PERFORMANCE_PROGRESS_LIST[2] = 1
    GAME:WaitFrames(30)

    UI:SetCenter(true)
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_NARRATION_1'], CH('Wigglytuff'):GetDisplayName()))
    UI:SetCenter(false)

    GROUND:CharSetAnim(CH('Wigglytuff'), "Walk", false)
    -- TODO SlidePositionOffset: SlidePositionOffset<actor ACTOR_NPC_PUKURIN>(0.7969, 0, -16)
    -- !! WaitExecuteLives(ACTOR_NPC_PUKURIN)
    GROUND:CharSetAnim(CH('Wigglytuff'), "None", false)
    
    SOUND:PlayBattleSE("EVT_Emote_Confused")
    GROUND:CharSetEmote(CH('PARTNER'), "question", 1)
    GAME:WaitFrames(30)
    
    UI:SetSpeaker(CH('PARTNER'))
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_PARTNER_6']))
    
    UI:SetSpeaker(CH('Wigglytuff'))
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Wigglytuff_12']))
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Wigglytuff_13']))
    
    GROUND:MoveToPosition(CH('PARTNER'), CH('PARTNER').Position.X + 0, CH('PARTNER').Position.Y + -12, false, 2)
    GAME:WaitFrames(10)
    GROUND:MoveToPosition(CH('PLAYER'), CH('PLAYER').Position.X + 0, CH('PLAYER').Position.Y + -12, false, 2)
    -- !! WaitExecuteLives(ACTOR_ATTENDANT1)
    GROUND:CharAnimateTurnTo(CH('PARTNER'), Dir8.UpRight, 4)
    -- !! WaitExecuteLives(ACTOR_PLAYER)
    GROUND:CharAnimateTurnTo(CH('PLAYER'), Dir8.UpLeft, 4)
    -- !! WaitExecuteLives(ACTOR_PLAYER)
    GAME:WaitFrames(15)

    -- open box
    SOUND:PlayBattleSE("EVT_CH02_Box_Open")
    -- TODO SetAnimation: SetAnimation<object OBJECT_G01P05A1_106>(18)
    -- TODO WaitAnimation: WaitAnimation<object OBJECT_G01P05A1_106>()
    -- TODO: WaitExecuteObject(OBJECT_G01P05A1_106)

    GAME:WaitFrames(30)

    UI:SetCenter(true)
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_NARRATION_2']))

    GAME:FadeOut(false, 30)
    GAME:WaitFrames(10)
    -- back_SetGround(LEVEL_V02P08A) (Should be the map you're currently on, or the map it sends you to next)
    -- ### supervision_RemoveActing(0) [IRRELEVANT]
    -- ### supervision_Acting(2) [IRRELEVANT]
    GAME:MoveCamera(MRKR('PERF_0').Position.X, MRKR('PERF_0').Position.Y, 1, false)
    GAME:FadeIn(30)

    GAME:WaitFrames(30)
    SOUND:PlayFanfare("Fanfare/Item.ogg")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_NARRATION_3']))
    
    SOUND:PlayFanfare("Fanfare/Item.ogg")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_NARRATION_4']))

    SOUND:PlayFanfare("Fanfare/Item.ogg")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_NARRATION_5']))
    UI:SetCenter(false)

    UI:SetSpeaker(CH('PARTNER'))
    UI:SetSpeakerEmotion("Inspired")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_PARTNER_7_' .. tostring(pTalkKind)]))

    UI:SetSpeaker(CH('Wigglytuff'))
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Wigglytuff_14']))
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Wigglytuff_15']))
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Wigglytuff_16']))
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Wigglytuff_17']))
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Wigglytuff_18']))
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Wigglytuff_19']))

    GAME:FadeOut(false, 30)
    -- ### supervision_RemoveActing(2) [IRRELEVANT]
    -- back_SetGround(LEVEL_G01P05A) (Should be the map you're currently on, or the map it sends you to next)
    -- ### supervision_Acting(3) [IRRELEVANT]
    
    GAME:MoveCamera(MRKR('PERF_0').Position.X, MRKR('PERF_0').Position.Y, 1, false)
    -- TODO SetAnimation: SetAnimation<object OBJECT_G01P05A1_106>(18)
    -- TODO WaitAnimation: WaitAnimation<object OBJECT_G01P05A1_106>()
    -- TODO: WaitExecuteObject(OBJECT_G01P05A1_106)

    GAME:FadeIn(30)
    GAME:WaitFrames(30)

    UI:SetCenter(true)
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_NARRATION_6']))
    
    -- GIVE ITEM BASED ON HERO SPECIES
    local gifts = {
        ["bulbasaur"] = "held_power_band",
        ["charmander"] = "held_special_band",
        ["squirtle"] = "held_zinc_band",
        ["pikachu"] = "held_zinc_band",
        ["meowth"] = "held_zinc_band",
        ["vulpix"] = "held_special_band",
        ["eevee"] = "held_zinc_band",
        ["chikorita"] = "held_power_band",
        ["cyndaquil"] = "held_defense_scarf",
        ["totodile"] = "held_joy_ribbon",
        ["phanpy"] = "held_power_band",
        ["treecko"] = "held_power_band",
        ["torchic"] = "held_defense_scarf",
        ["mudkip"] = "held_joy_ribbon",
        ["skitty"] = "held_special_band",
        ["turtwig"] = "held_special_band",
        ["chimchar"] = "held_defense_scarf",
        ["piplup"] = "held_joy_ribbon",
        ["shinx"] = "held_zinc_band",
        ["munchlax"] = "held_special_band",
        ["riolu"] = "held_defense_scarf"
    }

    --[[
        Backup gifts, use smallest stat as a baseline
        ATK -> Power Band
        DEF -> Def. Scarf
        HP -> Joy Ribbon
        SP.ATK -> Special Band
        SP.DEF -> Zinc Band
    ]]--

    local gift = gifts[SV.General.Starter.Species]
    if gift == nil then
        local hp = SV.General.Starter.CurrentForm:ReverseGetStat(RogueEssence.Data.Stat.HP)
        local atk = SV.General.Starter.CurrentForm:ReverseGetStat(RogueEssence.Data.Stat.Attack)
        local def = SV.General.Starter.CurrentForm:ReverseGetStat(RogueEssence.Data.Stat.Defense)
        local spatk = SV.General.Starter.CurrentForm:ReverseGetStat(RogueEssence.Data.Stat.MAtk)
        local spdef = SV.General.Starter.CurrentForm:ReverseGetStat(RogueEssence.Data.Stat.MDef)

        local lowest = 1
        local comp = {hp, atk, def, spatk, spdef}
        for i in #comp do
            if comp[i] < comp[lowest] then
                lowest = i
            end
        end

        local items = {"held_joy_ribbon", "held_power_band", "held_defense_scarf", "held_special_band", "held_zinc_band"}
        gift = items[lowest]
    end
    GAME:GivePlayerItem(gift)

    SOUND:PlayFanfare("Fanfare/Item.ogg")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_NARRATION_7'], RogueEssence.Dungeon.InvItem(gift):GetDisplayName()))
    
    -- GIVE AURA BOW
    local bows = {
		"bow_silver",
		"bow_brown",
		"bow_red",
		"bow_pink",
		"bow_orange",
		"bow_yellow",
		"bow_lime",
		"bow_green",
		"bow_viridian",
		"bow_minty",
		"bow_sky_blue",
		"bow_blue",
		"bow_cobalt",
		"bow_purple",
		"bow_violet",
		"bow_fuchsia"
	}
    local aura_bow = bows[SV.PlayerInputs.AuraColor + 1]
    GAME:GivePlayerItem(aura_bow)

    SOUND:PlayFanfare("Fanfare/Item.ogg")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_NARRATION_8'], RogueEssence.Dungeon.InvItem(aura_bow):GetDisplayName()))
    UI:SetCenter(false)
    
    GAME:WaitFrames(20)
    UI:SetSpeaker(CH('Wigglytuff'))
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Wigglytuff_20']))
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Wigglytuff_21']))
    
    GROUND:CharAnimateTurnTo(CH('PARTNER'), Dir8.Up, 4)
    GROUND:CharAnimateTurnTo(CH('PLAYER'), Dir8.Up, 4)

    local coro1 = TASK:BranchCoroutine(function ()
        CharacterActions.HopTwice(CH('PARTNER'), CH('PARTNER').Direction)
    end)
    local coro2 = TASK:BranchCoroutine(function ()
        UI:SetSpeaker(CH('PARTNER'))
        UI:SetSpeakerEmotion("Inspired")
        UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_PARTNER_8']))
    end)
    TASK:JoinCoroutines({coro1, coro2})
    
    UI:SetSpeaker(CH('Wigglytuff'))
    UI:SetSpeakerEmotion("Normal")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Wigglytuff_22']))

    local coro1 = TASK:BranchCoroutine(function ()
        CharacterActions.HopOnce(CH('PARTNER'), CH('PARTNER').Direction)
    end)
    local coro2 = TASK:BranchCoroutine(function ()
        UI:SetSpeaker(CH('PARTNER'))
        UI:SetSpeakerEmotion("Inspired")
        UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_PARTNER_9']))
    end)
    TASK:JoinCoroutines({coro1, coro2})

    GROUND:CharTurnToCharAnimated(CH('PARTNER'), CH('PLAYER'), 4)
    GROUND:CharTurnToCharAnimated(CH('PLAYER'), CH('PARTNER'), 4)
    
    UI:SetSpeaker(CH('PARTNER'))
    UI:SetSpeakerEmotion("Happy")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_PARTNER_10_' .. tostring(pTalkKind)], CH('PLAYER'):GetDisplayName()))
    GROUND:CharWaitAnim(CH('PLAYER'), "Nod") -- unsure if this is correct
    GROUND:CharWaitAnim(CH('PLAYER'), "Nod")
    GAME:WaitFrames(45)

    local coro1 = TASK:BranchCoroutine(function() GROUND:CharAnimateTurnTo(CH('PLAYER'), Dir8.Down, 4) end)
	local coro2 = TASK:BranchCoroutine(function() GROUND:CharAnimateTurnTo(CH('PARTNER'), Dir8.Down, 4) end)
	TASK:JoinCoroutines({coro1, coro2})
			
	GAME:WaitFrames(20)

	--pose
	local coro1 = TASK:BranchCoroutine(function() GROUND:CharSetAction(CH('PLAYER'), RogueEssence.Ground.PoseGroundAction(CH('PLAYER').Position, CH('PLAYER').Direction, RogueEssence.Content.GraphicsManager.GetAnimIndex("Pose"))) end) 
	local coro2 = TASK:BranchCoroutine(function() GROUND:CharSetAction(CH('PARTNER'), RogueEssence.Ground.PoseGroundAction(CH('PARTNER').Position, CH('PARTNER').Direction, RogueEssence.Content.GraphicsManager.GetAnimIndex("Pose"))) end)
	TASK:JoinCoroutines({coro1, coro2})

    GAME:WaitFrames(80)
    SOUND:FadeOutBGM(120)
    GAME:FadeOut(false, 60)

    _DATA.Save.ActiveTeam:SetRank('normal')
end

return guild_guildmaster_chambers
