--[[
    init.lua
    Created: 11/22/2023 13:09:48
    Description: Autogenerated script file for the map guild_outside_dusk.
]]--
-- Commonly included lua functions and data
require 'eos.common'
require 'eos.CharacterActions'
require 'eos.ExplorerEssentials'

-- Package name
local guild_outside_dusk = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---guild_outside_dusk.Init(map)
--Engine callback function
function guild_outside_dusk.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  
--COMMON:RespawnAllies()
COMMON:RespawnStarterPartner()
end

---guild_outside_dusk.Enter(map)
--Engine callback function
function guild_outside_dusk.Enter(map)
	ExplorerEssentials.SetProgress(2, 0) -- TEMP
	
	if SV.Progression.Chapter == 1 then
		GAME:CutsceneMode(true)

		guild_outside_dusk.CH1_PartnerWimpsOut()

		GAME:WaitFrames(60)

		--next scene
		GAME:EnterGroundMap("dusk_beach", "C1S1_PlayerSpawn")
	end

	if SV.Progression.Chapter == 2 then
		GAME:CutsceneMode(true)

		if SV.Cutscene.ProgressFlag == 1 then
			guild_outside_dusk.CH2_GuildSceneB()
		else
			guild_outside_dusk.CH2_GuildScene()
		end
	end
end

---guild_outside_dusk.Exit(map)
--Engine callback function
function guild_outside_dusk.Exit(map)


end

---guild_outside_dusk.Update(map)
--Engine callback function
function guild_outside_dusk.Update(map)


end

---guild_outside_dusk.GameSave(map)
--Engine callback function
function guild_outside_dusk.GameSave(map)


end

---guild_outside_dusk.GameLoad(map)
--Engine callback function
function guild_outside_dusk.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------



-------------------------------
-- Cutscene Functions
-------------------------------

function guild_outside_dusk.CH1_PartnerWimpsOut()
	GROUND:Hide("PLAYER")
	
	local hTalkKind = SV.Personality.HeroTalkKind
	local pTalkKind = SV.Personality.PartnerTalkKind

	local partner = CH("PARTNER")
	
	UI:SetSpeaker(partner)
	local marker = MRKR("CH1_PartnerSpawn")
	local cam = MRKR("CamPos_1")
	GROUND:TeleportTo(partner, marker.Position.X, marker.Position.Y, Direction.Up)
	GAME:MoveCamera(cam.Position.X, cam.Position.Y, 1, false)
  
    local coro1 = TASK:BranchCoroutine(function() SOUND:FadeInSE("Ambient/AMB_Fire_Loud", 60) end)
	local coro2 = TASK:BranchCoroutine(function() GAME:FadeIn(60) end)
	TASK:JoinCoroutines({coro1, coro2})
	
    GAME:WaitFrames(60)
    UI:SetSpeakerEmotion("Worried")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_Partner_1']))
	
	GAME:WaitFrames(10)
	GROUND:MoveInDirection(partner, Direction.Right, 24, false, 1)
	GROUND:MoveInDirection(partner, Direction.Left, 48, false, 1)
	GROUND:MoveInDirection(partner, Direction.Right, 48, false, 1)
	GROUND:MoveInDirection(partner, Direction.Left, 24, false, 1)
	
	GAME:WaitFrames(45)
	
	GROUND:CharAnimateTurnTo(partner, Direction.Up, 2)
	
	UI:SetSpeakerEmotion("Determined")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_Partner_2']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_Partner_3_'..tostring(pTalkKind)]))
	
	GROUND:MoveInDirection(partner, Direction.Up, 24, false, 1)
	
	SOUND:PlayBattleSE("EVT_Emote_Shock")
	GROUND:CharSetEmote(partner, "shock", 1)
	ExplorerEssentials.SetSpeakerUnknown(nil)
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_Unknown_1']), {
		function()
			CharacterActions.ScaredJump(partner, Direction.Up)
		end
	})
	
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_Unknown_2']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_Unknown_3'], _DATA:GetMonster(partner.CurrentForm.Species):GetColoredName()))
	
	GROUND:CharSetEmote(partner, "shock", 1)
	GROUND:AnimateInDirection(partner, "Walk", Direction.Up, Direction.Down, 12, 1, 2)
	UI:SetSpeaker(partner)
	UI:SetSpeakerEmotion("Surprised")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_Partner_4']))
	
	SOUND:PlayBattleSE("EVT_Emote_Confused_2")
    GROUND:CharSetEmote(partner, "sweating", 1)
    GROUND:CharAnimateTurnTo(partner, Direction.Right, 1)
    GAME:WaitFrames(5)
    GROUND:CharAnimateTurnTo(partner, Direction.Left, 1)
    GAME:WaitFrames(15)
    GROUND:CharAnimateTurnTo(partner, Direction.Right, 1)
    GAME:WaitFrames(5)
    GROUND:CharAnimateTurnTo(partner, Direction.Up, 1)
    GAME:WaitFrames(45)
    GROUND:CharSetEmote(partner, "sweating", 1)
	
	GAME:WaitFrames(10)
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_Partner_5_'..tostring(pTalkKind)]))
	
	GAME:WaitFrames(30)
	SOUND:PlayBattleSE("EVT_Emote_Sweatdrop")
	GROUND:CharSetEmote(partner, "sweatdrop", 1)
	UI:SetSpeakerEmotion("Sigh")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_Partner_6']))
	
	GAME:WaitFrames(15)
	UI:SetSpeakerEmotion("Sad")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_Partner_7_'..tostring(pTalkKind)]))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_Partner_8_'..tostring(pTalkKind)]))
	
	GROUND:MoveInDirection(partner, Direction.Up, 16, false, 1)
	SOUND:PlayBattleSE("EVT_CH02_Item_Place")
	GROUND:TeleportTo(OBJ("RelicFragment"), partner.Position.X, partner.Position.Y - 1, Direction.Down)
	GAME:WaitFrames(15)
	GROUND:AnimateInDirection(partner, "Walk", Direction.Up, Direction.Down, 16, 1, 1)
	GAME:WaitFrames(30)
	
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_Partner_9']))
	
	GAME:WaitFrames(30)
	GROUND:MoveInDirection(partner, Direction.Up, 16, false, 1)
	GROUND:Hide("RelicFragment")
	GAME:WaitFrames(15)
	GROUND:AnimateInDirection(partner, "Walk", Direction.Up, Direction.Down, 16, 1, 1)
	
	GAME:WaitFrames(45)
	CharacterActions.ShakeHead(partner, Direction.Up)
	GAME:WaitFrames(30)
	
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_Partner_10_'..tostring(pTalkKind)]))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_Partner_11']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_Partner_12']))
	
	GROUND:CharAnimateTurnTo(partner, Direction.Down, 5)
	GAME:WaitFrames(20)
	
	local coro1 = TASK:BranchCoroutine(function() GROUND:MoveInDirection(partner, Direction.Down, 240, false, 1) end)
	local coro2 = TASK:BranchCoroutine(function() GAME:MoveCamera(cam.Position.X, (cam.Position.Y + 125), 120, false) end)
	TASK:JoinCoroutines({coro1, coro2})
	
	GAME:WaitFrames(90)
	
	local koffing = CH("Koffing")
	local zubat = CH("Zubat")
	marker = MRKR("CH1_KoffingSpawn")
	GROUND:TeleportTo(koffing, marker.Position.X, (marker.Position.Y - 20), Direction.Down)
	marker = MRKR("CH1_ZubatSpawn")
	GROUND:TeleportTo(zubat, marker.Position.X, (marker.Position.Y - 20), Direction.Down)
	
	local pos1 = MRKR("CH1_KoffingPos")
	local pos2 = MRKR("CH1_ZubatPos")
	
	local coro1 = TASK:BranchCoroutine(function() GAME:WaitFrames(10)
										GROUND:MoveToPosition(koffing, pos1.Position.X, pos1.Position.Y, false, 1)
										GROUND:CharAnimateTurnTo(koffing, Direction.Down, 5)	end)
	local coro2 = TASK:BranchCoroutine(function() GROUND:MoveToPosition(zubat, pos2.Position.X, pos2.Position.Y, false, 1)
										GROUND:CharAnimateTurnTo(zubat, Direction.Down, 5)	end)
	local coro3 = TASK:BranchCoroutine(function() GAME:MoveCamera(cam.Position.X, cam.Position.Y, 180, false) end)
	TASK:JoinCoroutines({coro1, coro2, coro3})
	
	GAME:WaitFrames(45)
	
	--"\uE040"
	ExplorerEssentials.SetSpeakerUnknown(koffing)
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_Koffing_1'], zubat:GetDisplayName()))
	
	GAME:WaitFrames(10)
	UI:SetSpeaker(zubat)
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_Zubat_1'], koffing:GetDisplayName()))
	
	GAME:WaitFrames(10)
	UI:SetSpeaker(koffing)
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_Koffing_2']))
	
	GAME:WaitFrames(10)
	UI:SetSpeaker(zubat)
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_Zubat_2']))
	
	GAME:WaitFrames(10)
	GROUND:CharTurnToCharAnimated(koffing, zubat, 4, true)
	UI:SetSpeaker(koffing)
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_Koffing_3']))
	
	GAME:WaitFrames(10)
	GROUND:CharTurnToCharAnimated(zubat, koffing, 4, true)
	UI:SetSpeaker(zubat)
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_Zubat_3']))
	
	--nod
	local coro1 = TASK:BranchCoroutine(function() GROUND:CharWaitAnim(koffing, "Nod")
										GAME:WaitFrames(45)
										GROUND:MoveInDirection(koffing, Direction.Down, 180, false, 1)	end)
	local coro2 = TASK:BranchCoroutine(function() GROUND:CharWaitAnim(zubat, "Nod")
										GAME:WaitFrames(45)
										GAME:WaitFrames(10)
										GROUND:MoveInDirection(zubat, Direction.Down, 180, false, 1)	end)
	local coro3 = TASK:BranchCoroutine(function() GAME:WaitFrames(300)
										GAME:FadeOut(false, 60) end)
	local coro4 = TASK:BranchCoroutine(function() GAME:WaitFrames(300)
										SOUND:FadeOutSE("Ambient/AMB_Fire_Loud", 150)
										end)
	TASK:JoinCoroutines({coro1, coro2, coro3, coro4})
end

function guild_outside_dusk.CH2_GuildScene()

	local player = CH("PLAYER")
	local partner = CH("PARTNER")
	
	local hTalkKind = SV.Personality.HeroTalkKind
	local pTalkKind = SV.Personality.PartnerTalkKind
	
	local cam = MRKR("CamPos_1")
    GAME:MoveCamera(cam.Position.X, cam.Position.Y, 1, false)
	local marker = MRKR("CH1_ZubatPos")
    GROUND:TeleportTo(player, marker.Position.X, marker.Position.Y, Direction.Up)
	local marker = MRKR("CH1_KoffingPos")
    GROUND:TeleportTo(partner, marker.Position.X, marker.Position.Y, Direction.Up)

	local coro1 = TASK:BranchCoroutine(function() SOUND:FadeInSE("Ambient/AMB_Fire_Loud", 60) end)
	local coro2 = TASK:BranchCoroutine(function() GAME:FadeIn(60) end)
	TASK:JoinCoroutines({coro1, coro2})
	
	UI:SetSpeaker(partner)
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Partner_1_'..tostring(pTalkKind)], CH('Wigglytuff'):GetDisplayName())) --TODO: Add Wigglytuff Dummy

	GROUND:CharAnimateTurnTo(player, Direction.Left, 4)	
	GROUND:CharAnimateTurnTo(partner, Direction.Right, 4)

    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Partner_2']))
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Partner_3']))

	GROUND:CharAnimateTurnTo(player, Direction.Up, 4)	
	GROUND:CharAnimateTurnTo(partner, Direction.Up, 4)

	GAME:WaitFrames(40)

	UI:SetSpeakerEmotion("Worried")
    local coro1 = TASK:BranchCoroutine(function() UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Partner_4']), {
		function ()
			GROUND:CharEndAnim(partner)
		end
	}) end)
	local coro2 = TASK:BranchCoroutine(function() GROUND:CharSetAnim(partner, "Charge", true) end)
	TASK:JoinCoroutines({coro1, coro2})

	GROUND:CharEndAnim(partner) -- juuuuust in case the text script fails

	GROUND:CharAnimateTurnTo(partner, Direction.Right, 4)
	GROUND:CharAnimateTurnTo(player, Direction.Left, 4)	

	UI:SetSpeakerEmotion("Sad")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Partner_5_'..tostring(pTalkKind)]))

	GROUND:CharAnimateTurnTo(partner, Direction.Right, 4)
	GROUND:CharAnimateTurnTo(player, Direction.Left, 4)	

	UI:SetSpeakerEmotion("Determined")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Partner_6'], player:GetDisplayName()))

	GROUND:CharAnimateTurnTo(partner, Direction.Up, 2)
	CharacterActions.HopOnce(partner, Direction.Up)
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Partner_7']))

	local coro1 = TASK:BranchCoroutine(function() 
		GROUND:MoveToPosition(partner, cam.Position.X, cam.Position.Y - 4, false, 1)
		GROUND:CharAnimateTurnTo(partner, Direction.Up, 4) 
	end)
	local coro2 = TASK:BranchCoroutine(function()
		GROUND:CharAnimateTurnTo(player, Direction.Up, 10)
	end)
	TASK:JoinCoroutines({coro1, coro2})
	
	GAME:WaitFrames(40)

	ExplorerEssentials.SetSpeakerUnknown(nil)
	SOUND:PlayBattleSE("EVT_Emote_Shock")
	GROUND:CharSetEmote(partner, "shock", 1)
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Unknown_1']))		
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Unknown_2']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH1_Unknown_3'], _DATA:GetMonster(partner.CurrentForm.Species):GetColoredName()))

	SOUND:PlayBattleSE("EVT_Emote_Sweating")
	GROUND:CharSetEmote(partner, "sweating", 1)
	UI:SetSpeaker(partner)
	UI:SetSpeakerEmotion("Surprised")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Partner_8']))
    
	GROUND:CharSetAnim(partner, "Charge", true)
	GAME:WaitFrames(60)
	GROUND:CharEndAnim(partner)
	GAME:WaitFrames(20)

	UI:SetSpeakerEmotion("Pain")
    UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Partner_9_'..tostring(pTalkKind)]))

	GAME:WaitFrames(60)
	
	ExplorerEssentials.SetSpeakerUnknown(nil)
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Unknown_3'])) --you may enter dialoge
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Unknown_4']))

	GAME:WaitFrames(40)
	GROUND:MoveToPosition(partner, MRKR("CH1_KoffingPos").Position.X - 8, cam.Position.Y - 4, false, 1)
    GROUND:CharAnimateTurnTo(partner, Direction.Right, 4)

	GAME:WaitFrames(180)
    GROUND:CharAnimateTurnTo(partner, Direction.DownRight, 4)

	GAME:WaitFrames(40)
	SOUND:PlayBattleSE("EVT_Emote_Sweating")
	GROUND:CharSetEmote(partner, "sweating", 1)
	
	GAME:WaitFrames(40)
	GROUND:CharAnimateTurnTo(player, Direction.UpLeft, 4)

	UI:SetSpeaker(partner)
	UI:SetSpeakerEmotion("Worried")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Partner_10_'..tostring(pTalkKind)], player:GetDisplayName()))

    GROUND:CharAnimateTurnTo(partner, Direction.Right, 4)
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Partner_11']))

    GROUND:CharAnimateTurnTo(partner, Direction.DownRight, 4)
	GAME:WaitFrames(20)
	GROUND:CharAnimateTurnTo(player, Direction.Up, 4)

	-- show the grate closeup? might not be worth it since you can just see it anyways

	GAME:WaitFrames(30)
	ExplorerEssentials.SetSpeakerHero()
	UI:SetSpeakerEmotion("Normal")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Hero_1']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Hero_2']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Hero_3']))
	UI:SetSpeakerEmotion("Worried")
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Hero_4']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Hero_5']))

	SOUND:PlayBattleSE("EVT_Emote_Exclaim")
	GROUND:CharSetEmote(player, "exclaim", 1)
	GROUND:CharSetEmote(partner, "exclaim", 1)
	ExplorerEssentials.SetSpeakerUnknown(nil)
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Unknown_5']))

	GAME:WaitFrames(30)
	GROUND:CharAnimateTurnTo(partner, Direction.Right, 2)
	GROUND:MoveToPosition(player, cam.Position.X, cam.Position.Y - 4, false, 1)
    GROUND:CharAnimateTurnTo(player, Direction.Up, 2)

	GAME:WaitFrames(40)
	
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Unknown_1']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Unknown_2']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Unknown_6']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Unknown_7']))
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Unknown_8'], CH('Diglett'):GetDisplayName()))
	UI:SetSpeaker(CH('Diglett'):GetDisplayName(), true)
	UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Diglett_1']))

	-- transition
	local coro1 = TASK:BranchCoroutine(function() GAME:FadeOut(false, 60) end)
	local coro2 = TASK:BranchCoroutine(function() SOUND:FadeOutSE("Ambient/AMB_Fire_Loud", 60) end)
	TASK:JoinCoroutines({coro1, coro2})
	
	SV.Cutscene.ProgressFlag = 1
	-- go to grate scene

	GAME:RestartToTitle() -- TEMP
end

function guild_outside_dusk.CH2_GuildSceneB()

	local player = CH("PLAYER")
	local partner = CH("PARTNER")
	
	local hTalkKind = SV.Personality.HeroTalkKind
	local pTalkKind = SV.Personality.PartnerTalkKind
	
	local cam = MRKR("CamPos_1")
    GAME:MoveCamera(cam.Position.X, cam.Position.Y, 1, false)
	local marker = MRKR("CH1_ZubatPos")
    GROUND:TeleportTo(player, marker.Position.X - 16, marker.Position.Y - 24, Direction.Up)
	local marker = MRKR("CH1_KoffingPos")
    GROUND:TeleportTo(partner, marker.Position.X - 24, marker.Position.Y - 24, Direction.Right)
	GROUND:CharSetEmote(player, "sweatdrop", 1)
	GROUND:CharSetEmote(partner, "sweatdrop", 1)
	GROUND:CharAnimateTurnTo(player, Direction.Left, 2)
	--UI:SetSpeaker(partner)
	--UI:SetSpeakerEmotion("Worried")
	--UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Partner_11']))
	--UI:ResetSpeaker()
        --UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Unknown_7']))
	GROUND:CharSetEmote(player, "notice", 1)
	GROUND:CharSetEmote(player, "notice", 1)
	GROUND:CharAnimateTurnTo(player, Direction.Up, 2)
	--UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Unknown_8']))
	--UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Unknown_9']))
	--UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Unknown_10']))

	-- ANIMATE GATE OPENING

	GROUND:CharAnimateTurnTo(partner, Direction.UpRight, 2)
	CharacterActions.ScaredJump(partner, Direction.Up)
	GROUND:CharSetEmote(player, "shock", 1)
	GROUND:CharAnimateTurnTo(partner, Direction.Right, 2)
	GROUND:CharAnimateTurnTo(player, Direction.Left, 2)
	--UI:SetSpeaker(partner)
	--UI:SetSpeakerEmotion("Shock")
	--UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Partner_12']))
	--UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Partner_13']))
	--UI:SetSpeakerEmotion("Normal")
	--UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Partner_14']))
	--UI:WaitShowDialogue(STRINGS:Format(STRINGS.MapStrings['CH2_Partner_15']))
	GROUND:MoveToPosition(player, marker.Position.X + 16, marker.Position.Y - 40, false, 1)	
	GROUND:Hide("PLAYER")
	GROUND:MoveToPosition(partner, marker.Position.X + 16, marker.Position.Y - 24, false, 1)	
	GROUND:MoveToPosition(partner, marker.Position.X + 16, marker.Position.Y - 40, false, 1)	
	GROUND:Hide("PARTNER")
	--GAME:FadeOut(false, 60)
	--jump to scene inside top of guild

end



return guild_outside_dusk

