--[[
    init.lua
    Created: 11/22/2023 12:14:44
    Description: Autogenerated script file for the map crossroads_south.
]]--
-- Commonly included lua functions and data
require 'eos.common'
require 'eos.PartnerEssentials'
require 'eos.CharacterActions'
require 'eos.ExplorerEssentials'
require 'eos.GeneralFunctions'

-- Package name
local crossroads_south = {}

-- Local, localized strings table
-- Use this to display the named strings you added in the strings files for the map!
-- Ex:
--      local localizedstring = STRINGS.MapStrings['SomeStringName']


-------------------------------
-- Map Callbacks
-------------------------------
---crossroads_south.Init(map)
--Engine callback function
function crossroads_south.Init(map)

  --This will fill the localized strings table automatically based on the locale the game is 
  -- currently in. You can use the MapStrings table after this line!
  
SOUND:PlayBGM("014 - Treasure Town.ogg", true)
COMMON:RespawnAllies()
PartnerEssentials.InitializePartnerSpawn()
end

---crossroads_south.Enter(map)
--Engine callback function
function crossroads_south.Enter(map)

  GAME:FadeIn(20)

end

---crossroads_south.Exit(map)
--Engine callback function
function crossroads_south.Exit(map)

GAME:FadeOut(false, 20)
end

---crossroads_south.Update(map)
--Engine callback function
function crossroads_south.Update(map)


end

---crossroads_south.GameSave(map)
--Engine callback function
function crossroads_south.GameSave(map)


end

---crossroads_south.GameLoad(map)
--Engine callback function
function crossroads_south.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function crossroads_south.BeachEntrance_Touch(obj, activator)
SV.partner.Spawn = 'Entrance'
GAME:EnterGroundMap("beach", "Entrance")

end

function crossroads_south.CrossRoadsAssemblyEntrance_Touch(obj, activator)
SV.partner.Spawn = 'CrossRoadsSouthEntranceMarker'
GAME:EnterGroundMap("crossroads_assembly", "CrossRoadsSouthEntranceMarker")

end

return crossroads_south

