--[[
    init.lua
    Created: 09/26/2023 13:53:10
    Description: Autogenerated script file for the map cutscenes.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local cutscenes = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---cutscenes.Init(zone)
--Engine callback function
function cutscenes.Init(zone)


end

---cutscenes.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function cutscenes.EnterSegment(zone, rescuing, segmentID, mapID)


end

---cutscenes.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function cutscenes.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---cutscenes.Rescued(zone, name, mail)
--Engine callback function
function cutscenes.Rescued(zone, name, mail)


end

return cutscenes

