--[[
    init.lua
    Created: 12/02/2023 17:20:52
    Description: Autogenerated script file for the map beach_cave.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local beach_cave = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---beach_cave.Init(zone)
--Engine callback function
function beach_cave.Init(zone)


end

---beach_cave.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function beach_cave.EnterSegment(zone, rescuing, segmentID, mapID)
	COMMON.BeginDungeon(zone.ID, segmentID, mapID)
end

---beach_cave.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function beach_cave.ExitSegment(zone, result, rescue, segmentID, mapID)
  DEBUG.EnableDbgCoro() --Enable debugging this coroutine
  PrintInfo("=>> ExitSegment_beach_cave (Beach Cave) result "..tostring(result).." segment "..tostring(segmentID))

	GAME:SetRescueAllowed(false)
	
	SV.Dungeon.Zone = zone
	SV.Dungeon.Result = result
	SV.Dungeon.Rescue = rescue
	SV.Dungeon.SegmentID = segmentID
	SV.Dungeon.MapID = mapID
	
	if segmentID == 0 then -- main beach cave
	
		if result == RogueEssence.Data.GameProgress.ResultType.Cleared then --success
		
			GAME:EndDungeonRun(result, 'beach_cave', -1, 0, 0, false, false)	
			GAME:EnterZone("beach_cave", -1, 0, 0)	
			
		else --fail
		
			SV.beach_cave.FailedDungeon = true
			GAME:EndDungeonRun(result, "cutscenes", -1, 6, 0, true, true)	
			GAME:EnterZone("cutscenes", -1, 6, 0)	
			
		end
		
	else --triggered only from the boss map
	
		if result == RogueEssence.Data.GameProgress.ResultType.Cleared then --success
			
			--do another cutscene and end the dungeon day there
			SV.Progression.SectionFlag = 1
			GAME:EndDungeonRun(result, 'beach_cave', -1, 0, 0, false, false)	
			GAME:EnterZone("beach_cave", -1, 0, 0)
			
		else --fail
		
			SV.beach_cave.FailedDungeon = true
			SV.beach_cave.FailedBoss = true
			GAME:EndDungeonRun(result, "cutscenes", -1, 6, 0, true, true)	
			GAME:EnterZone("cutscenes", -1, 6, 0)
			
		end
	
	end
end

---beach_cave.Rescued(zone, name, mail)
--Engine callback function
function beach_cave.Rescued(zone, name, mail)
	COMMON.Rescued(zone, mail)

end

return beach_cave

