--[[
    init.lua
    Created: 12/02/2023 17:20:52
    Description: Autogenerated script file for the map beach_cave.
]]--
-- Commonly included lua functions and data
require 'common'

-- Package name
local beach_cave = {}

-------------------------------
-- Zone Callbacks
-------------------------------
---beach_cave.Init(zone)
--Engine callback function
function beach_cave.Init(zone)


end

---beach_cave.EnterSegment(zone, rescuing, segmentID, mapID)
--Engine callback function
function beach_cave.EnterSegment(zone, rescuing, segmentID, mapID)


end

---beach_cave.ExitSegment(zone, result, rescue, segmentID, mapID)
--Engine callback function
function beach_cave.ExitSegment(zone, result, rescue, segmentID, mapID)


end

---beach_cave.Rescued(zone, name, mail)
--Engine callback function
function beach_cave.Rescued(zone, name, mail)


end

return beach_cave

