--[[
    init.lua
    Created: 09/23/2026 15:00:52
    Description: Autogenerated script file for the map placeholder_room.
]]--
-- Commonly included lua functions and data
require 'origin.common'

-- Package name
local placeholder_room = {}

-------------------------------
-- Map Callbacks
-------------------------------
---placeholder_room.Init(map)
--Engine callback function
function placeholder_room.Init(map)


end

---placeholder_room.Enter(map)
--Engine callback function
function placeholder_room.Enter(map)

  GAME:FadeIn(20)

end

---placeholder_room.Exit(map)
--Engine callback function
function placeholder_room.Exit(map)


end

---placeholder_room.Update(map)
--Engine callback function
function placeholder_room.Update(map)


end

---placeholder_room.GameSave(map)
--Engine callback function
function placeholder_room.GameSave(map)


end

---placeholder_room.GameLoad(map)
--Engine callback function
function placeholder_room.GameLoad(map)

  GAME:FadeIn(20)

end

-------------------------------
-- Entities Callbacks
-------------------------------

function placeholder_room.Unknown_Action(obj, activator)
  
end

function placeholder_room.Exit_Touch(obj, activator)
  GROUND:EnterGroundMap("hub", "guild_bedroom", "Entrance", false)
end

return placeholder_room

